---
title: "pest_cmd_qgcomp_v8_sa2"
author: "LCalderon"
date: '2025-12-09'
output: html_document
---

### SET UP DATA
```{r, load and setup data}
# Clear workspace
rm(list=ls())

# Set working directory
#setwd("/Users/lcalderon1/Library/CloudStorage/Box-Box/CHAM Maternal Cognition Study/Analyses and Manuscripts/Lucia's analyses/CHAM PUR Cardiometabolic/Analysis 2")
setwd("C:/Users/lucia/Box/CHAM Maternal Cognition Study/Analyses and Manuscripts/Lucia's analyses/CHAM PUR Cardiometabolic/Analysis 2/")

library(tableone)
library(fastDummies)
library(coda)
library(dplyr)
library(haven)
library(multcomp)
library(ggplot2)
library(qgcomp)
library(qgcompint)
library(gfoRmula)
library(broom)
library(boot)

# Read in Data from Stata (this dataset only includes the analytic sample)
data<-read_dta("pest_cmd_analysis_v6.dta") 

# Drop outliers for continuous outcomes
data$mbmi_mc1[data$mbmi_mc1_out==1]<-NA
data$mwaist_mc1[data$mwaist_mc1_out==1]<-NA
data$mbpsys_mc1[data$mbpsys_mc1_out==1]<-NA
data$mbpdia_mc1[data$mbpdia_mc1_out==1]<-NA
data$mbppul_mc1[data$mbppul_mc1_out==1]<-NA
data$mbpmap_mc1[data$mbpmap_mc1_out==1]<-NA
data$gluc_mc1[data$gluc_mc1_out==1]<-NA
data$hba1c_mc1[data$hba1c_mc1_out==1]<-NA
data$log_trig_mc1[data$log_trig_mc1_out==1]<-NA
data$hdl_mc1[data$hdl_mc1_out==1]<-NA
data$log_crp_mc1[data$log_crp_mc1_out==1]<-NA
data$log_il6_mc1[data$log_il6_mc1_out==1]<-NA

# Exclude those taking meds from relevant continuous outcomes
data$mbpsys_mc1[data$mbpsys_mc1_med==1]<-NA
data$mbpdia_mc1[data$mbpdia_mc1_med==1]<-NA
data$mbppul_mc1[data$mbppul_mc1_med==1]<-NA
data$mbpmap_mc1[data$mbpmap_mc1_med==1]<-NA
data$gluc_mc1[data$gluc_mc1_med==1]<-NA
data$hba1c_mc1[data$hba1c_mc1_med==1]<-NA
data$log_trig_mc1[data$log_trig_mc1_med==1]<-NA
data$hdl_mc1[data$hdl_mc1_med==1]<-NA

# Exclude non-fasting laboratory outcomes
data$gluc_mc1[data$gluc_mc1_nf==1]<-NA
data$hba1c_mc1[data$hba1c_mc1_nf==1]<-NA
data$log_trig_mc1[data$log_trig_mc1_nf==1]<-NA
data$hdl_mc1[data$hdl_mc1_nf==1]<-NA
data$log_crp_mc1[data$log_crp_mc1_nf==1]<-NA
data$log_il6_mc1[data$log_il6_mc1_nf==1]<-NA

# Table 1 to check consistency with Stata analysis 
myvars<- c("age_dl","ageusa_cat_bl","meducat_bl","imarcat_10_5y","iagwork_10_5y","i2_povcat2_10_5y",
           "mhtn_mc1","diabetes_mc1","mobese_mc1","waist_ind_mc1","bp_ind_mc1","gluc_ind_mc1","trig_ind_mc1","chdl_ind_mc1","metsyn_mc1","crp_cat_mc1",
           "mbpsys_mc1","mbpdia_mc1","mbppul_mc1","mbpmap_mc1","mbmi_mc1","mwaist_mc1","gluc_mc1","hba1c_mc1","log_trig_mc1","hdl_mc1","log_crp_mc1","log_il6_mc1")
mycatvars<-c("ageusa_cat_bl","meducat_bl","imarcat_10_5y","iagwork_10_5y","i2_povcat2_10_5y",
             "mhtn_mc1","diabetes_mc1","mobese_mc1","waist_ind_mc1","bp_ind_mc1","gluc_ind_mc1","trig_ind_mc1","chdl_ind_mc1","metsyn_mc1","crp_cat_mc1")
table1<-CreateTableOne(vars=myvars, data=data, factorVars=mycatvars)
tab1print<-print(table1, showAlllevels=T, catDigits=1, contDigits=1, pDigits=1, test=F, printToggle = FALSE)

#Subset out relevant covariates
data<-dummy_cols(data, select_columns = c("ageusa_cat_bl","meducat_bl","iagwork_10_5y"), 
                 remove_first_dummy = TRUE, remove_selected_columns = FALSE, 
                 remove_most_frequent_dummy = FALSE, ignore_na = FALSE)
W <- subset(data, select = c("age_dl","ageusa_cat_bl_2","ageusa_cat_bl_3","meducat_bl_2","meducat_bl_3",
                             "imarcat_10_5y","iagwork_10_5y_2","iagwork_10_5y_3","i2_povcat2_10_5y"))
W<-as.matrix(W)

#IPAWs
S<- subset(data, select = "ipaw")

#Exposures
X<- subset(data, select = c("op",
                            "pyr",
                            "carb",
                            "neo",
                            "mn",
                            "gly",
                            "paraq"))

X <- as.matrix(X)

##Vectorize individual outcomes of interest from Y
Y_sys<-as.vector(data$mbpsys_mc1)
Y_dia<-as.vector(data$mbpdia_mc1)
Y_pul<-as.vector(data$mbppul_mc1)
Y_map<-as.vector(data$mbpmap_mc1)
Y_bmi<-as.vector(data$mbmi_mc1)
Y_wai<-as.vector(data$mwaist_mc1)
Y_glu<-as.vector(data$gluc_mc1)
Y_hba<-as.vector(data$hba1c_mc1)
Y_tri<-as.vector(data$log_trig_mc1)
Y_hdl<-as.vector(data$hdl_mc1)
Y_crp<-as.vector(data$log_crp_mc1)
Y_il6<-as.vector(data$log_il6_mc1)

Y_hyper<-as.vector(data$mhtn_mc1)
Y_diabe<-as.vector(data$diabetes_mc1)
Y_obese<-as.vector(data$mobese_mc1)
Y_waind<-as.vector(data$waist_ind_mc1)
Y_bpind<-as.vector(data$bp_ind_mc1)
Y_glind<-as.vector(data$gluc_ind_mc1)
Y_trind<-as.vector(data$trig_ind_mc1)
Y_chind<-as.vector(data$chdl_ind_mc1)
Y_metab<-as.vector(data$metsyn_mc1)
Y_crpca<-as.vector(data$crp_cat_mc1)

##Complete Case Flag for each Outcome
is.cc.sys <- complete.cases(cbind(W,X,Y_sys,S))
is.cc.dia <- complete.cases(cbind(W,X,Y_dia,S))
is.cc.pul <- complete.cases(cbind(W,X,Y_pul,S))
is.cc.map <- complete.cases(cbind(W,X,Y_map,S))
is.cc.bmi <- complete.cases(cbind(W,X,Y_bmi,S))
is.cc.wai <- complete.cases(cbind(W,X,Y_wai,S))
is.cc.glu <- complete.cases(cbind(W,X,Y_glu,S))
is.cc.hba <- complete.cases(cbind(W,X,Y_hba,S))
is.cc.tri <- complete.cases(cbind(W,X,Y_tri,S))
is.cc.hdl <- complete.cases(cbind(W,X,Y_hdl,S))
is.cc.crp <- complete.cases(cbind(W,X,Y_crp,S))
is.cc.il6 <- complete.cases(cbind(W,X,Y_il6,S))

is.cc.hyper <- complete.cases(cbind(W,X,Y_hyper,S))
is.cc.diabe <- complete.cases(cbind(W,X,Y_diabe,S))
is.cc.obese <- complete.cases(cbind(W,X,Y_obese,S))
is.cc.waind <- complete.cases(cbind(W,X,Y_waind,S))
is.cc.bpind <- complete.cases(cbind(W,X,Y_bpind,S))
is.cc.glind <- complete.cases(cbind(W,X,Y_glind,S))
is.cc.trind <- complete.cases(cbind(W,X,Y_trind,S))
is.cc.chind <- complete.cases(cbind(W,X,Y_chind,S))
is.cc.metab <- complete.cases(cbind(W,X,Y_metab,S))
is.cc.crpca <- complete.cases(cbind(W,X,Y_crpca,S))

##Subset outcomes as complete cases
Y.cc.sys <- subset(Y_sys,is.cc.sys) 
Y.cc.dia <- subset(Y_dia,is.cc.dia) 
Y.cc.pul <- subset(Y_pul,is.cc.pul) 
Y.cc.map <- subset(Y_map,is.cc.map) 
Y.cc.bmi <- subset(Y_bmi,is.cc.bmi)
Y.cc.wai <- subset(Y_wai,is.cc.wai)
Y.cc.glu <- subset(Y_glu,is.cc.glu)
Y.cc.hba <- subset(Y_hba,is.cc.hba)
Y.cc.tri <- subset(Y_tri,is.cc.tri)
Y.cc.hdl <- subset(Y_hdl,is.cc.hdl)
Y.cc.crp <- subset(Y_crp,is.cc.crp)
Y.cc.il6 <- subset(Y_il6,is.cc.il6)

Y.cc.hyper <- subset(Y_hyper,is.cc.hyper)
Y.cc.diabe <- subset(Y_diabe,is.cc.diabe)
Y.cc.obese <- subset(Y_obese,is.cc.obese)
Y.cc.waind <- subset(Y_waind,is.cc.waind)
Y.cc.bpind <- subset(Y_bpind,is.cc.bpind)
Y.cc.glind <- subset(Y_glind,is.cc.glind)
Y.cc.trind <- subset(Y_trind,is.cc.trind)
Y.cc.chind <- subset(Y_chind,is.cc.chind)
Y.cc.metab <- subset(Y_metab,is.cc.metab)
Y.cc.crpca <- subset(Y_crpca,is.cc.crpca)

# Set up data frames for regression models
data.sys <- as.data.frame(cbind(Y.cc.sys, X[is.cc.sys,], W[is.cc.sys,], S[is.cc.sys,]))
data.dia <- as.data.frame(cbind(Y.cc.dia, X[is.cc.dia,], W[is.cc.dia,], S[is.cc.dia,]))
data.pul <- as.data.frame(cbind(Y.cc.pul, X[is.cc.pul,], W[is.cc.pul,], S[is.cc.pul,]))
data.map <- as.data.frame(cbind(Y.cc.map, X[is.cc.map,], W[is.cc.map,], S[is.cc.map,]))
data.bmi <- as.data.frame(cbind(Y.cc.bmi, X[is.cc.bmi,], W[is.cc.bmi,], S[is.cc.bmi,]))
data.wai <- as.data.frame(cbind(Y.cc.wai, X[is.cc.wai,], W[is.cc.wai,], S[is.cc.wai,]))
data.glu <- as.data.frame(cbind(Y.cc.glu, X[is.cc.glu,], W[is.cc.glu,], S[is.cc.glu,]))
data.hba <- as.data.frame(cbind(Y.cc.hba, X[is.cc.hba,], W[is.cc.hba,], S[is.cc.hba,]))
data.tri <- as.data.frame(cbind(Y.cc.tri, X[is.cc.tri,], W[is.cc.tri,], S[is.cc.tri,]))
data.hdl <- as.data.frame(cbind(Y.cc.hdl, X[is.cc.hdl,], W[is.cc.hdl,], S[is.cc.hdl,]))
data.crp <- as.data.frame(cbind(Y.cc.crp, X[is.cc.crp,], W[is.cc.crp,], S[is.cc.crp,]))
data.il6 <- as.data.frame(cbind(Y.cc.il6, X[is.cc.il6,], W[is.cc.il6,], S[is.cc.il6,]))

data.hyper <- as.data.frame(cbind(Y.cc.hyper, X[is.cc.hyper,], W[is.cc.hyper,], S[is.cc.hyper,]))
data.diabe <- as.data.frame(cbind(Y.cc.diabe, X[is.cc.diabe,], W[is.cc.diabe,], S[is.cc.diabe,]))
data.obese <- as.data.frame(cbind(Y.cc.obese, X[is.cc.obese,], W[is.cc.obese,], S[is.cc.obese,]))
data.waind <- as.data.frame(cbind(Y.cc.waind, X[is.cc.waind,], W[is.cc.waind,], S[is.cc.waind,]))
data.bpind <- as.data.frame(cbind(Y.cc.bpind, X[is.cc.bpind,], W[is.cc.bpind,], S[is.cc.bpind,]))
data.glind <- as.data.frame(cbind(Y.cc.glind, X[is.cc.glind,], W[is.cc.glind,], S[is.cc.glind,]))
data.trind <- as.data.frame(cbind(Y.cc.trind, X[is.cc.trind,], W[is.cc.trind,], S[is.cc.trind,]))
data.chind <- as.data.frame(cbind(Y.cc.chind, X[is.cc.chind,], W[is.cc.chind,], S[is.cc.chind,]))
data.metab <- as.data.frame(cbind(Y.cc.metab, X[is.cc.metab,], W[is.cc.metab,], S[is.cc.metab,]))
data.crpca <- as.data.frame(cbind(Y.cc.crpca, X[is.cc.crpca,], W[is.cc.crpca,], S[is.cc.crpca,]))

## Testing qgcomp package (From A Keil vignette https://cran.r-project.org/web/packages/qgcomp/vignettes/qgcomp-vignette.html)

  # Mixture names
  Xnm.all <-c("op",
                            "pyr",
                            "carb",
                            "neo",
                            "mn",
                            "gly",
                            "paraq") ##all exposures

  

  ## Individual exposures 
  Xnm.op <-c("op") 
  Xnm.pyr <-c("pyr")
  Xnm.carb <-c("carb")
  Xnm.neo <-c("neo")
  Xnm.mn <-c("mn")
  Xnm.gly <-c("gly")
  Xnm.paraq <-c("paraq")
```

### Continuous outcomes - qgcomp.glm.boot (no weights)
```{r, joint exposure models, continuous outcomes, qgcomp.glm.boot, systolic BP}
qc.fit.boot.sys <- qgcomp.glm.boot(Y.cc.sys ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.sys, #dataset
                                family=gaussian(), 
                                q=4, B=1000, seed=125)
                                
qc.fit.boot.sys

plot(qc.fit.boot.sys)
```

```{r, joint exposure models, continuous outcomes, qgcomp.glm.boot, diastolic BP}
qc.fit.boot.dia <- qgcomp.glm.boot(Y.cc.dia ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.dia, #dataset
                                family=gaussian(), 
                                q=4, B=1000, seed=125)
                                
qc.fit.boot.dia

plot(qc.fit.boot.dia)
```

```{r, joint exposure models, continuous outcomes, qgcomp.glm.boot, pulse pressure}
qc.fit.boot.pul <- qgcomp.glm.boot(Y.cc.pul ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.pul, #dataset
                                family=gaussian(), 
                                q=4, B=1000, seed=125)
                                
qc.fit.boot.pul

plot(qc.fit.boot.pul)
```

```{r, joint exposure models, continuous outcomes, qgcomp.glm.boot, MAP}
qc.fit.boot.map <- qgcomp.glm.boot(Y.cc.map ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.map, #dataset
                                family=gaussian(), 
                                q=4, B=1000, seed=125)
                                
qc.fit.boot.map

plot(qc.fit.boot.map)
```

```{r, joint exposure models, continuous outcomes, qgcomp.glm.boot, triglycerides}
qc.fit.boot.tri <- qgcomp.glm.boot(Y.cc.tri ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.tri, #dataset
                                family=gaussian(), 
                                q=4, B=1000, seed=125)
                                
qc.fit.boot.tri

plot(qc.fit.boot.tri)
```

```{r, joint exposure models, continuous outcomes, qgcomp.glm.boot, HDL}
qc.fit.boot.hdl <- qgcomp.glm.boot(Y.cc.hdl ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.hdl, #dataset
                                family=gaussian(), 
                                q=4, B=1000, seed=125)
                                
qc.fit.boot.hdl

plot(qc.fit.boot.hdl)
```

```{r, joint exposure models, continuous outcomes, qgcomp.glm.boot, glucose}
qc.fit.boot.glu <- qgcomp.glm.boot(Y.cc.glu ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.glu, #dataset
                                family=gaussian(), 
                                q=4, B=1000, seed=125)
                                
qc.fit.boot.glu

plot(qc.fit.boot.glu)
```

```{r, joint exposure models, continuous outcomes, qgcomp.glm.boot, HbA1c}
qc.fit.boot.hba <- qgcomp.glm.boot(Y.cc.hba ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.hba, #dataset
                                family=gaussian(), 
                                q=4, B=1000, seed=125)
                                
qc.fit.boot.hba

plot(qc.fit.boot.hba)
```

```{r, joint exposure models, continuous outcomes, qgcomp.glm.boot, BMI}
qc.fit.boot.bmi <- qgcomp.glm.boot(Y.cc.bmi ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.bmi, #dataset
                                family=gaussian(), 
                                q=4, B=1000, seed=125)
                                
qc.fit.boot.bmi

plot(qc.fit.boot.bmi)
```

```{r, joint exposure models, continuous outcomes, qgcomp.glm.boot, waist circ}
qc.fit.boot.wai <- qgcomp.glm.boot(Y.cc.wai ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.wai, #dataset
                                family=gaussian(), 
                                q=4, B=1000, seed=125)
                                
qc.fit.boot.wai

plot(qc.fit.boot.wai)
```

```{r, joint exposure models, continuous outcomes, qgcomp.glm.boot, CRP}
qc.fit.boot.crp <- qgcomp.glm.boot(Y.cc.crp ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.crp, #dataset
                                family=gaussian(), 
                                q=4, B=1000, seed=125)
                                
qc.fit.boot.crp

plot(qc.fit.boot.crp)
```

```{r, joint exposure models, continuous outcomes, qgcomp.glm.boot, IL6}
qc.fit.boot.il6 <- qgcomp.glm.boot(Y.cc.il6 ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.il6, #dataset
                                family=gaussian(), 
                                q=4, B=1000, seed=125)

qc.fit.boot.il6

plot(qc.fit.boot.il6)
```


### Continuous outcomes - qgcomp.glm.noboot (no weights)
```{r, joint exposure models, continuous outcomes, qgcomp.glm.noboot, systolic BP}
qc.fit.noboot.sys <- qgcomp.glm.noboot(Y.cc.sys ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.sys, #dataset
                                family=gaussian(), 
                                q=4
                                )

qc.fit.noboot.sys

# underlying model of qgcomp fit
qc.fit.noboot.sys$qx$Y.cc.sys <- data.sys$Y.cc.sys # bring outcome back into quantized data

#add the covariates and weights too
qc.fit.noboot.sys$qx$age_dl <- data.sys$age_dl 
qc.fit.noboot.sys$qx$ageusa_cat_bl_2 <- data.sys$ageusa_cat_bl_2 
qc.fit.noboot.sys$qx$ageusa_cat_bl_3 <- data.sys$ageusa_cat_bl_3 
qc.fit.noboot.sys$qx$meducat_bl_2 <- data.sys$meducat_bl_2 
qc.fit.noboot.sys$qx$meducat_bl_3 <- data.sys$meducat_bl_3 
qc.fit.noboot.sys$qx$imarcat_10_5y <- data.sys$imarcat_10_5y 
qc.fit.noboot.sys$qx$iagwork_10_5y_2 <- data.sys$iagwork_10_5y_2 
qc.fit.noboot.sys$qx$iagwork_10_5y_3 <- data.sys$iagwork_10_5y_3 
qc.fit.noboot.sys$qx$i2_povcat2_10_5y <- data.sys$i2_povcat2_10_5y 
qc.fit.noboot.sys$qx$ipaw <- data.sys$ipaw

# adjusted coefficients from underlying model
newfit.noboot.sys <- glm(Y.cc.sys ~ 
                      age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                      meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                      iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                      op_q + #exposures
                      pyr_q + carb_q + neo_q + mn_q + gly_q + paraq_q, 
                   data = qc.fit.noboot.sys$qx
                   )

newfit.noboot.sys ##this is where the individual coefficients are
tidy(newfit.noboot.sys, conf.int = T) # and confidence intervals

sum(newfit.noboot.sys$coefficients[-c(1:10)]) # sums to psi_1 

coef(qc.fit.noboot.sys)

plot(qc.fit.noboot.sys) #Need to fix width of bars

  #Making my own plot
  coefficients <- qc.fit.noboot.sys$fit$coefficients[qc.fit.noboot.sys$expnms]
  pos_sum <- sum(coefficients[coefficients > 0])
  neg_sum <- sum(coefficients[coefficients < 0])

  weights <- rep(NA, length(coefficients))
  weights[coefficients > 0] <- coefficients[coefficients > 0] / pos_sum
  weights[coefficients < 0] <- -(coefficients[coefficients < 0] / neg_sum)

  plot_data <- data.frame(
    exposure = qc.fit.noboot.sys$expnms,
    weights = weights
  )

  plot_data$exposure <- factor(plot_data$exposure, levels = qc.fit.noboot.sys$expnms)
  
  p <- ggplot(plot_data, aes(x = weights, y = exposure)) +
    geom_bar(stat = "identity", width = 0.8, aes(fill = weights > 0)) +
    geom_vline(xintercept = 0, linetype = "dotted") +
    scale_fill_manual(values = c("TRUE" = "#818181", "FALSE" = "#ABABAB"), guide = "none") +
    labs(
      x = "Weight of Exposure",
      y = "Exposures"
    ) +
    theme_classic()+
    scale_x_continuous(
      limits = c(-1.0, 1.0),
      breaks = c(-0.75, -0.50, -0.25, 0, 0.25, 0.50, 0.75)
    )
  
  print(p)
```

```{r, joint exposure models, continuous outcomes, qgcomp.glm.noboot, diastolic BP}
qc.fit.noboot.dia <- qgcomp.glm.noboot(Y.cc.dia ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.dia, #dataset
                                family=gaussian(), 
                                q=4
                                )

qc.fit.noboot.dia

# underlying model of qgcomp fit
qc.fit.noboot.dia$qx$Y.cc.dia <- data.dia$Y.cc.dia # bring outcome back into quantized data

#add the covariates and weights too
qc.fit.noboot.dia$qx$age_dl <- data.dia$age_dl 
qc.fit.noboot.dia$qx$ageusa_cat_bl_2 <- data.dia$ageusa_cat_bl_2 
qc.fit.noboot.dia$qx$ageusa_cat_bl_3 <- data.dia$ageusa_cat_bl_3 
qc.fit.noboot.dia$qx$meducat_bl_2 <- data.dia$meducat_bl_2 
qc.fit.noboot.dia$qx$meducat_bl_3 <- data.dia$meducat_bl_3 
qc.fit.noboot.dia$qx$imarcat_10_5y <- data.dia$imarcat_10_5y 
qc.fit.noboot.dia$qx$iagwork_10_5y_2 <- data.dia$iagwork_10_5y_2 
qc.fit.noboot.dia$qx$iagwork_10_5y_3 <- data.dia$iagwork_10_5y_3 
qc.fit.noboot.dia$qx$i2_povcat2_10_5y <- data.dia$i2_povcat2_10_5y 
qc.fit.noboot.dia$qx$ipaw <- data.dia$ipaw

# adjusted coefficients from underlying model
newfit.noboot.dia <- glm(Y.cc.dia ~ 
                      age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                      meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                      iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                      op_q + #exposures
                      pyr_q + carb_q + neo_q + mn_q + gly_q + paraq_q, 
                   data = qc.fit.noboot.dia$qx
                   )

newfit.noboot.dia ##this is where the individual coefficients are
tidy(newfit.noboot.dia, conf.int = T) # and confidence intervals

sum(newfit.noboot.dia$coefficients[-c(1:10)]) # sums to psi_1 

coef(qc.fit.noboot.dia)

plot(qc.fit.noboot.dia)

#Making my own plot
  coefficients <- qc.fit.noboot.dia$fit$coefficients[qc.fit.noboot.dia$expnms]
  pos_sum <- sum(coefficients[coefficients > 0])
  neg_sum <- sum(coefficients[coefficients < 0])

  weights <- rep(NA, length(coefficients))
  weights[coefficients > 0] <- coefficients[coefficients > 0] / pos_sum
  weights[coefficients < 0] <- -(coefficients[coefficients < 0] / neg_sum)

  plot_data <- data.frame(
    exposure = qc.fit.noboot.dia$expnms,
    weights = weights
  )

  plot_data$exposure <- factor(plot_data$exposure, levels = qc.fit.noboot.dia$expnms)
  
  p <- ggplot(plot_data, aes(x = weights, y = exposure)) +
    geom_bar(stat = "identity", width = 0.8, aes(fill = weights > 0)) +
    geom_vline(xintercept = 0, linetype = "dotted") +
    scale_fill_manual(values = c("TRUE" = "#818181", "FALSE" = "#818181"), guide = "none") +
    labs(
      x = "Weight of Exposure",
      y = "Exposures"
    ) +
    theme_classic()+
    scale_x_continuous(
      limits = c(-1.0, 1.0),
      breaks = c(-0.75, -0.50, -0.25, 0, 0.25, 0.50, 0.75)
    )
  
  print(p)
```

```{r, joint exposure models, continuous outcomes, qgcomp.glm.noboot, pulse pressure}
qc.fit.noboot.pul <- qgcomp.glm.noboot(Y.cc.pul ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.pul, #dataset
                                family=gaussian(), 
                                q=4
                                )

qc.fit.noboot.pul

# underlying model of qgcomp fit
qc.fit.noboot.pul$qx$Y.cc.pul <- data.pul$Y.cc.pul # bring outcome back into quantized data

#add the covariates and weights too
qc.fit.noboot.pul$qx$age_dl <- data.pul$age_dl 
qc.fit.noboot.pul$qx$ageusa_cat_bl_2 <- data.pul$ageusa_cat_bl_2 
qc.fit.noboot.pul$qx$ageusa_cat_bl_3 <- data.pul$ageusa_cat_bl_3 
qc.fit.noboot.pul$qx$meducat_bl_2 <- data.pul$meducat_bl_2 
qc.fit.noboot.pul$qx$meducat_bl_3 <- data.pul$meducat_bl_3 
qc.fit.noboot.pul$qx$imarcat_10_5y <- data.pul$imarcat_10_5y 
qc.fit.noboot.pul$qx$iagwork_10_5y_2 <- data.pul$iagwork_10_5y_2 
qc.fit.noboot.pul$qx$iagwork_10_5y_3 <- data.pul$iagwork_10_5y_3 
qc.fit.noboot.pul$qx$i2_povcat2_10_5y <- data.pul$i2_povcat2_10_5y 
qc.fit.noboot.pul$qx$ipaw <- data.pul$ipaw

# adjusted coefficients from underlying model
newfit.noboot.pul <- glm(Y.cc.pul ~ 
                      age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                      meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                      iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                      op_q + #exposures
                      pyr_q + carb_q + neo_q + mn_q + gly_q + paraq_q, 
                   data = qc.fit.noboot.pul$qx
                   )

newfit.noboot.pul ##this is where the individual coefficients are
tidy(newfit.noboot.pul, conf.int = T) # and confidence intervals

sum(newfit.noboot.pul$coefficients[-c(1:10)]) # sums to psi_1 

coef(qc.fit.noboot.pul)

plot(qc.fit.noboot.pul)

  #Making my own plot
  coefficients <- qc.fit.noboot.pul$fit$coefficients[qc.fit.noboot.pul$expnms]
  pos_sum <- sum(coefficients[coefficients > 0])
  neg_sum <- sum(coefficients[coefficients < 0])

  weights <- rep(NA, length(coefficients))
  weights[coefficients > 0] <- coefficients[coefficients > 0] / pos_sum
  weights[coefficients < 0] <- -(coefficients[coefficients < 0] / neg_sum)

  plot_data <- data.frame(
    exposure = qc.fit.noboot.pul$expnms,
    weights = weights
  )

  plot_data$exposure <- factor(plot_data$exposure, levels = qc.fit.noboot.pul$expnms)
  
  p <- ggplot(plot_data, aes(x = weights, y = exposure)) +
    geom_bar(stat = "identity", width = 0.8, aes(fill = weights > 0)) +
    geom_vline(xintercept = 0, linetype = "dotted") +
    scale_fill_manual(values = c("TRUE" = "#818181", "FALSE" = "#ABABAB"), guide = "none") +
    labs(
      x = "Weight of Exposure",
      y = "Exposures"
    ) +
    theme_classic()+
    scale_x_continuous(
      limits = c(-1.0, 1.0),
      breaks = c(-0.75, -0.50, -0.25, 0, 0.25, 0.50, 0.75)
    )
  
  print(p)
```

```{r, joint exposure models, continuous outcomes, qgcomp.glm.noboot, MAP}
qc.fit.noboot.map <- qgcomp.glm.noboot(Y.cc.map ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.map, #dataset
                                family=gaussian(), 
                                q=4
                                )

qc.fit.noboot.map

# underlying model of qgcomp fit
qc.fit.noboot.map$qx$Y.cc.map <- data.map$Y.cc.map # bring outcome back into quantized data

#add the covariates and weights too
qc.fit.noboot.map$qx$age_dl <- data.map$age_dl 
qc.fit.noboot.map$qx$ageusa_cat_bl_2 <- data.map$ageusa_cat_bl_2 
qc.fit.noboot.map$qx$ageusa_cat_bl_3 <- data.map$ageusa_cat_bl_3 
qc.fit.noboot.map$qx$meducat_bl_2 <- data.map$meducat_bl_2 
qc.fit.noboot.map$qx$meducat_bl_3 <- data.map$meducat_bl_3 
qc.fit.noboot.map$qx$imarcat_10_5y <- data.map$imarcat_10_5y 
qc.fit.noboot.map$qx$iagwork_10_5y_2 <- data.map$iagwork_10_5y_2 
qc.fit.noboot.map$qx$iagwork_10_5y_3 <- data.map$iagwork_10_5y_3 
qc.fit.noboot.map$qx$i2_povcat2_10_5y <- data.map$i2_povcat2_10_5y 
qc.fit.noboot.map$qx$ipaw <- data.map$ipaw

# adjusted coefficients from underlying model
newfit.noboot.map <- glm(Y.cc.map ~ 
                      age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                      meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                      iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                      op_q + #exposures
                      pyr_q + carb_q + neo_q + mn_q + gly_q + paraq_q, 
                   data = qc.fit.noboot.map$qx
                   )

newfit.noboot.map ##this is where the individual coefficients are
tidy(newfit.noboot.map, conf.int = T) # and confidence intervals

sum(newfit.noboot.map$coefficients[-c(1:10)]) # sums to psi_1 

coef(qc.fit.noboot.map)

plot(qc.fit.noboot.map)

  #Making my own plot
  coefficients <- qc.fit.noboot.map$fit$coefficients[qc.fit.noboot.map$expnms]
  pos_sum <- sum(coefficients[coefficients > 0])
  neg_sum <- sum(coefficients[coefficients < 0])

  weights <- rep(NA, length(coefficients))
  weights[coefficients > 0] <- coefficients[coefficients > 0] / pos_sum
  weights[coefficients < 0] <- -(coefficients[coefficients < 0] / neg_sum)

  plot_data <- data.frame(
    exposure = qc.fit.noboot.map$expnms,
    weights = weights
  )

  plot_data$exposure <- factor(plot_data$exposure, levels = qc.fit.noboot.map$expnms)
  
  p <- ggplot(plot_data, aes(x = weights, y = exposure)) +
    geom_bar(stat = "identity", width = 0.8, aes(fill = weights > 0)) +
    geom_vline(xintercept = 0, linetype = "dotted") +
    scale_fill_manual(values = c("TRUE" = "#818181", "FALSE" = "#ABABAB"), guide = "none") +
    labs(
      x = "Weight of Exposure",
      y = "Exposures"
    ) +
    theme_classic()+
    scale_x_continuous(
      limits = c(-1.0, 1.0),
      breaks = c(-0.75, -0.50, -0.25, 0, 0.25, 0.50, 0.75)
    )
  
  print(p)
```

```{r, joint exposure models, continuous outcomes, qgcomp.glm.noboot, triglycerides}
qc.fit.noboot.tri <- qgcomp.glm.noboot(Y.cc.tri ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.tri, #dataset
                                family=gaussian(), 
                                q=4
                                )

qc.fit.noboot.tri

# underlying model of qgcomp fit
qc.fit.noboot.tri$qx$Y.cc.tri <- data.tri$Y.cc.tri # bring outcome back into quantized data

#add the covariates and weights too
qc.fit.noboot.tri$qx$age_dl <- data.tri$age_dl 
qc.fit.noboot.tri$qx$ageusa_cat_bl_2 <- data.tri$ageusa_cat_bl_2 
qc.fit.noboot.tri$qx$ageusa_cat_bl_3 <- data.tri$ageusa_cat_bl_3 
qc.fit.noboot.tri$qx$meducat_bl_2 <- data.tri$meducat_bl_2 
qc.fit.noboot.tri$qx$meducat_bl_3 <- data.tri$meducat_bl_3 
qc.fit.noboot.tri$qx$imarcat_10_5y <- data.tri$imarcat_10_5y 
qc.fit.noboot.tri$qx$iagwork_10_5y_2 <- data.tri$iagwork_10_5y_2 
qc.fit.noboot.tri$qx$iagwork_10_5y_3 <- data.tri$iagwork_10_5y_3 
qc.fit.noboot.tri$qx$i2_povcat2_10_5y <- data.tri$i2_povcat2_10_5y 
qc.fit.noboot.tri$qx$ipaw <- data.tri$ipaw

# adjusted coefficients from underlying model
newfit.noboot.tri <- glm(Y.cc.tri ~ 
                      age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                      meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                      iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                      op_q + #exposures
                      pyr_q + carb_q + neo_q + mn_q + gly_q + paraq_q, 
                   data = qc.fit.noboot.tri$qx
                   )

newfit.noboot.tri ##this is where the individual coefficients are
tidy(newfit.noboot.tri, conf.int = T) # and confidence intervals

sum(newfit.noboot.tri$coefficients[-c(1:10)]) # sums to psi_1 

coef(qc.fit.noboot.tri)

plot(qc.fit.noboot.tri)

  #Making my own plot
  coefficients <- qc.fit.noboot.tri$fit$coefficients[qc.fit.noboot.tri$expnms]
  pos_sum <- sum(coefficients[coefficients > 0])
  neg_sum <- sum(coefficients[coefficients < 0])

  weights <- rep(NA, length(coefficients))
  weights[coefficients > 0] <- coefficients[coefficients > 0] / pos_sum
  weights[coefficients < 0] <- -(coefficients[coefficients < 0] / neg_sum)

  plot_data <- data.frame(
    exposure = qc.fit.noboot.tri$expnms,
    weights = weights
  )

  plot_data$exposure <- factor(plot_data$exposure, levels = qc.fit.noboot.tri$expnms)
  
  p <- ggplot(plot_data, aes(x = weights, y = exposure)) +
    geom_bar(stat = "identity", width = 0.8, aes(fill = weights > 0)) +
    geom_vline(xintercept = 0, linetype = "dotted") +
    scale_fill_manual(values = c("TRUE" = "#ABABAB", "FALSE" = "#818181"), guide = "none") +
    labs(
      x = "Weight of Exposure",
      y = "Exposures"
    ) +
    theme_classic()+
    scale_x_continuous(
      limits = c(-1.0, 1.0),
      breaks = c(-0.75, -0.50, -0.25, 0, 0.25, 0.50, 0.75)
    )
  
  print(p)
```

```{r, joint exposure models, continuous outcomes, qgcomp.glm.noboot, HDL}
qc.fit.noboot.hdl <- qgcomp.glm.noboot(Y.cc.hdl ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.hdl, #dataset
                                family=gaussian(), 
                                q=4
                                )

qc.fit.noboot.hdl

# underlying model of qgcomp fit
qc.fit.noboot.hdl$qx$Y.cc.hdl <- data.hdl$Y.cc.hdl # bring outcome back into quantized data

#add the covariates and weights too
qc.fit.noboot.hdl$qx$age_dl <- data.hdl$age_dl 
qc.fit.noboot.hdl$qx$ageusa_cat_bl_2 <- data.hdl$ageusa_cat_bl_2 
qc.fit.noboot.hdl$qx$ageusa_cat_bl_3 <- data.hdl$ageusa_cat_bl_3 
qc.fit.noboot.hdl$qx$meducat_bl_2 <- data.hdl$meducat_bl_2 
qc.fit.noboot.hdl$qx$meducat_bl_3 <- data.hdl$meducat_bl_3 
qc.fit.noboot.hdl$qx$imarcat_10_5y <- data.hdl$imarcat_10_5y 
qc.fit.noboot.hdl$qx$iagwork_10_5y_2 <- data.hdl$iagwork_10_5y_2 
qc.fit.noboot.hdl$qx$iagwork_10_5y_3 <- data.hdl$iagwork_10_5y_3 
qc.fit.noboot.hdl$qx$i2_povcat2_10_5y <- data.hdl$i2_povcat2_10_5y 
qc.fit.noboot.hdl$qx$ipaw <- data.hdl$ipaw

# adjusted coefficients from underlying model
newfit.noboot.hdl <- glm(Y.cc.hdl ~ 
                      age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                      meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                      iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                      op_q + #exposures
                      pyr_q + carb_q + neo_q + mn_q + gly_q + paraq_q, 
                   data = qc.fit.noboot.hdl$qx
                   )

newfit.noboot.hdl ##this is where the individual coefficients are
tidy(newfit.noboot.hdl, conf.int = T) # and confidence intervals

sum(newfit.noboot.hdl$coefficients[-c(1:10)]) # sums to psi_1 

coef(qc.fit.noboot.hdl)

plot(qc.fit.noboot.hdl)

  #Making my own plot
  coefficients <- qc.fit.noboot.hdl$fit$coefficients[qc.fit.noboot.hdl$expnms]
  pos_sum <- sum(coefficients[coefficients > 0])
  neg_sum <- sum(coefficients[coefficients < 0])

  weights <- rep(NA, length(coefficients))
  weights[coefficients > 0] <- coefficients[coefficients > 0] / pos_sum
  weights[coefficients < 0] <- -(coefficients[coefficients < 0] / neg_sum)

  plot_data <- data.frame(
    exposure = qc.fit.noboot.hdl$expnms,
    weights = weights
  )

  plot_data$exposure <- factor(plot_data$exposure, levels = qc.fit.noboot.hdl$expnms)
  
  p <- ggplot(plot_data, aes(x = weights, y = exposure)) +
    geom_bar(stat = "identity", width = 0.8, aes(fill = weights > 0)) +
    geom_vline(xintercept = 0, linetype = "dotted") +
    scale_fill_manual(values = c("TRUE" = "#ABABAB", "FALSE" = "#818181"), guide = "none") +
    labs(
      x = "Weight of Exposure",
      y = "Exposures"
    ) +
    theme_classic()+
    scale_x_continuous(
      limits = c(-1.0, 1.0),
      breaks = c(-0.75, -0.50, -0.25, 0, 0.25, 0.50, 0.75)
    )
  
  print(p)
```

```{r, joint exposure models, continuous outcomes, qgcomp.glm.noboot, glucose}
qc.fit.noboot.glu <- qgcomp.glm.noboot(Y.cc.glu ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.glu, #dataset
                                family=gaussian(), 
                                q=4
                                )

qc.fit.noboot.glu

# underlying model of qgcomp fit
qc.fit.noboot.glu$qx$Y.cc.glu <- data.glu$Y.cc.glu # bring outcome back into quantized data

#add the covariates and weights too
qc.fit.noboot.glu$qx$age_dl <- data.glu$age_dl 
qc.fit.noboot.glu$qx$ageusa_cat_bl_2 <- data.glu$ageusa_cat_bl_2 
qc.fit.noboot.glu$qx$ageusa_cat_bl_3 <- data.glu$ageusa_cat_bl_3 
qc.fit.noboot.glu$qx$meducat_bl_2 <- data.glu$meducat_bl_2 
qc.fit.noboot.glu$qx$meducat_bl_3 <- data.glu$meducat_bl_3 
qc.fit.noboot.glu$qx$imarcat_10_5y <- data.glu$imarcat_10_5y 
qc.fit.noboot.glu$qx$iagwork_10_5y_2 <- data.glu$iagwork_10_5y_2 
qc.fit.noboot.glu$qx$iagwork_10_5y_3 <- data.glu$iagwork_10_5y_3 
qc.fit.noboot.glu$qx$i2_povcat2_10_5y <- data.glu$i2_povcat2_10_5y 
qc.fit.noboot.glu$qx$ipaw <- data.glu$ipaw

# adjusted coefficients from underlying model
newfit.noboot.glu <- glm(Y.cc.glu ~ 
                      age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                      meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                      iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                      op_q + #exposures
                      pyr_q + carb_q + neo_q + mn_q + gly_q + paraq_q, 
                   data = qc.fit.noboot.glu$qx
                   )

newfit.noboot.glu ##this is where the individual coefficients are
tidy(newfit.noboot.glu, conf.int = T) # and confidence intervals

sum(newfit.noboot.glu$coefficients[-c(1:10)]) # sums to psi_1 

coef(qc.fit.noboot.glu)

plot(qc.fit.noboot.glu)

  #Making my own plot
  coefficients <- qc.fit.noboot.glu$fit$coefficients[qc.fit.noboot.glu$expnms]
  pos_sum <- sum(coefficients[coefficients > 0])
  neg_sum <- sum(coefficients[coefficients < 0])

  weights <- rep(NA, length(coefficients))
  weights[coefficients > 0] <- coefficients[coefficients > 0] / pos_sum
  weights[coefficients < 0] <- -(coefficients[coefficients < 0] / neg_sum)

  plot_data <- data.frame(
    exposure = qc.fit.noboot.glu$expnms,
    weights = weights
  )

  plot_data$exposure <- factor(plot_data$exposure, levels = qc.fit.noboot.glu$expnms)
  
  p <- ggplot(plot_data, aes(x = weights, y = exposure)) +
    geom_bar(stat = "identity", width = 0.8, aes(fill = weights > 0)) +
    geom_vline(xintercept = 0, linetype = "dotted") +
    scale_fill_manual(values = c("TRUE" = "#818181", "FALSE" = "#818181"), guide = "none") +
    labs(
      x = "Weight of Exposure",
      y = "Exposures"
    ) +
    theme_classic()+
    scale_x_continuous(
      limits = c(-1.0, 1.0),
      breaks = c(-0.75, -0.50, -0.25, 0, 0.25, 0.50, 0.75)
    )
  
  print(p)
```

```{r, joint exposure models, continuous outcomes, qgcomp.glm.noboot, HbA1c}
qc.fit.noboot.hba <- qgcomp.glm.noboot(Y.cc.hba ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.hba, #dataset
                                family=gaussian(), 
                                q=4
                                )

qc.fit.noboot.hba

# underlying model of qgcomp fit
qc.fit.noboot.hba$qx$Y.cc.hba <- data.hba$Y.cc.hba # bring outcome back into quantized data

#add the covariates and weights too
qc.fit.noboot.hba$qx$age_dl <- data.hba$age_dl 
qc.fit.noboot.hba$qx$ageusa_cat_bl_2 <- data.hba$ageusa_cat_bl_2 
qc.fit.noboot.hba$qx$ageusa_cat_bl_3 <- data.hba$ageusa_cat_bl_3 
qc.fit.noboot.hba$qx$meducat_bl_2 <- data.hba$meducat_bl_2 
qc.fit.noboot.hba$qx$meducat_bl_3 <- data.hba$meducat_bl_3 
qc.fit.noboot.hba$qx$imarcat_10_5y <- data.hba$imarcat_10_5y 
qc.fit.noboot.hba$qx$iagwork_10_5y_2 <- data.hba$iagwork_10_5y_2 
qc.fit.noboot.hba$qx$iagwork_10_5y_3 <- data.hba$iagwork_10_5y_3 
qc.fit.noboot.hba$qx$i2_povcat2_10_5y <- data.hba$i2_povcat2_10_5y 
qc.fit.noboot.hba$qx$ipaw <- data.hba$ipaw

# adjusted coefficients from underlying model
newfit.noboot.hba <- glm(Y.cc.hba ~ 
                      age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                      meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                      iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                      op_q + #exposures
                      pyr_q + carb_q + neo_q + mn_q + gly_q + paraq_q, 
                   data = qc.fit.noboot.hba$qx
                   )

newfit.noboot.hba ##this is where the individual coefficients are
tidy(newfit.noboot.hba, conf.int = T) # and confidence intervals

sum(newfit.noboot.hba$coefficients[-c(1:10)]) # sums to psi_1 

coef(qc.fit.noboot.hba)

plot(qc.fit.noboot.hba)

  #Making my own plot
  coefficients <- qc.fit.noboot.hba$fit$coefficients[qc.fit.noboot.hba$expnms]
  pos_sum <- sum(coefficients[coefficients > 0])
  neg_sum <- sum(coefficients[coefficients < 0])

  weights <- rep(NA, length(coefficients))
  weights[coefficients > 0] <- coefficients[coefficients > 0] / pos_sum
  weights[coefficients < 0] <- -(coefficients[coefficients < 0] / neg_sum)

  plot_data <- data.frame(
    exposure = qc.fit.noboot.hba$expnms,
    weights = weights
  )

  plot_data$exposure <- factor(plot_data$exposure, levels = qc.fit.noboot.hba$expnms)
  
  p <- ggplot(plot_data, aes(x = weights, y = exposure)) +
    geom_bar(stat = "identity", width = 0.8, aes(fill = weights > 0)) +
    geom_vline(xintercept = 0, linetype = "dotted") +
    scale_fill_manual(values = c("TRUE" = "#ABABAB", "FALSE" = "#818181"), guide = "none") +
    labs(
      x = "Weight of Exposure",
      y = "Exposures"
    ) +
    theme_classic()+
    scale_x_continuous(
      limits = c(-1.0, 1.0),
      breaks = c(-0.75, -0.50, -0.25, 0, 0.25, 0.50, 0.75)
    )
  
  print(p)
```

```{r, joint exposure models, continuous outcomes, qgcomp.glm.noboot, BMI}
qc.fit.noboot.bmi <- qgcomp.glm.noboot(Y.cc.bmi ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.bmi, #dataset
                                family=gaussian(), 
                                q=4
                                )

qc.fit.noboot.bmi

# underlying model of qgcomp fit
qc.fit.noboot.bmi$qx$Y.cc.bmi <- data.bmi$Y.cc.bmi # bring outcome back into quantized data

#add the covariates and weights too
qc.fit.noboot.bmi$qx$age_dl <- data.bmi$age_dl 
qc.fit.noboot.bmi$qx$ageusa_cat_bl_2 <- data.bmi$ageusa_cat_bl_2 
qc.fit.noboot.bmi$qx$ageusa_cat_bl_3 <- data.bmi$ageusa_cat_bl_3 
qc.fit.noboot.bmi$qx$meducat_bl_2 <- data.bmi$meducat_bl_2 
qc.fit.noboot.bmi$qx$meducat_bl_3 <- data.bmi$meducat_bl_3 
qc.fit.noboot.bmi$qx$imarcat_10_5y <- data.bmi$imarcat_10_5y 
qc.fit.noboot.bmi$qx$iagwork_10_5y_2 <- data.bmi$iagwork_10_5y_2 
qc.fit.noboot.bmi$qx$iagwork_10_5y_3 <- data.bmi$iagwork_10_5y_3 
qc.fit.noboot.bmi$qx$i2_povcat2_10_5y <- data.bmi$i2_povcat2_10_5y 
qc.fit.noboot.bmi$qx$ipaw <- data.bmi$ipaw

# adjusted coefficients from underlying model
newfit.noboot.bmi <- glm(Y.cc.bmi ~ 
                      age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                      meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                      iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                      op_q + #exposures
                      pyr_q + carb_q + neo_q + mn_q + gly_q + paraq_q, 
                   data = qc.fit.noboot.bmi$qx
                   )

newfit.noboot.bmi ##this is where the individual coefficients are
tidy(newfit.noboot.bmi, conf.int = T) # and confidence intervals

sum(newfit.noboot.bmi$coefficients[-c(1:10)]) # sums to psi_1 

coef(qc.fit.noboot.bmi)

plot(qc.fit.noboot.bmi)

  #Making my own plot
  coefficients <- qc.fit.noboot.bmi$fit$coefficients[qc.fit.noboot.bmi$expnms]
  pos_sum <- sum(coefficients[coefficients > 0])
  neg_sum <- sum(coefficients[coefficients < 0])

  weights <- rep(NA, length(coefficients))
  weights[coefficients > 0] <- coefficients[coefficients > 0] / pos_sum
  weights[coefficients < 0] <- -(coefficients[coefficients < 0] / neg_sum)

  plot_data <- data.frame(
    exposure = qc.fit.noboot.bmi$expnms,
    weights = weights
  )

  plot_data$exposure <- factor(plot_data$exposure, levels = qc.fit.noboot.bmi$expnms)
  
  p <- ggplot(plot_data, aes(x = weights, y = exposure)) +
    geom_bar(stat = "identity", width = 0.8, aes(fill = weights > 0)) +
    geom_vline(xintercept = 0, linetype = "dotted") +
    scale_fill_manual(values = c("TRUE" = "#818181", "FALSE" = "#818181"), guide = "none") +
    labs(
      x = "Weight of Exposure",
      y = "Exposures"
    ) +
    theme_classic()+
    scale_x_continuous(
      limits = c(-1.0, 1.0),
      breaks = c(-0.75, -0.50, -0.25, 0, 0.25, 0.50, 0.75)
    )
  
  print(p)
```

```{r, joint exposure models, continuous outcomes, qgcomp.glm.noboot, waist circ}
qc.fit.noboot.wai <- qgcomp.glm.noboot(Y.cc.wai ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.wai, #dataset
                                family=gaussian(), 
                                q=4
                                )

qc.fit.noboot.wai

# underlying model of qgcomp fit
qc.fit.noboot.wai$qx$Y.cc.wai <- data.wai$Y.cc.wai # bring outcome back into quantized data

#add the covariates and weights too
qc.fit.noboot.wai$qx$age_dl <- data.wai$age_dl 
qc.fit.noboot.wai$qx$ageusa_cat_bl_2 <- data.wai$ageusa_cat_bl_2 
qc.fit.noboot.wai$qx$ageusa_cat_bl_3 <- data.wai$ageusa_cat_bl_3 
qc.fit.noboot.wai$qx$meducat_bl_2 <- data.wai$meducat_bl_2 
qc.fit.noboot.wai$qx$meducat_bl_3 <- data.wai$meducat_bl_3 
qc.fit.noboot.wai$qx$imarcat_10_5y <- data.wai$imarcat_10_5y 
qc.fit.noboot.wai$qx$iagwork_10_5y_2 <- data.wai$iagwork_10_5y_2 
qc.fit.noboot.wai$qx$iagwork_10_5y_3 <- data.wai$iagwork_10_5y_3 
qc.fit.noboot.wai$qx$i2_povcat2_10_5y <- data.wai$i2_povcat2_10_5y 
qc.fit.noboot.wai$qx$ipaw <- data.wai$ipaw

# adjusted coefficients from underlying model
newfit.noboot.wai <- glm(Y.cc.wai ~ 
                      age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                      meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                      iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                      op_q + #exposures
                      pyr_q + carb_q + neo_q + mn_q + gly_q + paraq_q, 
                   data = qc.fit.noboot.wai$qx
                   )

newfit.noboot.wai ##this is where the individual coefficients are
tidy(newfit.noboot.wai, conf.int = T) # and confidence intervals

sum(newfit.noboot.wai$coefficients[-c(1:10)]) # sums to psi_1 

coef(qc.fit.noboot.wai)

plot(qc.fit.noboot.wai)

  #Making my own plot
  coefficients <- qc.fit.noboot.wai$fit$coefficients[qc.fit.noboot.wai$expnms]
  pos_sum <- sum(coefficients[coefficients > 0])
  neg_sum <- sum(coefficients[coefficients < 0])

  weights <- rep(NA, length(coefficients))
  weights[coefficients > 0] <- coefficients[coefficients > 0] / pos_sum
  weights[coefficients < 0] <- -(coefficients[coefficients < 0] / neg_sum)

  plot_data <- data.frame(
    exposure = qc.fit.noboot.wai$expnms,
    weights = weights
  )

  plot_data$exposure <- factor(plot_data$exposure, levels = qc.fit.noboot.wai$expnms)
  
  p <- ggplot(plot_data, aes(x = weights, y = exposure)) +
    geom_bar(stat = "identity", width = 0.8, aes(fill = weights > 0)) +
    geom_vline(xintercept = 0, linetype = "dotted") +
    scale_fill_manual(values = c("TRUE" = "#ABABAB", "FALSE" = "#818181"), guide = "none") +
    labs(
      x = "Weight of Exposure",
      y = "Exposures"
    ) +
    theme_classic()+
    scale_x_continuous(
      limits = c(-1.0, 1.0),
      breaks = c(-0.75, -0.50, -0.25, 0, 0.25, 0.50, 0.75)
    )
  
  print(p)
```

```{r, joint exposure models, continuous outcomes, qgcomp.glm.noboot, CRP}
qc.fit.noboot.crp <- qgcomp.glm.noboot(Y.cc.crp ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.crp, #dataset
                                family=gaussian(), 
                                q=4
                                )

qc.fit.noboot.crp

# underlying model of qgcomp fit
qc.fit.noboot.crp$qx$Y.cc.crp <- data.crp$Y.cc.crp # bring outcome back into quantized data

#add the covariates and weights too
qc.fit.noboot.crp$qx$age_dl <- data.crp$age_dl 
qc.fit.noboot.crp$qx$ageusa_cat_bl_2 <- data.crp$ageusa_cat_bl_2 
qc.fit.noboot.crp$qx$ageusa_cat_bl_3 <- data.crp$ageusa_cat_bl_3 
qc.fit.noboot.crp$qx$meducat_bl_2 <- data.crp$meducat_bl_2 
qc.fit.noboot.crp$qx$meducat_bl_3 <- data.crp$meducat_bl_3 
qc.fit.noboot.crp$qx$imarcat_10_5y <- data.crp$imarcat_10_5y 
qc.fit.noboot.crp$qx$iagwork_10_5y_2 <- data.crp$iagwork_10_5y_2 
qc.fit.noboot.crp$qx$iagwork_10_5y_3 <- data.crp$iagwork_10_5y_3 
qc.fit.noboot.crp$qx$i2_povcat2_10_5y <- data.crp$i2_povcat2_10_5y 
qc.fit.noboot.crp$qx$ipaw <- data.crp$ipaw

# adjusted coefficients from underlying model
newfit.noboot.crp <- glm(Y.cc.crp ~ 
                      age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                      meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                      iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                      op_q + #exposures
                      pyr_q + carb_q + neo_q + mn_q + gly_q + paraq_q, 
                   data = qc.fit.noboot.crp$qx
                   )

newfit.noboot.crp ##this is where the individual coefficients are
tidy(newfit.noboot.crp, conf.int = T) # and confidence intervals

sum(newfit.noboot.crp$coefficients[-c(1:10)]) # sums to psi_1 

coef(qc.fit.noboot.crp)

plot(qc.fit.noboot.crp)

  #Making my own plot
  coefficients <- qc.fit.noboot.crp$fit$coefficients[qc.fit.noboot.crp$expnms]
  pos_sum <- sum(coefficients[coefficients > 0])
  neg_sum <- sum(coefficients[coefficients < 0])

  weights <- rep(NA, length(coefficients))
  weights[coefficients > 0] <- coefficients[coefficients > 0] / pos_sum
  weights[coefficients < 0] <- -(coefficients[coefficients < 0] / neg_sum)

  plot_data <- data.frame(
    exposure = qc.fit.noboot.crp$expnms,
    weights = weights
  )

  plot_data$exposure <- factor(plot_data$exposure, levels = qc.fit.noboot.crp$expnms)
  
  p <- ggplot(plot_data, aes(x = weights, y = exposure)) +
    geom_bar(stat = "identity", width = 0.8, aes(fill = weights > 0)) +
    geom_vline(xintercept = 0, linetype = "dotted") +
    scale_fill_manual(values = c("TRUE" = "#818181", "FALSE" = "#818181"), guide = "none") +
    labs(
      x = "Weight of Exposure",
      y = "Exposures"
    ) +
    theme_classic()+
    scale_x_continuous(
      limits = c(-1.0, 1.0),
      breaks = c(-0.75, -0.50, -0.25, 0, 0.25, 0.50, 0.75)
    )
  
  print(p)
```

```{r, joint exposure models, continuous outcomes, qgcomp.glm.noboot, IL6}
qc.fit.noboot.il6 <- qgcomp.glm.noboot(Y.cc.il6 ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.il6, #dataset
                                family=gaussian(), 
                                q=4
                                )

qc.fit.noboot.il6

# underlying model of qgcomp fit
qc.fit.noboot.il6$qx$Y.cc.il6 <- data.il6$Y.cc.il6 # bring outcome back into quantized data

#add the covariates and weights too
qc.fit.noboot.il6$qx$age_dl <- data.il6$age_dl 
qc.fit.noboot.il6$qx$ageusa_cat_bl_2 <- data.il6$ageusa_cat_bl_2 
qc.fit.noboot.il6$qx$ageusa_cat_bl_3 <- data.il6$ageusa_cat_bl_3 
qc.fit.noboot.il6$qx$meducat_bl_2 <- data.il6$meducat_bl_2 
qc.fit.noboot.il6$qx$meducat_bl_3 <- data.il6$meducat_bl_3 
qc.fit.noboot.il6$qx$imarcat_10_5y <- data.il6$imarcat_10_5y 
qc.fit.noboot.il6$qx$iagwork_10_5y_2 <- data.il6$iagwork_10_5y_2 
qc.fit.noboot.il6$qx$iagwork_10_5y_3 <- data.il6$iagwork_10_5y_3 
qc.fit.noboot.il6$qx$i2_povcat2_10_5y <- data.il6$i2_povcat2_10_5y 
qc.fit.noboot.il6$qx$ipaw <- data.il6$ipaw

# adjusted coefficients from underlying model
newfit.noboot.il6 <- glm(Y.cc.il6 ~ 
                      age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                      meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                      iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                      op_q + #exposures
                      pyr_q + carb_q + neo_q + mn_q + gly_q + paraq_q, 
                   data = qc.fit.noboot.il6$qx
                   )

newfit.noboot.il6 ##this is where the individual coefficients are
tidy(newfit.noboot.il6, conf.int = T) # and confidence intervals

sum(newfit.noboot.il6$coefficients[-c(1:10)]) # sums to psi_1 

coef(qc.fit.noboot.il6)

plot(qc.fit.noboot.il6)

  #Making my own plot
  coefficients <- qc.fit.noboot.il6$fit$coefficients[qc.fit.noboot.il6$expnms]
  pos_sum <- sum(coefficients[coefficients > 0])
  neg_sum <- sum(coefficients[coefficients < 0])

  weights <- rep(NA, length(coefficients))
  weights[coefficients > 0] <- coefficients[coefficients > 0] / pos_sum
  weights[coefficients < 0] <- -(coefficients[coefficients < 0] / neg_sum)

  plot_data <- data.frame(
    exposure = qc.fit.noboot.il6$expnms,
    weights = weights
  )

  plot_data$exposure <- factor(plot_data$exposure, levels = qc.fit.noboot.il6$expnms)
  
  p <- ggplot(plot_data, aes(x = weights, y = exposure)) +
    geom_bar(stat = "identity", width = 0.8, aes(fill = weights > 0)) +
    geom_vline(xintercept = 0, linetype = "dotted") +
    scale_fill_manual(values = c("TRUE" = "#818181", "FALSE" = "#818181"), guide = "none") +
    labs(
      x = "Weight of Exposure",
      y = "Exposures"
    ) +
    theme_classic()+
    scale_x_continuous(
      limits = c(-1.0, 1.0),
      breaks = c(-0.75, -0.50, -0.25, 0, 0.25, 0.50, 0.75)
    )
  
  print(p)
```

### Continuous outcomes - qgcomp.glm.ee (weights)
```{r, joint exposure models, continuous outcomes, qgcomp.glm.ee, systolic BP}
qc.fit.ee.sys <- qgcomp.glm.ee(Y.cc.sys ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.sys, #dataset
                                family=gaussian(), 
                                q=4,
                                weights=ipaw)

qc.fit.ee.sys

# underlying model of qgcomp fit
#qc.fit.ee.sys$qx$Y.cc.sys <- data.sys$Y.cc.sys # bring outcome back into quantized data

#add the covariates and weights too
#qc.fit.ee.sys$qx$age_dl <- data.sys$age_dl 
#qc.fit.ee.sys$qx$ageusa_cat_bl_2 <- data.sys$ageusa_cat_bl_2 
#qc.fit.ee.sys$qx$ageusa_cat_bl_3 <- data.sys$ageusa_cat_bl_3 
#qc.fit.ee.sys$qx$meducat_bl_2 <- data.sys$meducat_bl_2 
#qc.fit.ee.sys$qx$meducat_bl_3 <- data.sys$meducat_bl_3 
#qc.fit.ee.sys$qx$imarcat_10_5y <- data.sys$imarcat_10_5y 
#qc.fit.ee.sys$qx$iagwork_10_5y_2 <- data.sys$iagwork_10_5y_2 
#qc.fit.ee.sys$qx$iagwork_10_5y_3 <- data.sys$iagwork_10_5y_3 
#qc.fit.ee.sys$qx$i2_povcat2_10_5y <- data.sys$i2_povcat2_10_5y 
#qc.fit.ee.sys$qx$ipaw <- data.sys$ipaw

# adjusted coefficients from underlying model
#newfit.ee.sys <- glm(Y.cc.sys ~ 
#                      age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
#                      meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
#                      iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
#                      op_q + #exposures
#                      pyr_q + carb_q + neo_q + mn_q + gly_q + paraq_q, 
#                   data = qc.fit.ee.sys$qx,
#                   weights=ipaw)

#newfit.ee.sys ##this is where the individual coefficients are
#tidy(newfit.ee.sys, conf.int = T) # and confidence intervals

#sum(newfit.ee.sys$coefficients[-c(1:10)]) # sums to psi_1 

#coef(qc.fit.ee.sys)

plot(qc.fit.ee.sys)
```

```{r, joint exposure models, continuous outcomes, qgcomp.glm.ee, diastolic BP}
qc.fit.ee.dia <- qgcomp.glm.ee(Y.cc.dia ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.dia, #dataset
                                family=gaussian(), 
                                q=4,
                                weights=ipaw)

qc.fit.ee.dia

# underlying model of qgcomp fit
#qc.fit.ee.dia$qx$Y.cc.dia <- data.dia$Y.cc.dia # bring outcome back into quantized data

#add the covariates and weights too
#qc.fit.ee.dia$qx$age_dl <- data.dia$age_dl 
#qc.fit.ee.dia$qx$ageusa_cat_bl_2 <- data.dia$ageusa_cat_bl_2 
#qc.fit.ee.dia$qx$ageusa_cat_bl_3 <- data.dia$ageusa_cat_bl_3 
#qc.fit.ee.dia$qx$meducat_bl_2 <- data.dia$meducat_bl_2 
#qc.fit.ee.dia$qx$meducat_bl_3 <- data.dia$meducat_bl_3 
#qc.fit.ee.dia$qx$imarcat_10_5y <- data.dia$imarcat_10_5y 
#qc.fit.ee.dia$qx$iagwork_10_5y_2 <- data.dia$iagwork_10_5y_2 
#qc.fit.ee.dia$qx$iagwork_10_5y_3 <- data.dia$iagwork_10_5y_3 
#qc.fit.ee.dia$qx$i2_povcat2_10_5y <- data.dia$i2_povcat2_10_5y 
#qc.fit.ee.dia$qx$ipaw <- data.dia$ipaw

# adjusted coefficients from underlying model
#newfit.ee.dia <- glm(Y.cc.dia ~ 
#                      age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
#                      meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
#                      iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
#                      op_q + #exposures
#                      pyr_q + carb_q + neo_q + mn_q + gly_q + paraq_q, 
#                   data = qc.fit.ee.dia$qx,
#                   weights=ipaw)

#newfit.ee.dia ##this is where the individual coefficients are
#tidy(newfit.ee.dia, conf.int = T) # and confidence intervals

#sum(newfit.ee.dia$coefficients[-c(1:10)]) # sums to psi_1 

#coef(qc.fit.ee.dia)

plot(qc.fit.ee.dia)
```

```{r, joint exposure models, continuous outcomes, qgcomp.glm.ee, pulse pressure}
qc.fit.ee.pul <- qgcomp.glm.ee(Y.cc.pul ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.pul, #dataset
                                family=gaussian(), 
                                q=4,
                                weights=ipaw)

qc.fit.ee.pul

# underlying model of qgcomp fit
#qc.fit.ee.pul$qx$Y.cc.pul <- data.pul$Y.cc.pul # bring outcome back into quantized data

#add the covariates and weights too
#qc.fit.ee.pul$qx$age_dl <- data.pul$age_dl 
#qc.fit.ee.pul$qx$ageusa_cat_bl_2 <- data.pul$ageusa_cat_bl_2 
#qc.fit.ee.pul$qx$ageusa_cat_bl_3 <- data.pul$ageusa_cat_bl_3 
#qc.fit.ee.pul$qx$meducat_bl_2 <- data.pul$meducat_bl_2 
#qc.fit.ee.pul$qx$meducat_bl_3 <- data.pul$meducat_bl_3 
#qc.fit.ee.pul$qx$imarcat_10_5y <- data.pul$imarcat_10_5y 
#qc.fit.ee.pul$qx$iagwork_10_5y_2 <- data.pul$iagwork_10_5y_2 
#qc.fit.ee.pul$qx$iagwork_10_5y_3 <- data.pul$iagwork_10_5y_3 
#qc.fit.ee.pul$qx$i2_povcat2_10_5y <- data.pul$i2_povcat2_10_5y 
#qc.fit.ee.pul$qx$ipaw <- data.pul$ipaw

# adjusted coefficients from underlying model
#newfit.ee.pul <- glm(Y.cc.pul ~ 
#                      age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
#                      meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
#                      iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
#                      op_q + #exposures
#                      pyr_q + carb_q + neo_q + mn_q + gly_q + paraq_q, 
#                   data = qc.fit.ee.pul$qx,
#                   weights=ipaw)

#newfit.ee.pul ##this is where the individual coefficients are
#tidy(newfit.ee.pul, conf.int = T) # and confidence intervals

#sum(newfit.ee.pul$coefficients[-c(1:10)]) # sums to psi_1 

#coef(qc.fit.ee.pul)

plot(qc.fit.ee.pul)
```

```{r, joint exposure models, continuous outcomes, qgcomp.glm.ee, MAP}
qc.fit.ee.map <- qgcomp.glm.ee(Y.cc.map ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.map, #dataset
                                family=gaussian(), 
                                q=4,
                                weights=ipaw)

qc.fit.ee.map

# underlying model of qgcomp fit
#qc.fit.ee.map$qx$Y.cc.map <- data.map$Y.cc.map # bring outcome back into quantized data

#add the covariates and weights too
#qc.fit.ee.map$qx$age_dl <- data.map$age_dl 
#qc.fit.ee.map$qx$ageusa_cat_bl_2 <- data.map$ageusa_cat_bl_2 
#qc.fit.ee.map$qx$ageusa_cat_bl_3 <- data.map$ageusa_cat_bl_3 
#qc.fit.ee.map$qx$meducat_bl_2 <- data.map$meducat_bl_2 
#qc.fit.ee.map$qx$meducat_bl_3 <- data.map$meducat_bl_3 
#qc.fit.ee.map$qx$imarcat_10_5y <- data.map$imarcat_10_5y 
#qc.fit.ee.map$qx$iagwork_10_5y_2 <- data.map$iagwork_10_5y_2 
#qc.fit.ee.map$qx$iagwork_10_5y_3 <- data.map$iagwork_10_5y_3 
#qc.fit.ee.map$qx$i2_povcat2_10_5y <- data.map$i2_povcat2_10_5y 
#qc.fit.ee.map$qx$ipaw <- data.map$ipaw

# adjusted coefficients from underlying model
#newfit.ee.map <- glm(Y.cc.map ~ 
#                      age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
#                      meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
#                      iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
#                      op_q + #exposures
#                      pyr_q + carb_q + neo_q + mn_q + gly_q + paraq_q, 
#                   data = qc.fit.ee.map$qx,
#                   weights=ipaw)

#newfit.ee.map ##this is where the individual coefficients are
#tidy(newfit.ee.map, conf.int = T) # and confidence intervals

#sum(newfit.ee.map$coefficients[-c(1:10)]) # sums to psi_1 

#coef(qc.fit.ee.map)

plot(qc.fit.ee.map)
```

```{r, joint exposure models, continuous outcomes, qgcomp.glm.ee, triglycerides}
qc.fit.ee.tri <- qgcomp.glm.ee(Y.cc.tri ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.tri, #dataset
                                family=gaussian(), 
                                q=4,
                                weights=ipaw)

qc.fit.ee.tri

# underlying model of qgcomp fit
#qc.fit.ee.tri$qx$Y.cc.tri <- data.tri$Y.cc.tri # bring outcome back into quantized data

#add the covariates and weights too
#qc.fit.ee.tri$qx$age_dl <- data.tri$age_dl 
#qc.fit.ee.tri$qx$ageusa_cat_bl_2 <- data.tri$ageusa_cat_bl_2 
#qc.fit.ee.tri$qx$ageusa_cat_bl_3 <- data.tri$ageusa_cat_bl_3 
#qc.fit.ee.tri$qx$meducat_bl_2 <- data.tri$meducat_bl_2 
#qc.fit.ee.tri$qx$meducat_bl_3 <- data.tri$meducat_bl_3 
#qc.fit.ee.tri$qx$imarcat_10_5y <- data.tri$imarcat_10_5y 
#qc.fit.ee.tri$qx$iagwork_10_5y_2 <- data.tri$iagwork_10_5y_2 
#qc.fit.ee.tri$qx$iagwork_10_5y_3 <- data.tri$iagwork_10_5y_3 
#qc.fit.ee.tri$qx$i2_povcat2_10_5y <- data.tri$i2_povcat2_10_5y 
#qc.fit.ee.tri$qx$ipaw <- data.tri$ipaw

# adjusted coefficients from underlying model
#newfit.ee.tri <- glm(Y.cc.tri ~ 
#                      age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
#                      meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
#                      iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
#                      op_q + #exposures
#                      pyr_q + carb_q + neo_q + mn_q + gly_q + paraq_q, 
#                   data = qc.fit.ee.tri$qx,
#                   weights=ipaw)

#newfit.ee.tri ##this is where the individual coefficients are
#tidy(newfit.ee.tri, conf.int = T) # and confidence intervals

#sum(newfit.ee.tri$coefficients[-c(1:10)]) # sums to psi_1 

#coef(qc.fit.ee.tri)

plot(qc.fit.ee.tri)
```

```{r, joint exposure models, continuous outcomes, qgcomp.glm.ee, HDL}
qc.fit.ee.hdl <- qgcomp.glm.ee(Y.cc.hdl ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.hdl, #dataset
                                family=gaussian(), 
                                q=4,
                                weights=ipaw)

qc.fit.ee.hdl

# underlying model of qgcomp fit
#qc.fit.ee.hdl$qx$Y.cc.hdl <- data.hdl$Y.cc.hdl # bring outcome back into quantized data

#add the covariates and weights too
#qc.fit.ee.hdl$qx$age_dl <- data.hdl$age_dl 
#qc.fit.ee.hdl$qx$ageusa_cat_bl_2 <- data.hdl$ageusa_cat_bl_2 
#qc.fit.ee.hdl$qx$ageusa_cat_bl_3 <- data.hdl$ageusa_cat_bl_3 
#qc.fit.ee.hdl$qx$meducat_bl_2 <- data.hdl$meducat_bl_2 
#qc.fit.ee.hdl$qx$meducat_bl_3 <- data.hdl$meducat_bl_3 
#qc.fit.ee.hdl$qx$imarcat_10_5y <- data.hdl$imarcat_10_5y 
#qc.fit.ee.hdl$qx$iagwork_10_5y_2 <- data.hdl$iagwork_10_5y_2 
#qc.fit.ee.hdl$qx$iagwork_10_5y_3 <- data.hdl$iagwork_10_5y_3 
#qc.fit.ee.hdl$qx$i2_povcat2_10_5y <- data.hdl$i2_povcat2_10_5y 
#qc.fit.ee.hdl$qx$ipaw <- data.hdl$ipaw

# adjusted coefficients from underlying model
#newfit.ee.hdl <- glm(Y.cc.hdl ~ 
#                      age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
#                      meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
#                      iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
#                      op_q + #exposures
#                      pyr_q + carb_q + neo_q + mn_q + gly_q + paraq_q, 
#                   data = qc.fit.ee.hdl$qx,
#                   weights=ipaw)

#newfit.ee.hdl ##this is where the individual coefficients are
#tidy(newfit.ee.hdl, conf.int = T) # and confidence intervals

#sum(newfit.ee.hdl$coefficients[-c(1:10)]) # sums to psi_1 

#coef(qc.fit.ee.hdl)

plot(qc.fit.ee.hdl)
```

```{r, joint exposure models, continuous outcomes, qgcomp.glm.ee, glucose}
qc.fit.ee.glu <- qgcomp.glm.ee(Y.cc.glu ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.glu, #dataset
                                family=gaussian(), 
                                q=4,
                                weights=ipaw)

qc.fit.ee.glu

# underlying model of qgcomp fit
#qc.fit.ee.glu$qx$Y.cc.glu <- data.glu$Y.cc.glu # bring outcome back into quantized data

#add the covariates and weights too
#qc.fit.ee.glu$qx$age_dl <- data.glu$age_dl 
#qc.fit.ee.glu$qx$ageusa_cat_bl_2 <- data.glu$ageusa_cat_bl_2 
#qc.fit.ee.glu$qx$ageusa_cat_bl_3 <- data.glu$ageusa_cat_bl_3 
#qc.fit.ee.glu$qx$meducat_bl_2 <- data.glu$meducat_bl_2 
#qc.fit.ee.glu$qx$meducat_bl_3 <- data.glu$meducat_bl_3 
#qc.fit.ee.glu$qx$imarcat_10_5y <- data.glu$imarcat_10_5y 
#qc.fit.ee.glu$qx$iagwork_10_5y_2 <- data.glu$iagwork_10_5y_2 
#qc.fit.ee.glu$qx$iagwork_10_5y_3 <- data.glu$iagwork_10_5y_3 
#qc.fit.ee.glu$qx$i2_povcat2_10_5y <- data.glu$i2_povcat2_10_5y 
#qc.fit.ee.glu$qx$ipaw <- data.glu$ipaw

# adjusted coefficients from underlying model
#newfit.ee.glu <- glm(Y.cc.glu ~ 
#                      age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
#                      meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
#                      iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
#                      op_q + #exposures
#                      pyr_q + carb_q + neo_q + mn_q + gly_q + paraq_q, 
#                   data = qc.fit.ee.glu$qx,
#                   weights=ipaw)

#newfit.ee.glu ##this is where the individual coefficients are
#tidy(newfit.ee.glu, conf.int = T) # and confidence intervals

#sum(newfit.ee.glu$coefficients[-c(1:10)]) # sums to psi_1 

#coef(qc.fit.ee.glu)

plot(qc.fit.ee.glu)
```

```{r, joint exposure models, continuous outcomes, qgcomp.glm.ee, HbA1c}
qc.fit.ee.hba <- qgcomp.glm.ee(Y.cc.hba ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.hba, #dataset
                                family=gaussian(), 
                                q=4,
                                weights=ipaw)

qc.fit.ee.hba

# underlying model of qgcomp fit
#qc.fit.ee.hba$qx$Y.cc.hba <- data.hba$Y.cc.hba # bring outcome back into quantized data

#add the covariates and weights too
#qc.fit.ee.hba$qx$age_dl <- data.hba$age_dl 
#qc.fit.ee.hba$qx$ageusa_cat_bl_2 <- data.hba$ageusa_cat_bl_2 
#qc.fit.ee.hba$qx$ageusa_cat_bl_3 <- data.hba$ageusa_cat_bl_3 
#qc.fit.ee.hba$qx$meducat_bl_2 <- data.hba$meducat_bl_2 
#qc.fit.ee.hba$qx$meducat_bl_3 <- data.hba$meducat_bl_3 
#qc.fit.ee.hba$qx$imarcat_10_5y <- data.hba$imarcat_10_5y 
#qc.fit.ee.hba$qx$iagwork_10_5y_2 <- data.hba$iagwork_10_5y_2 
#qc.fit.ee.hba$qx$iagwork_10_5y_3 <- data.hba$iagwork_10_5y_3 
#qc.fit.ee.hba$qx$i2_povcat2_10_5y <- data.hba$i2_povcat2_10_5y 
#qc.fit.ee.hba$qx$ipaw <- data.hba$ipaw

# adjusted coefficients from underlying model
#newfit.ee.hba <- glm(Y.cc.hba ~ 
#                      age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
#                      meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
#                      iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
#                      op_q + #exposures
#                      pyr_q + carb_q + neo_q + mn_q + gly_q + paraq_q, 
#                   data = qc.fit.ee.hba$qx,
#                   weights=ipaw)

#newfit.ee.hba ##this is where the individual coefficients are
#tidy(newfit.ee.hba, conf.int = T) # and confidence intervals

#sum(newfit.ee.hba$coefficients[-c(1:10)]) # sums to psi_1 

#coef(qc.fit.ee.hba)

plot(qc.fit.ee.hba)
```

```{r, joint exposure models, continuous outcomes, qgcomp.glm.ee, BMI}
qc.fit.ee.bmi <- qgcomp.glm.ee(Y.cc.bmi ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.bmi, #dataset
                                family=gaussian(), 
                                q=4,
                                weights=ipaw)

qc.fit.ee.bmi

# underlying model of qgcomp fit
#qc.fit.ee.bmi$qx$Y.cc.bmi <- data.bmi$Y.cc.bmi # bring outcome back into quantized data

#add the covariates and weights too
#qc.fit.ee.bmi$qx$age_dl <- data.bmi$age_dl 
#qc.fit.ee.bmi$qx$ageusa_cat_bl_2 <- data.bmi$ageusa_cat_bl_2 
#qc.fit.ee.bmi$qx$ageusa_cat_bl_3 <- data.bmi$ageusa_cat_bl_3 
#qc.fit.ee.bmi$qx$meducat_bl_2 <- data.bmi$meducat_bl_2 
#qc.fit.ee.bmi$qx$meducat_bl_3 <- data.bmi$meducat_bl_3 
#qc.fit.ee.bmi$qx$imarcat_10_5y <- data.bmi$imarcat_10_5y 
#qc.fit.ee.bmi$qx$iagwork_10_5y_2 <- data.bmi$iagwork_10_5y_2 
#qc.fit.ee.bmi$qx$iagwork_10_5y_3 <- data.bmi$iagwork_10_5y_3 
#qc.fit.ee.bmi$qx$i2_povcat2_10_5y <- data.bmi$i2_povcat2_10_5y 
#qc.fit.ee.bmi$qx$ipaw <- data.bmi$ipaw

# adjusted coefficients from underlying model
#newfit.ee.bmi <- glm(Y.cc.bmi ~ 
#                      age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
#                      meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
#                      iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
#                      op_q + #exposures
#                      pyr_q + carb_q + neo_q + mn_q + gly_q + paraq_q, 
#                   data = qc.fit.ee.bmi$qx,
#                   weights=ipaw)

#newfit.ee.bmi ##this is where the individual coefficients are
#tidy(newfit.ee.bmi, conf.int = T) # and confidence intervals

#sum(newfit.ee.bmi$coefficients[-c(1:10)]) # sums to psi_1 

#coef(qc.fit.ee.bmi)

plot(qc.fit.ee.bmi)
```

```{r, joint exposure models, continuous outcomes, qgcomp.glm.ee, waist circ}
qc.fit.ee.wai <- qgcomp.glm.ee(Y.cc.wai ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.wai, #dataset
                                family=gaussian(), 
                                q=4,
                                weights=ipaw)

qc.fit.ee.wai

# underlying model of qgcomp fit
#qc.fit.ee.wai$qx$Y.cc.wai <- data.wai$Y.cc.wai # bring outcome back into quantized data

#add the covariates and weights too
#qc.fit.ee.wai$qx$age_dl <- data.wai$age_dl 
#qc.fit.ee.wai$qx$ageusa_cat_bl_2 <- data.wai$ageusa_cat_bl_2 
#qc.fit.ee.wai$qx$ageusa_cat_bl_3 <- data.wai$ageusa_cat_bl_3 
#qc.fit.ee.wai$qx$meducat_bl_2 <- data.wai$meducat_bl_2 
#qc.fit.ee.wai$qx$meducat_bl_3 <- data.wai$meducat_bl_3 
#qc.fit.ee.wai$qx$imarcat_10_5y <- data.wai$imarcat_10_5y 
#qc.fit.ee.wai$qx$iagwork_10_5y_2 <- data.wai$iagwork_10_5y_2 
#qc.fit.ee.wai$qx$iagwork_10_5y_3 <- data.wai$iagwork_10_5y_3 
#qc.fit.ee.wai$qx$i2_povcat2_10_5y <- data.wai$i2_povcat2_10_5y 
#qc.fit.ee.wai$qx$ipaw <- data.wai$ipaw

# adjusted coefficients from underlying model
#newfit.ee.wai <- glm(Y.cc.wai ~ 
#                      age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
#                      meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
#                      iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
#                      op_q + #exposures
#                      pyr_q + carb_q + neo_q + mn_q + gly_q + paraq_q, 
#                   data = qc.fit.ee.wai$qx,
#                   weights=ipaw)

#newfit.ee.wai ##this is where the individual coefficients are
#tidy(newfit.ee.wai, conf.int = T) # and confidence intervals

#sum(newfit.ee.wai$coefficients[-c(1:10)]) # sums to psi_1 

#coef(qc.fit.ee.wai)

plot(qc.fit.ee.wai)
```

```{r, joint exposure models, continuous outcomes, qgcomp.glm.ee, CRP}
qc.fit.ee.crp <- qgcomp.glm.ee(Y.cc.crp ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.crp, #dataset
                                family=gaussian(), 
                                q=4,
                                weights=ipaw)

qc.fit.ee.crp

# underlying model of qgcomp fit
#qc.fit.ee.crp$qx$Y.cc.crp <- data.crp$Y.cc.crp # bring outcome back into quantized data

#add the covariates and weights too
#qc.fit.ee.crp$qx$age_dl <- data.crp$age_dl 
#qc.fit.ee.crp$qx$ageusa_cat_bl_2 <- data.crp$ageusa_cat_bl_2 
#qc.fit.ee.crp$qx$ageusa_cat_bl_3 <- data.crp$ageusa_cat_bl_3 
#qc.fit.ee.crp$qx$meducat_bl_2 <- data.crp$meducat_bl_2 
#qc.fit.ee.crp$qx$meducat_bl_3 <- data.crp$meducat_bl_3 
#qc.fit.ee.crp$qx$imarcat_10_5y <- data.crp$imarcat_10_5y 
#qc.fit.ee.crp$qx$iagwork_10_5y_2 <- data.crp$iagwork_10_5y_2 
#qc.fit.ee.crp$qx$iagwork_10_5y_3 <- data.crp$iagwork_10_5y_3 
#qc.fit.ee.crp$qx$i2_povcat2_10_5y <- data.crp$i2_povcat2_10_5y 
#qc.fit.ee.crp$qx$ipaw <- data.crp$ipaw

# adjusted coefficients from underlying model
#newfit.ee.crp <- glm(Y.cc.crp ~ 
#                      age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
#                      meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
#                      iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
#                      op_q + #exposures
#                      pyr_q + carb_q + neo_q + mn_q + gly_q + paraq_q, 
#                   data = qc.fit.ee.crp$qx,
#                   weights=ipaw)

#newfit.ee.crp ##this is where the individual coefficients are
#tidy(newfit.ee.crp, conf.int = T) # and confidence intervals

#sum(newfit.ee.crp$coefficients[-c(1:10)]) # sums to psi_1 

#coef(qc.fit.ee.crp)

plot(qc.fit.ee.crp)
```

```{r, joint exposure models, continuous outcomes, qgcomp.glm.ee, IL6}
qc.fit.ee.il6 <- qgcomp.glm.ee(Y.cc.il6 ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.il6, #dataset
                                family=gaussian(), 
                                q=4,
                                weights=ipaw)

qc.fit.ee.il6

# underlying model of qgcomp fit
#qc.fit.ee.il6$qx$Y.cc.il6 <- data.il6$Y.cc.il6 # bring outcome back into quantized data

#add the covariates and weights too
#qc.fit.ee.il6$qx$age_dl <- data.il6$age_dl 
#qc.fit.ee.il6$qx$ageusa_cat_bl_2 <- data.il6$ageusa_cat_bl_2 
#qc.fit.ee.il6$qx$ageusa_cat_bl_3 <- data.il6$ageusa_cat_bl_3 
#qc.fit.ee.il6$qx$meducat_bl_2 <- data.il6$meducat_bl_2 
#qc.fit.ee.il6$qx$meducat_bl_3 <- data.il6$meducat_bl_3 
#qc.fit.ee.il6$qx$imarcat_10_5y <- data.il6$imarcat_10_5y 
#qc.fit.ee.il6$qx$iagwork_10_5y_2 <- data.il6$iagwork_10_5y_2 
#qc.fit.ee.il6$qx$iagwork_10_5y_3 <- data.il6$iagwork_10_5y_3 
#qc.fit.ee.il6$qx$i2_povcat2_10_5y <- data.il6$i2_povcat2_10_5y 
#qc.fit.ee.il6$qx$ipaw <- data.il6$ipaw

# adjusted coefficients from underlying model
#newfit.ee.il6 <- glm(Y.cc.il6 ~ 
#                      age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
#                      meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
#                      iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
#                      op_q + #exposures
#                      pyr_q + carb_q + neo_q + mn_q + gly_q + paraq_q, 
#                   data = qc.fit.ee.il6$qx,
#                   weights=ipaw)

#newfit.ee.il6 ##this is where the individual coefficients are
#tidy(newfit.ee.il6, conf.int = T) # and confidence intervals

#sum(newfit.ee.il6$coefficients[-c(1:10)]) # sums to psi_1 

#coef(qc.fit.ee.il6)

plot(qc.fit.ee.il6)
```


### Binary outcomes - qgcomp.glm.boot (no weights)
```{r, joint exposure models, binary outcomes, qgcomp.glm.boot, hypertension}
qc.fit.boot.hyper <- qgcomp.glm.boot(Y.cc.hyper ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.hyper, #dataset
                                family=binomial(), 
                                q=4, B=1000, seed=125)
                                

qc.fit.boot.hyper
plot(qc.fit.boot.hyper)
```

```{r, joint exposure models, binary outcomes, qgcomp.glm.boot, diabetes}
qc.fit.boot.diabe <- qgcomp.glm.boot(Y.cc.diabe ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.diabe, #dataset
                                family=binomial(), 
                                q=4, B=1000, seed=125)
                                

qc.fit.boot.diabe
plot(qc.fit.boot.diabe)
```

```{r, joint exposure models, binary outcomes, qgcomp.glm.boot, obese}
qc.fit.boot.obese <- qgcomp.glm.boot(Y.cc.obese ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.obese, #dataset
                                family=binomial(), 
                                q=4, B=1000, seed=125)
                                

qc.fit.boot.obese
plot(qc.fit.boot.obese)
```

```{r, joint exposure models, binary outcomes, qgcomp.glm.boot, BP ind}
qc.fit.boot.bpind <- qgcomp.glm.boot(Y.cc.bpind ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.bpind, #dataset
                                family=binomial(), 
                                q=4, B=1000, seed=125)
                                

qc.fit.boot.bpind
plot(qc.fit.boot.bpind)
```

```{r, joint exposure models, binary outcomes, qgcomp.glm.boot, triglyceride ind}
qc.fit.boot.trind <- qgcomp.glm.boot(Y.cc.trind ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.trind, #dataset
                                family=binomial(), 
                                q=4, B=1000, seed=125)
                                

qc.fit.boot.trind
plot(qc.fit.boot.trind)
```

```{r, joint exposure models, binary outcomes, qgcomp.glm.boot, HDL ind}
qc.fit.boot.chind <- qgcomp.glm.boot(Y.cc.chind ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.chind, #dataset
                                family=binomial(), 
                                q=4, B=1000, seed=125)
                                

qc.fit.boot.chind
plot(qc.fit.boot.chind)
```

```{r, joint exposure models, binary outcomes, qgcomp.glm.boot, glucose ind}
qc.fit.boot.glind <- qgcomp.glm.boot(Y.cc.glind ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.glind, #dataset
                                family=binomial(), 
                                q=4, B=1000, seed=125)
                                

qc.fit.boot.glind
plot(qc.fit.boot.glind)
```

```{r, joint exposure models, binary outcomes, qgcomp.glm.boot, waist ind}
qc.fit.boot.waind <- qgcomp.glm.boot(Y.cc.waind ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.waind, #dataset
                                family=binomial(), 
                                q=4, B=1000, seed=125)
                                

qc.fit.boot.waind
plot(qc.fit.boot.waind)
```

```{r, joint exposure models, binary outcomes, qgcomp.glm.boot, MetS}
qc.fit.boot.metab <- qgcomp.glm.boot(Y.cc.metab ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.metab, #dataset
                                family=binomial(), 
                                q=4, B=1000, seed=125)
                                

qc.fit.boot.metab
plot(qc.fit.boot.metab)
```

```{r, joint exposure models, binary outcomes, qgcomp.glm.boot, CRP cat}
qc.fit.boot.crpca <- qgcomp.glm.boot(Y.cc.crpca ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.crpca, #dataset
                                family=binomial(), 
                                q=4, B=1000, seed=125)
                                

qc.fit.boot.crpca
plot(qc.fit.boot.crpca)
```

### Binary outcomes - qgcomp.glm.noboot (no weights)
```{r, joint exposure models, binary outcomes, qgcomp.glm.noboot, hypertension}
qc.fit.noboot.hyper <- qgcomp.glm.noboot(Y.cc.hyper ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.hyper, #dataset
                                family=binomial(), 
                                q=4
                                )

qc.fit.noboot.hyper

# underlying model of qgcomp fit
qc.fit.noboot.hyper$qx$Y.cc.hyper <- data.hyper$Y.cc.hyper # bring outcome back into quantized data

#add the covariates and weights too
qc.fit.noboot.hyper$qx$age_dl <- data.hyper$age_dl 
qc.fit.noboot.hyper$qx$ageusa_cat_bl_2 <- data.hyper$ageusa_cat_bl_2 
qc.fit.noboot.hyper$qx$ageusa_cat_bl_3 <- data.hyper$ageusa_cat_bl_3 
qc.fit.noboot.hyper$qx$meducat_bl_2 <- data.hyper$meducat_bl_2 
qc.fit.noboot.hyper$qx$meducat_bl_3 <- data.hyper$meducat_bl_3 
qc.fit.noboot.hyper$qx$imarcat_10_5y <- data.hyper$imarcat_10_5y 
qc.fit.noboot.hyper$qx$iagwork_10_5y_2 <- data.hyper$iagwork_10_5y_2 
qc.fit.noboot.hyper$qx$iagwork_10_5y_3 <- data.hyper$iagwork_10_5y_3 
qc.fit.noboot.hyper$qx$i2_povcat2_10_5y <- data.hyper$i2_povcat2_10_5y 
qc.fit.noboot.hyper$qx$ipaw <- data.hyper$ipaw

# adjusted coefficients from underlying model
newfit.noboot.hyper <- glm(Y.cc.hyper ~ 
                      age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                      meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                      iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                      op_q + #exposures
                      pyr_q + carb_q + neo_q + mn_q + gly_q + paraq_q, 
                   data = qc.fit.noboot.hyper$qx, family=binomial(),
                   )

newfit.noboot.hyper ##this is where the individual coefficients are
tidy(newfit.noboot.hyper, conf.int = T) # and confidence intervals

sum(newfit.noboot.hyper$coefficients[-c(1:10)]) # sums to psi_1 

coef(qc.fit.noboot.hyper)

plot(qc.fit.noboot.hyper)

  #Making my own plot
  coefficients <- qc.fit.noboot.hyper$fit$coefficients[qc.fit.noboot.hyper$expnms]
  pos_sum <- sum(coefficients[coefficients > 0])
  neg_sum <- sum(coefficients[coefficients < 0])

  weights <- rep(NA, length(coefficients))
  weights[coefficients > 0] <- coefficients[coefficients > 0] / pos_sum
  weights[coefficients < 0] <- -(coefficients[coefficients < 0] / neg_sum)

  plot_data <- data.frame(
    exposure = qc.fit.noboot.hyper$expnms,
    weights = weights
  )

  plot_data$exposure <- factor(plot_data$exposure, levels = qc.fit.noboot.hyper$expnms)
  
  p <- ggplot(plot_data, aes(x = weights, y = exposure)) +
    geom_bar(stat = "identity", width = 0.8, aes(fill = weights > 0)) +
    geom_vline(xintercept = 0, linetype = "dotted") +
    scale_fill_manual(values = c("TRUE" = "#818181", "FALSE" = "#ABABAB"), guide = "none") +
    labs(
      x = "Weight of Exposure",
      y = "Exposures"
    ) +
    theme_classic()+
    scale_x_continuous(
      limits = c(-1.0, 1.0),
      breaks = c(-0.75, -0.50, -0.25, 0, 0.25, 0.50, 0.75)
    )
  
  print(p)
```

```{r, joint exposure models, binary outcomes, qgcomp.glm.noboot, diabetes}
qc.fit.noboot.diabe <- qgcomp.glm.noboot(Y.cc.diabe ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.diabe, #dataset
                                family=binomial(), 
                                q=4
                                )

qc.fit.noboot.diabe

# underlying model of qgcomp fit
qc.fit.noboot.diabe$qx$Y.cc.diabe <- data.diabe$Y.cc.diabe # bring outcome back into quantized data

#add the covariates and weights too
qc.fit.noboot.diabe$qx$age_dl <- data.diabe$age_dl 
qc.fit.noboot.diabe$qx$ageusa_cat_bl_2 <- data.diabe$ageusa_cat_bl_2 
qc.fit.noboot.diabe$qx$ageusa_cat_bl_3 <- data.diabe$ageusa_cat_bl_3 
qc.fit.noboot.diabe$qx$meducat_bl_2 <- data.diabe$meducat_bl_2 
qc.fit.noboot.diabe$qx$meducat_bl_3 <- data.diabe$meducat_bl_3 
qc.fit.noboot.diabe$qx$imarcat_10_5y <- data.diabe$imarcat_10_5y 
qc.fit.noboot.diabe$qx$iagwork_10_5y_2 <- data.diabe$iagwork_10_5y_2 
qc.fit.noboot.diabe$qx$iagwork_10_5y_3 <- data.diabe$iagwork_10_5y_3 
qc.fit.noboot.diabe$qx$i2_povcat2_10_5y <- data.diabe$i2_povcat2_10_5y 
qc.fit.noboot.diabe$qx$ipaw <- data.diabe$ipaw

# adjusted coefficients from underlying model
newfit.noboot.diabe <- glm(Y.cc.diabe ~ 
                      age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                      meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                      iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                      op_q + #exposures
                      pyr_q + carb_q + neo_q + mn_q + gly_q + paraq_q, 
                   data = qc.fit.noboot.diabe$qx, family=binomial(),
                   )

newfit.noboot.diabe ##this is where the individual coefficients are
tidy(newfit.noboot.diabe, conf.int = T) # and confidence intervals

sum(newfit.noboot.diabe$coefficients[-c(1:10)]) # sums to psi_1 

coef(qc.fit.noboot.diabe)

plot(qc.fit.noboot.diabe)

  #Making my own plot
  coefficients <- qc.fit.noboot.diabe$fit$coefficients[qc.fit.noboot.diabe$expnms]
  pos_sum <- sum(coefficients[coefficients > 0])
  neg_sum <- sum(coefficients[coefficients < 0])

  weights <- rep(NA, length(coefficients))
  weights[coefficients > 0] <- coefficients[coefficients > 0] / pos_sum
  weights[coefficients < 0] <- -(coefficients[coefficients < 0] / neg_sum)

  plot_data <- data.frame(
    exposure = qc.fit.noboot.diabe$expnms,
    weights = weights
  )

  plot_data$exposure <- factor(plot_data$exposure, levels = qc.fit.noboot.diabe$expnms)
  
  p <- ggplot(plot_data, aes(x = weights, y = exposure)) +
    geom_bar(stat = "identity", width = 0.8, aes(fill = weights > 0)) +
    geom_vline(xintercept = 0, linetype = "dotted") +
    scale_fill_manual(values = c("TRUE" = "#818181", "FALSE" = "#818181"), guide = "none") +
    labs(
      x = "Weight of Exposure",
      y = "Exposures"
    ) +
    theme_classic()+
    scale_x_continuous(
      limits = c(-1.0, 1.0),
      breaks = c(-0.75, -0.50, -0.25, 0, 0.25, 0.50, 0.75)
    )
  
  print(p)
```

```{r, joint exposure models, binary outcomes, qgcomp.glm.noboot, obese}
qc.fit.noboot.obese <- qgcomp.glm.noboot(Y.cc.obese ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.obese, #dataset
                                family=binomial(), 
                                q=4
                                )

qc.fit.noboot.obese

# underlying model of qgcomp fit
qc.fit.noboot.obese$qx$Y.cc.obese <- data.obese$Y.cc.obese # bring outcome back into quantized data

#add the covariates and weights too
qc.fit.noboot.obese$qx$age_dl <- data.obese$age_dl 
qc.fit.noboot.obese$qx$ageusa_cat_bl_2 <- data.obese$ageusa_cat_bl_2 
qc.fit.noboot.obese$qx$ageusa_cat_bl_3 <- data.obese$ageusa_cat_bl_3 
qc.fit.noboot.obese$qx$meducat_bl_2 <- data.obese$meducat_bl_2 
qc.fit.noboot.obese$qx$meducat_bl_3 <- data.obese$meducat_bl_3 
qc.fit.noboot.obese$qx$imarcat_10_5y <- data.obese$imarcat_10_5y 
qc.fit.noboot.obese$qx$iagwork_10_5y_2 <- data.obese$iagwork_10_5y_2 
qc.fit.noboot.obese$qx$iagwork_10_5y_3 <- data.obese$iagwork_10_5y_3 
qc.fit.noboot.obese$qx$i2_povcat2_10_5y <- data.obese$i2_povcat2_10_5y 
qc.fit.noboot.obese$qx$ipaw <- data.obese$ipaw

# adjusted coefficients from underlying model
newfit.noboot.obese <- glm(Y.cc.obese ~ 
                      age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                      meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                      iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                      op_q + #exposures
                      pyr_q + carb_q + neo_q + mn_q + gly_q + paraq_q, 
                   data = qc.fit.noboot.obese$qx, family=binomial(),
                   )

newfit.noboot.obese ##this is where the individual coefficients are
tidy(newfit.noboot.obese, conf.int = T) # and confidence intervals

sum(newfit.noboot.obese$coefficients[-c(1:10)]) # sums to psi_1 

coef(qc.fit.noboot.obese)

plot(qc.fit.noboot.obese)

  #Making my own plot
  coefficients <- qc.fit.noboot.obese$fit$coefficients[qc.fit.noboot.obese$expnms]
  pos_sum <- sum(coefficients[coefficients > 0])
  neg_sum <- sum(coefficients[coefficients < 0])

  weights <- rep(NA, length(coefficients))
  weights[coefficients > 0] <- coefficients[coefficients > 0] / pos_sum
  weights[coefficients < 0] <- -(coefficients[coefficients < 0] / neg_sum)

  plot_data <- data.frame(
    exposure = qc.fit.noboot.obese$expnms,
    weights = weights
  )

  plot_data$exposure <- factor(plot_data$exposure, levels = qc.fit.noboot.obese$expnms)
  
  p <- ggplot(plot_data, aes(x = weights, y = exposure)) +
    geom_bar(stat = "identity", width = 0.8, aes(fill = weights > 0)) +
    geom_vline(xintercept = 0, linetype = "dotted") +
    scale_fill_manual(values = c("TRUE" = "#818181", "FALSE" = "#818181"), guide = "none") +
    labs(
      x = "Weight of Exposure",
      y = "Exposures"
    ) +
    theme_classic()+
    scale_x_continuous(
      limits = c(-1.0, 1.0),
      breaks = c(-0.75, -0.50, -0.25, 0, 0.25, 0.50, 0.75)
    )
  
  print(p)
```

```{r, joint exposure models, binary outcomes, qgcomp.glm.noboot, BP ind}
qc.fit.noboot.bpind <- qgcomp.glm.noboot(Y.cc.bpind ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.bpind, #dataset
                                family=binomial(), 
                                q=4
                                )

qc.fit.noboot.bpind

# underlying model of qgcomp fit
qc.fit.noboot.bpind$qx$Y.cc.bpind <- data.bpind$Y.cc.bpind # bring outcome back into quantized data

#add the covariates and weights too
qc.fit.noboot.bpind$qx$age_dl <- data.bpind$age_dl 
qc.fit.noboot.bpind$qx$ageusa_cat_bl_2 <- data.bpind$ageusa_cat_bl_2 
qc.fit.noboot.bpind$qx$ageusa_cat_bl_3 <- data.bpind$ageusa_cat_bl_3 
qc.fit.noboot.bpind$qx$meducat_bl_2 <- data.bpind$meducat_bl_2 
qc.fit.noboot.bpind$qx$meducat_bl_3 <- data.bpind$meducat_bl_3 
qc.fit.noboot.bpind$qx$imarcat_10_5y <- data.bpind$imarcat_10_5y 
qc.fit.noboot.bpind$qx$iagwork_10_5y_2 <- data.bpind$iagwork_10_5y_2 
qc.fit.noboot.bpind$qx$iagwork_10_5y_3 <- data.bpind$iagwork_10_5y_3 
qc.fit.noboot.bpind$qx$i2_povcat2_10_5y <- data.bpind$i2_povcat2_10_5y 
qc.fit.noboot.bpind$qx$ipaw <- data.bpind$ipaw

# adjusted coefficients from underlying model
newfit.noboot.bpind <- glm(Y.cc.bpind ~ 
                      age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                      meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                      iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                      op_q + #exposures
                      pyr_q + carb_q + neo_q + mn_q + gly_q + paraq_q, 
                   data = qc.fit.noboot.bpind$qx, family=binomial(),
                   )

newfit.noboot.bpind ##this is where the individual coefficients are
tidy(newfit.noboot.bpind, conf.int = T) # and confidence intervals

sum(newfit.noboot.bpind$coefficients[-c(1:10)]) # sums to psi_1 

coef(qc.fit.noboot.bpind)

plot(qc.fit.noboot.bpind)

  #Making my own plot
  coefficients <- qc.fit.noboot.bpind$fit$coefficients[qc.fit.noboot.bpind$expnms]
  pos_sum <- sum(coefficients[coefficients > 0])
  neg_sum <- sum(coefficients[coefficients < 0])

  weights <- rep(NA, length(coefficients))
  weights[coefficients > 0] <- coefficients[coefficients > 0] / pos_sum
  weights[coefficients < 0] <- -(coefficients[coefficients < 0] / neg_sum)

  plot_data <- data.frame(
    exposure = qc.fit.noboot.bpind$expnms,
    weights = weights
  )

  plot_data$exposure <- factor(plot_data$exposure, levels = qc.fit.noboot.bpind$expnms)
  
  p <- ggplot(plot_data, aes(x = weights, y = exposure)) +
    geom_bar(stat = "identity", width = 0.8, aes(fill = weights > 0)) +
    geom_vline(xintercept = 0, linetype = "dotted") +
    scale_fill_manual(values = c("TRUE" = "#818181", "FALSE" = "#ABABAB"), guide = "none") +
    labs(
      x = "Weight of Exposure",
      y = "Exposures"
    ) +
    theme_classic()+
    scale_x_continuous(
      limits = c(-1.0, 1.0),
      breaks = c(-0.75, -0.50, -0.25, 0, 0.25, 0.50, 0.75)
    )
  
  print(p)
```

```{r, joint exposure models, binary outcomes, qgcomp.glm.noboot, triglyceride ind}
qc.fit.noboot.trind <- qgcomp.glm.noboot(Y.cc.trind ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.trind, #dataset
                                family=binomial(), 
                                q=4
                                )

qc.fit.noboot.trind

# underlying model of qgcomp fit
qc.fit.noboot.trind$qx$Y.cc.trind <- data.trind$Y.cc.trind # bring outcome back into quantized data

#add the covariates and weights too
qc.fit.noboot.trind$qx$age_dl <- data.trind$age_dl 
qc.fit.noboot.trind$qx$ageusa_cat_bl_2 <- data.trind$ageusa_cat_bl_2 
qc.fit.noboot.trind$qx$ageusa_cat_bl_3 <- data.trind$ageusa_cat_bl_3 
qc.fit.noboot.trind$qx$meducat_bl_2 <- data.trind$meducat_bl_2 
qc.fit.noboot.trind$qx$meducat_bl_3 <- data.trind$meducat_bl_3 
qc.fit.noboot.trind$qx$imarcat_10_5y <- data.trind$imarcat_10_5y 
qc.fit.noboot.trind$qx$iagwork_10_5y_2 <- data.trind$iagwork_10_5y_2 
qc.fit.noboot.trind$qx$iagwork_10_5y_3 <- data.trind$iagwork_10_5y_3 
qc.fit.noboot.trind$qx$i2_povcat2_10_5y <- data.trind$i2_povcat2_10_5y 
qc.fit.noboot.trind$qx$ipaw <- data.trind$ipaw

# adjusted coefficients from underlying model
newfit.noboot.trind <- glm(Y.cc.trind ~ 
                      age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                      meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                      iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                      op_q + #exposures
                      pyr_q + carb_q + neo_q + mn_q + gly_q + paraq_q, 
                   data = qc.fit.noboot.trind$qx, family=binomial(),
                   )

newfit.noboot.trind ##this is where the individual coefficients are
tidy(newfit.noboot.trind, conf.int = T) # and confidence intervals

sum(newfit.noboot.trind$coefficients[-c(1:10)]) # sums to psi_1 

coef(qc.fit.noboot.trind)

plot(qc.fit.noboot.trind)

  #Making my own plot
  coefficients <- qc.fit.noboot.trind$fit$coefficients[qc.fit.noboot.trind$expnms]
  pos_sum <- sum(coefficients[coefficients > 0])
  neg_sum <- sum(coefficients[coefficients < 0])

  weights <- rep(NA, length(coefficients))
  weights[coefficients > 0] <- coefficients[coefficients > 0] / pos_sum
  weights[coefficients < 0] <- -(coefficients[coefficients < 0] / neg_sum)

  plot_data <- data.frame(
    exposure = qc.fit.noboot.trind$expnms,
    weights = weights
  )

  plot_data$exposure <- factor(plot_data$exposure, levels = qc.fit.noboot.trind$expnms)
  
  p <- ggplot(plot_data, aes(x = weights, y = exposure)) +
    geom_bar(stat = "identity", width = 0.8, aes(fill = weights > 0)) +
    geom_vline(xintercept = 0, linetype = "dotted") +
    scale_fill_manual(values = c("TRUE" = "#818181", "FALSE" = "#818181"), guide = "none") +
    labs(
      x = "Weight of Exposure",
      y = "Exposures"
    ) +
    theme_classic()+
    scale_x_continuous(
      limits = c(-1.0, 1.0),
      breaks = c(-0.75, -0.50, -0.25, 0, 0.25, 0.50, 0.75)
    )
  
  print(p)
```

```{r, joint exposure models, binary outcomes, qgcomp.glm.noboot, HDL ind}
qc.fit.noboot.chind <- qgcomp.glm.noboot(Y.cc.chind ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.chind, #dataset
                                family=binomial(), 
                                q=4
                                )

qc.fit.noboot.chind

# underlying model of qgcomp fit
qc.fit.noboot.chind$qx$Y.cc.chind <- data.chind$Y.cc.chind # bring outcome back into quantized data

#add the covariates and weights too
qc.fit.noboot.chind$qx$age_dl <- data.chind$age_dl 
qc.fit.noboot.chind$qx$ageusa_cat_bl_2 <- data.chind$ageusa_cat_bl_2 
qc.fit.noboot.chind$qx$ageusa_cat_bl_3 <- data.chind$ageusa_cat_bl_3 
qc.fit.noboot.chind$qx$meducat_bl_2 <- data.chind$meducat_bl_2 
qc.fit.noboot.chind$qx$meducat_bl_3 <- data.chind$meducat_bl_3 
qc.fit.noboot.chind$qx$imarcat_10_5y <- data.chind$imarcat_10_5y 
qc.fit.noboot.chind$qx$iagwork_10_5y_2 <- data.chind$iagwork_10_5y_2 
qc.fit.noboot.chind$qx$iagwork_10_5y_3 <- data.chind$iagwork_10_5y_3 
qc.fit.noboot.chind$qx$i2_povcat2_10_5y <- data.chind$i2_povcat2_10_5y 
qc.fit.noboot.chind$qx$ipaw <- data.chind$ipaw

# adjusted coefficients from underlying model
newfit.noboot.chind <- glm(Y.cc.chind ~ 
                      age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                      meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                      iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                      op_q + #exposures
                      pyr_q + carb_q + neo_q + mn_q + gly_q + paraq_q, 
                   data = qc.fit.noboot.chind$qx, family=binomial(),
                   )

newfit.noboot.chind ##this is where the individual coefficients are
tidy(newfit.noboot.chind, conf.int = T) # and confidence intervals

sum(newfit.noboot.chind$coefficients[-c(1:10)]) # sums to psi_1 

coef(qc.fit.noboot.chind)

plot(qc.fit.noboot.chind)

  #Making my own plot
  coefficients <- qc.fit.noboot.chind$fit$coefficients[qc.fit.noboot.chind$expnms]
  pos_sum <- sum(coefficients[coefficients > 0])
  neg_sum <- sum(coefficients[coefficients < 0])

  weights <- rep(NA, length(coefficients))
  weights[coefficients > 0] <- coefficients[coefficients > 0] / pos_sum
  weights[coefficients < 0] <- -(coefficients[coefficients < 0] / neg_sum)

  plot_data <- data.frame(
    exposure = qc.fit.noboot.chind$expnms,
    weights = weights
  )

  plot_data$exposure <- factor(plot_data$exposure, levels = qc.fit.noboot.chind$expnms)
  
  p <- ggplot(plot_data, aes(x = weights, y = exposure)) +
    geom_bar(stat = "identity", width = 0.8, aes(fill = weights > 0)) +
    geom_vline(xintercept = 0, linetype = "dotted") +
    scale_fill_manual(values = c("TRUE" = "#818181", "FALSE" = "#ABABAB"), guide = "none") +
    labs(
      x = "Weight of Exposure",
      y = "Exposures"
    ) +
    theme_classic()+
    scale_x_continuous(
      limits = c(-1.0, 1.0),
      breaks = c(-0.75, -0.50, -0.25, 0, 0.25, 0.50, 0.75)
    )
  
  print(p)
```

```{r, joint exposure models, binary outcomes, qgcomp.glm.noboot, glucose ind}
qc.fit.noboot.glind <- qgcomp.glm.noboot(Y.cc.glind ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.glind, #dataset
                                family=binomial(), 
                                q=4
                                )

qc.fit.noboot.glind

# underlying model of qgcomp fit
qc.fit.noboot.glind$qx$Y.cc.glind <- data.glind$Y.cc.glind # bring outcome back into quantized data

#add the covariates and weights too
qc.fit.noboot.glind$qx$age_dl <- data.glind$age_dl 
qc.fit.noboot.glind$qx$ageusa_cat_bl_2 <- data.glind$ageusa_cat_bl_2 
qc.fit.noboot.glind$qx$ageusa_cat_bl_3 <- data.glind$ageusa_cat_bl_3 
qc.fit.noboot.glind$qx$meducat_bl_2 <- data.glind$meducat_bl_2 
qc.fit.noboot.glind$qx$meducat_bl_3 <- data.glind$meducat_bl_3 
qc.fit.noboot.glind$qx$imarcat_10_5y <- data.glind$imarcat_10_5y 
qc.fit.noboot.glind$qx$iagwork_10_5y_2 <- data.glind$iagwork_10_5y_2 
qc.fit.noboot.glind$qx$iagwork_10_5y_3 <- data.glind$iagwork_10_5y_3 
qc.fit.noboot.glind$qx$i2_povcat2_10_5y <- data.glind$i2_povcat2_10_5y 
qc.fit.noboot.glind$qx$ipaw <- data.glind$ipaw

# adjusted coefficients from underlying model
newfit.noboot.glind <- glm(Y.cc.glind ~ 
                      age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                      meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                      iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                      op_q + #exposures
                      pyr_q + carb_q + neo_q + mn_q + gly_q + paraq_q, 
                   data = qc.fit.noboot.glind$qx, family=binomial(),
                   )

newfit.noboot.glind ##this is where the individual coefficients are
tidy(newfit.noboot.glind, conf.int = T) # and confidence intervals

sum(newfit.noboot.glind$coefficients[-c(1:10)]) # sums to psi_1 

coef(qc.fit.noboot.glind)

plot(qc.fit.noboot.glind)

  #Making my own plot
  coefficients <- qc.fit.noboot.glind$fit$coefficients[qc.fit.noboot.glind$expnms]
  pos_sum <- sum(coefficients[coefficients > 0])
  neg_sum <- sum(coefficients[coefficients < 0])

  weights <- rep(NA, length(coefficients))
  weights[coefficients > 0] <- coefficients[coefficients > 0] / pos_sum
  weights[coefficients < 0] <- -(coefficients[coefficients < 0] / neg_sum)

  plot_data <- data.frame(
    exposure = qc.fit.noboot.glind$expnms,
    weights = weights
  )

  plot_data$exposure <- factor(plot_data$exposure, levels = qc.fit.noboot.glind$expnms)
  
  p <- ggplot(plot_data, aes(x = weights, y = exposure)) +
    geom_bar(stat = "identity", width = 0.8, aes(fill = weights > 0)) +
    geom_vline(xintercept = 0, linetype = "dotted") +
    scale_fill_manual(values = c("TRUE" = "#818181", "FALSE" = "#818181"), guide = "none") +
    labs(
      x = "Weight of Exposure",
      y = "Exposures"
    ) +
    theme_classic()+
    scale_x_continuous(
      limits = c(-1.0, 1.0),
      breaks = c(-0.75, -0.50, -0.25, 0, 0.25, 0.50, 0.75)
    )
  
  print(p)
```

```{r, joint exposure models, binary outcomes, qgcomp.glm.noboot, waist ind}
qc.fit.noboot.waind <- qgcomp.glm.noboot(Y.cc.waind ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.waind, #dataset
                                family=binomial(), 
                                q=4
                                )

qc.fit.noboot.waind

# underlying model of qgcomp fit
qc.fit.noboot.waind$qx$Y.cc.waind <- data.waind$Y.cc.waind # bring outcome back into quantized data

#add the covariates and weights too
qc.fit.noboot.waind$qx$age_dl <- data.waind$age_dl 
qc.fit.noboot.waind$qx$ageusa_cat_bl_2 <- data.waind$ageusa_cat_bl_2 
qc.fit.noboot.waind$qx$ageusa_cat_bl_3 <- data.waind$ageusa_cat_bl_3 
qc.fit.noboot.waind$qx$meducat_bl_2 <- data.waind$meducat_bl_2 
qc.fit.noboot.waind$qx$meducat_bl_3 <- data.waind$meducat_bl_3 
qc.fit.noboot.waind$qx$imarcat_10_5y <- data.waind$imarcat_10_5y 
qc.fit.noboot.waind$qx$iagwork_10_5y_2 <- data.waind$iagwork_10_5y_2 
qc.fit.noboot.waind$qx$iagwork_10_5y_3 <- data.waind$iagwork_10_5y_3 
qc.fit.noboot.waind$qx$i2_povcat2_10_5y <- data.waind$i2_povcat2_10_5y 
qc.fit.noboot.waind$qx$ipaw <- data.waind$ipaw

# adjusted coefficients from underlying model
newfit.noboot.waind <- glm(Y.cc.waind ~ 
                      age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                      meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                      iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                      op_q + #exposures
                      pyr_q + carb_q + neo_q + mn_q + gly_q + paraq_q, 
                   data = qc.fit.noboot.waind$qx, family=binomial(),
                   )

newfit.noboot.waind ##this is where the individual coefficients are
tidy(newfit.noboot.waind, conf.int = T) # and confidence intervals

sum(newfit.noboot.waind$coefficients[-c(1:10)]) # sums to psi_1 

coef(qc.fit.noboot.waind)

plot(qc.fit.noboot.waind)

  #Making my own plot
  coefficients <- qc.fit.noboot.waind$fit$coefficients[qc.fit.noboot.waind$expnms]
  pos_sum <- sum(coefficients[coefficients > 0])
  neg_sum <- sum(coefficients[coefficients < 0])

  weights <- rep(NA, length(coefficients))
  weights[coefficients > 0] <- coefficients[coefficients > 0] / pos_sum
  weights[coefficients < 0] <- -(coefficients[coefficients < 0] / neg_sum)

  plot_data <- data.frame(
    exposure = qc.fit.noboot.waind$expnms,
    weights = weights
  )

  plot_data$exposure <- factor(plot_data$exposure, levels = qc.fit.noboot.waind$expnms)
  
  p <- ggplot(plot_data, aes(x = weights, y = exposure)) +
    geom_bar(stat = "identity", width = 0.8, aes(fill = weights > 0)) +
    geom_vline(xintercept = 0, linetype = "dotted") +
    scale_fill_manual(values = c("TRUE" = "#ABABAB", "FALSE" = "#818181"), guide = "none") +
    labs(
      x = "Weight of Exposure",
      y = "Exposures"
    ) +
    theme_classic()+
    scale_x_continuous(
      limits = c(-1.0, 1.0),
      breaks = c(-0.75, -0.50, -0.25, 0, 0.25, 0.50, 0.75)
    )
  
  print(p)
```

```{r, joint exposure models, binary outcomes, qgcomp.glm.noboot, MetS}
qc.fit.noboot.metab <- qgcomp.glm.noboot(Y.cc.metab ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.metab, #dataset
                                family=binomial(), 
                                q=4
                                )

qc.fit.noboot.metab

# underlying model of qgcomp fit
qc.fit.noboot.metab$qx$Y.cc.metab <- data.metab$Y.cc.metab # bring outcome back into quantized data

#add the covariates and weights too
qc.fit.noboot.metab$qx$age_dl <- data.metab$age_dl 
qc.fit.noboot.metab$qx$ageusa_cat_bl_2 <- data.metab$ageusa_cat_bl_2 
qc.fit.noboot.metab$qx$ageusa_cat_bl_3 <- data.metab$ageusa_cat_bl_3 
qc.fit.noboot.metab$qx$meducat_bl_2 <- data.metab$meducat_bl_2 
qc.fit.noboot.metab$qx$meducat_bl_3 <- data.metab$meducat_bl_3 
qc.fit.noboot.metab$qx$imarcat_10_5y <- data.metab$imarcat_10_5y 
qc.fit.noboot.metab$qx$iagwork_10_5y_2 <- data.metab$iagwork_10_5y_2 
qc.fit.noboot.metab$qx$iagwork_10_5y_3 <- data.metab$iagwork_10_5y_3 
qc.fit.noboot.metab$qx$i2_povcat2_10_5y <- data.metab$i2_povcat2_10_5y 
qc.fit.noboot.metab$qx$ipaw <- data.metab$ipaw

# adjusted coefficients from underlying model
newfit.noboot.metab <- glm(Y.cc.metab ~ 
                      age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                      meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                      iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                      op_q + #exposures
                      pyr_q + carb_q + neo_q + mn_q + gly_q + paraq_q, 
                   data = qc.fit.noboot.metab$qx, family=binomial(),
                   )

newfit.noboot.metab ##this is where the individual coefficients are
tidy(newfit.noboot.metab, conf.int = T) # and confidence intervals

sum(newfit.noboot.metab$coefficients[-c(1:10)]) # sums to psi_1 

coef(qc.fit.noboot.metab)

plot(qc.fit.noboot.metab)

  #Making my own plot
  coefficients <- qc.fit.noboot.metab$fit$coefficients[qc.fit.noboot.metab$expnms]
  pos_sum <- sum(coefficients[coefficients > 0])
  neg_sum <- sum(coefficients[coefficients < 0])

  weights <- rep(NA, length(coefficients))
  weights[coefficients > 0] <- coefficients[coefficients > 0] / pos_sum
  weights[coefficients < 0] <- -(coefficients[coefficients < 0] / neg_sum)

  plot_data <- data.frame(
    exposure = qc.fit.noboot.metab$expnms,
    weights = weights
  )

  plot_data$exposure <- factor(plot_data$exposure, levels = qc.fit.noboot.metab$expnms)
  
  p <- ggplot(plot_data, aes(x = weights, y = exposure)) +
    geom_bar(stat = "identity", width = 0.8, aes(fill = weights > 0)) +
    geom_vline(xintercept = 0, linetype = "dotted") +
    scale_fill_manual(values = c("TRUE" = "#818181", "FALSE" = "#ABABAB"), guide = "none") +
    labs(
      x = "Weight of Exposure",
      y = "Exposures"
    ) +
    theme_classic()+
    scale_x_continuous(
      limits = c(-1.0, 1.0),
      breaks = c(-0.75, -0.50, -0.25, 0, 0.25, 0.50, 0.75)
    )
  
  print(p)
```

```{r, joint exposure models, binary outcomes, qgcomp.glm.noboot, CRP cat}
qc.fit.noboot.crpca <- qgcomp.glm.noboot(Y.cc.crpca ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.crpca, #dataset
                                family=binomial(), 
                                q=4
                                )

qc.fit.noboot.crpca

# underlying model of qgcomp fit
qc.fit.noboot.crpca$qx$Y.cc.crpca <- data.crpca$Y.cc.crpca # bring outcome back into quantized data

#add the covariates and weights too
qc.fit.noboot.crpca$qx$age_dl <- data.crpca$age_dl 
qc.fit.noboot.crpca$qx$ageusa_cat_bl_2 <- data.crpca$ageusa_cat_bl_2 
qc.fit.noboot.crpca$qx$ageusa_cat_bl_3 <- data.crpca$ageusa_cat_bl_3 
qc.fit.noboot.crpca$qx$meducat_bl_2 <- data.crpca$meducat_bl_2 
qc.fit.noboot.crpca$qx$meducat_bl_3 <- data.crpca$meducat_bl_3 
qc.fit.noboot.crpca$qx$imarcat_10_5y <- data.crpca$imarcat_10_5y 
qc.fit.noboot.crpca$qx$iagwork_10_5y_2 <- data.crpca$iagwork_10_5y_2 
qc.fit.noboot.crpca$qx$iagwork_10_5y_3 <- data.crpca$iagwork_10_5y_3 
qc.fit.noboot.crpca$qx$i2_povcat2_10_5y <- data.crpca$i2_povcat2_10_5y 
qc.fit.noboot.crpca$qx$ipaw <- data.crpca$ipaw

# adjusted coefficients from underlying model
newfit.noboot.crpca <- glm(Y.cc.crpca ~ 
                      age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                      meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                      iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                      op_q + #exposures
                      pyr_q + carb_q + neo_q + mn_q + gly_q + paraq_q, 
                   data = qc.fit.noboot.crpca$qx, family=binomial(),
                   )

newfit.noboot.crpca ##this is where the individual coefficients are
tidy(newfit.noboot.crpca, conf.int = T) # and confidence intervals

sum(newfit.noboot.crpca$coefficients[-c(1:10)]) # sums to psi_1 

coef(qc.fit.noboot.crpca)

plot(qc.fit.noboot.crpca)

  #Making my own plot
  coefficients <- qc.fit.noboot.crpca$fit$coefficients[qc.fit.noboot.crpca$expnms]
  pos_sum <- sum(coefficients[coefficients > 0])
  neg_sum <- sum(coefficients[coefficients < 0])

  weights <- rep(NA, length(coefficients))
  weights[coefficients > 0] <- coefficients[coefficients > 0] / pos_sum
  weights[coefficients < 0] <- -(coefficients[coefficients < 0] / neg_sum)

  plot_data <- data.frame(
    exposure = qc.fit.noboot.crpca$expnms,
    weights = weights
  )

  plot_data$exposure <- factor(plot_data$exposure, levels = qc.fit.noboot.crpca$expnms)
  
  p <- ggplot(plot_data, aes(x = weights, y = exposure)) +
    geom_bar(stat = "identity", width = 0.8, aes(fill = weights > 0)) +
    geom_vline(xintercept = 0, linetype = "dotted") +
    scale_fill_manual(values = c("TRUE" = "#818181", "FALSE" = "#ABABAB"), guide = "none") +
    labs(
      x = "Weight of Exposure",
      y = "Exposures"
    ) +
    theme_classic()+
    scale_x_continuous(
      limits = c(-1.0, 1.0),
      breaks = c(-0.75, -0.50, -0.25, 0, 0.25, 0.50, 0.75)
    )
  
  print(p)
```

### Binary outcomes - qgcomp.glm.ee (weights)
```{r, joint exposure models, binary outcomes, qgcomp.glm.ee, hypertension}
qc.fit.ee.hyper <- qgcomp.glm.ee(Y.cc.hyper ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.hyper, #dataset
                                family=binomial(), 
                                q=4,
                                weights=ipaw)

qc.fit.ee.hyper
plot(qc.fit.ee.hyper)
```

```{r, joint exposure models, binary outcomes, qgcomp.glm.ee, diabetes}
qc.fit.ee.diabe <- qgcomp.glm.ee(Y.cc.diabe ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.diabe, #dataset
                                family=binomial(), 
                                q=4,
                                weights=ipaw)

qc.fit.ee.diabe
plot(qc.fit.ee.diabe)
```

```{r, joint exposure models, binary outcomes, qgcomp.glm.ee, obese}
qc.fit.ee.obese <- qgcomp.glm.ee(Y.cc.obese ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.obese, #dataset
                                family=binomial(), 
                                q=4,
                                weights=ipaw)

qc.fit.ee.obese
plot(qc.fit.ee.obese)
```

```{r, joint exposure models, binary outcomes, qgcomp.glm.ee, BP ind}
qc.fit.ee.bpind <- qgcomp.glm.ee(Y.cc.bpind ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.bpind, #dataset
                                family=binomial(), 
                                q=4,
                                weights=ipaw)

qc.fit.ee.bpind
plot(qc.fit.ee.bpind)
```

```{r, joint exposure models, binary outcomes, qgcomp.glm.ee, triglyceride ind}
qc.fit.ee.trind <- qgcomp.glm.ee(Y.cc.trind ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.trind, #dataset
                                family=binomial(), 
                                q=4,
                                weights=ipaw)

qc.fit.ee.trind
plot(qc.fit.ee.trind)
```

```{r, joint exposure models, binary outcomes, qgcomp.glm.ee, HDL ind}
qc.fit.ee.chind <- qgcomp.glm.ee(Y.cc.chind ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.chind, #dataset
                                family=binomial(), 
                                q=4,
                                weights=ipaw)

qc.fit.ee.chind
plot(qc.fit.ee.chind)
```

```{r, joint exposure models, binary outcomes, qgcomp.glm.ee, glucose ind}
qc.fit.ee.glind <- qgcomp.glm.ee(Y.cc.glind ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.glind, #dataset
                                family=binomial(), 
                                q=4,
                                weights=ipaw)

qc.fit.ee.glind
plot(qc.fit.ee.glind)
```

```{r, joint exposure models, binary outcomes, qgcomp.glm.ee, waist ind}
qc.fit.ee.waind <- qgcomp.glm.ee(Y.cc.waind ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.waind, #dataset
                                family=binomial(), 
                                q=4,
                                weights=ipaw)

qc.fit.ee.waind
plot(qc.fit.ee.waind)
```

```{r, joint exposure models, binary outcomes, qgcomp.glm.ee, MetS}
qc.fit.ee.metab <- qgcomp.glm.ee(Y.cc.metab ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.metab, #dataset
                                family=binomial(), 
                                q=4,
                                weights=ipaw)

qc.fit.ee.metab
plot(qc.fit.ee.metab)
```

```{r, joint exposure models, binary outcomes, qgcomp.glm.ee, CRP cat}
qc.fit.ee.crpca <- qgcomp.glm.ee(Y.cc.crpca ~ #outcome
                                  age_dl + ageusa_cat_bl_2 + ageusa_cat_bl_3 + # covars
                                  meducat_bl_2 + meducat_bl_3 + imarcat_10_5y + 
                                  iagwork_10_5y_2+ iagwork_10_5y_3 + i2_povcat2_10_5y +
                                  op + #exposures
                                  pyr + carb+ neo + mn + gly + paraq,
                                expnms=Xnm.all, #exposure names
                                data.crpca, #dataset
                                family=binomial(), 
                                q=4,
                                weights=ipaw)

qc.fit.ee.crpca
plot(qc.fit.ee.crpca)
```
