---
title: "pest_cmd_bkmr_novarsel_continuous_v3.Rmd"
author: "LCalderon"
output: html_document
date: "2025-12-09"
---

### SET UP DATA
```{r, load and setup data}
# Clear workspace
rm(list=ls())

# Set working directory
#setwd("/Users/lcalderon1/Library/CloudStorage/Box-Box/CHAM Maternal Cognition Study/Analyses and Manuscripts/Lucia's analyses/CHAM PUR Cardiometabolic/Analysis 2")
setwd("C:/Users/lucia/Box/CHAM Maternal Cognition Study/Analyses and Manuscripts/Lucia's analyses/CHAM PUR Cardiometabolic/Analysis 2/")

library(tableone)
library(fastDummies)
library(coda)
library(haven)
library(multcomp)
library(ggplot2)
library(ggcorrplot)
library(qgcomp)
library(qgcompint)
library(gfoRmula)
library(broom)
library(boot)
library(bkmr)
library(tidyr)
library(tibble)
library(dplyr)

# Read in Data from Stata (this dataset only includes the analytic sample)
data<-read_dta("pest_cmd_analysis_v6.dta") 

# Drop outliers for continuous outcomes
data$mbmi_mc1[data$mbmi_mc1_out==1]<-NA
data$mwaist_mc1[data$mwaist_mc1_out==1]<-NA
data$mbpsys_mc1[data$mbpsys_mc1_out==1]<-NA
data$mbpdia_mc1[data$mbpdia_mc1_out==1]<-NA
data$mbppul_mc1[data$mbppul_mc1_out==1]<-NA
data$mbpmap_mc1[data$mbpmap_mc1_out==1]<-NA
data$gluc_mc1[data$gluc_mc1_out==1]<-NA
data$hba1c_mc1[data$hba1c_mc1_out==1]<-NA
data$log_trig_mc1[data$log_trig_mc1_out==1]<-NA
data$hdl_mc1[data$hdl_mc1_out==1]<-NA
data$log_crp_mc1[data$log_crp_mc1_out==1]<-NA
data$log_il6_mc1[data$log_il6_mc1_out==1]<-NA

# Exclude those taking meds from relevant continuous outcomes
data$mbpsys_mc1[data$mbpsys_mc1_med==1]<-NA
data$mbpdia_mc1[data$mbpdia_mc1_med==1]<-NA
data$mbppul_mc1[data$mbppul_mc1_med==1]<-NA
data$mbpmap_mc1[data$mbpmap_mc1_med==1]<-NA
data$gluc_mc1[data$gluc_mc1_med==1]<-NA
data$hba1c_mc1[data$hba1c_mc1_med==1]<-NA
data$log_trig_mc1[data$log_trig_mc1_med==1]<-NA
data$hdl_mc1[data$hdl_mc1_med==1]<-NA

# Exclude non-fasting glucose
#data$gluc_mc1[data$gluc_mc1_nf==1]<-NA

# Table 1 to check consistency with Stata analysis 
myvars<- c("age_dl","ageusa_cat_bl","meducat_bl","imarcat_10_5y","iagwork_10_5y","i2_povcat2_10_5y",
           "mhtn_mc1","diabetes_mc1","mobese_mc1","waist_ind_mc1","bp_ind_mc1","gluc_ind_mc1","trig_ind_mc1","chdl_ind_mc1","metsyn_mc1","crp_cat_mc1",
           "mbpsys_mc1","mbpdia_mc1","mbppul_mc1","mbpmap_mc1","mbmi_mc1","mwaist_mc1","gluc_mc1","hba1c_mc1","log_trig_mc1","hdl_mc1","log_crp_mc1","log_il6_mc1")
mycatvars<-c("ageusa_cat_bl","meducat_bl","imarcat_10_5y","iagwork_10_5y","i2_povcat2_10_5y",
             "mhtn_mc1","diabetes_mc1","mobese_mc1","waist_ind_mc1","bp_ind_mc1","gluc_ind_mc1","trig_ind_mc1","chdl_ind_mc1","metsyn_mc1","crp_cat_mc1")
table1<-CreateTableOne(vars=myvars, data=data, factorVars=mycatvars)
tab1print<-print(table1, showAlllevels=T, catDigits=1, contDigits=1, pDigits=1, test=F, printToggle = FALSE)

#Subset out relevant covariates
data<-dummy_cols(data, select_columns = c("ageusa_cat_bl","meducat_bl","iagwork_10_5y"), 
                 remove_first_dummy = TRUE, remove_selected_columns = FALSE, 
                 remove_most_frequent_dummy = FALSE, ignore_na = FALSE)
X <- subset(data, select = c("age_dl","ageusa_cat_bl_2","ageusa_cat_bl_3","meducat_bl_2","meducat_bl_3",
                             "imarcat_10_5y","iagwork_10_5y_2","iagwork_10_5y_3","i2_povcat2_10_5y"))
X<-as.matrix(X)

#Exposures
Z<- subset(data, select = c("op",
                            "pyr",
                            "carb",
                            "neo",
                            "mn",
                            "gly",
                            "paraq"))

Z <- as.matrix(Z)

  #Correlation matrix
  cor_mat <- cor(Z, use = "pairwise.complete.obs")
  ggcorrplot(cor_mat,
             hc.order = FALSE,
             type = "lower",
             lab = TRUE,
             outline.color = "white",
             colors = c("#6D9EC1", "white", "#E46726"))

Z <- scale(Z) ## This is essential for BKMR

##Vectorize individual outcomes of interest from Y
Y_sys<-as.vector(data$mbpsys_mc1)
Y_dia<-as.vector(data$mbpdia_mc1)
Y_pul<-as.vector(data$mbppul_mc1)
Y_map<-as.vector(data$mbpmap_mc1)
Y_bmi<-as.vector(data$mbmi_mc1)
Y_wai<-as.vector(data$mwaist_mc1)
Y_glu<-as.vector(data$gluc_mc1)
Y_hba<-as.vector(data$hba1c_mc1)
Y_tri<-as.vector(data$log_trig_mc1)
Y_hdl<-as.vector(data$hdl_mc1)
Y_crp<-as.vector(data$log_crp_mc1)
Y_il6<-as.vector(data$log_il6_mc1)

Y_hyper<-as.vector(data$mhtn_mc1)
Y_diabe<-as.vector(data$diabetes_mc1)
Y_obese<-as.vector(data$mobese_mc1)
Y_waind<-as.vector(data$waist_ind_mc1)
Y_bpind<-as.vector(data$bp_ind_mc1)
Y_glind<-as.vector(data$gluc_ind_mc1)
Y_trind<-as.vector(data$trig_ind_mc1)
Y_chind<-as.vector(data$chdl_ind_mc1)
Y_metab<-as.vector(data$metsyn_mc1)
Y_crpca<-as.vector(data$crp_cat_mc1)

##Complete Case Flag for each Outcome
is.cc.sys <- complete.cases(cbind(X,Z,Y_sys))
is.cc.dia <- complete.cases(cbind(X,Z,Y_dia))
is.cc.pul <- complete.cases(cbind(X,Z,Y_pul))
is.cc.map <- complete.cases(cbind(X,Z,Y_map))
is.cc.bmi <- complete.cases(cbind(X,Z,Y_bmi))
is.cc.wai <- complete.cases(cbind(X,Z,Y_wai))
is.cc.glu <- complete.cases(cbind(X,Z,Y_glu))
is.cc.hba <- complete.cases(cbind(X,Z,Y_hba))
is.cc.tri <- complete.cases(cbind(X,Z,Y_tri))
is.cc.hdl <- complete.cases(cbind(X,Z,Y_hdl))
is.cc.crp <- complete.cases(cbind(X,Z,Y_crp))
is.cc.il6 <- complete.cases(cbind(X,Z,Y_il6))

is.cc.hyper <- complete.cases(cbind(X,Z,Y_hyper))
is.cc.diabe <- complete.cases(cbind(X,Z,Y_diabe))
is.cc.obese <- complete.cases(cbind(X,Z,Y_obese))
is.cc.waind <- complete.cases(cbind(X,Z,Y_waind))
is.cc.bpind <- complete.cases(cbind(X,Z,Y_bpind))
is.cc.glind <- complete.cases(cbind(X,Z,Y_glind))
is.cc.trind <- complete.cases(cbind(X,Z,Y_trind))
is.cc.chind <- complete.cases(cbind(X,Z,Y_chind))
is.cc.metab <- complete.cases(cbind(X,Z,Y_metab))
is.cc.crpca <- complete.cases(cbind(X,Z,Y_crpca))

##Subset outcomes as complete cases
Y.cc.sys <- subset(Y_sys,is.cc.sys) 
Y.cc.dia <- subset(Y_dia,is.cc.dia) 
Y.cc.pul <- subset(Y_pul,is.cc.pul) 
Y.cc.map <- subset(Y_map,is.cc.map) 
Y.cc.bmi <- subset(Y_bmi,is.cc.bmi)
Y.cc.wai <- subset(Y_wai,is.cc.wai)
Y.cc.glu <- subset(Y_glu,is.cc.glu)
Y.cc.hba <- subset(Y_hba,is.cc.hba)
Y.cc.tri <- subset(Y_tri,is.cc.tri)
Y.cc.hdl <- subset(Y_hdl,is.cc.hdl)
Y.cc.crp <- subset(Y_crp,is.cc.crp)
Y.cc.il6 <- subset(Y_il6,is.cc.il6)

Y.cc.hyper <- subset(Y_hyper,is.cc.hyper)
Y.cc.diabe <- subset(Y_diabe,is.cc.diabe)
Y.cc.obese <- subset(Y_obese,is.cc.obese)
Y.cc.waind <- subset(Y_waind,is.cc.waind)
Y.cc.bpind <- subset(Y_bpind,is.cc.bpind)
Y.cc.glind <- subset(Y_glind,is.cc.glind)
Y.cc.trind <- subset(Y_trind,is.cc.trind)
Y.cc.chind <- subset(Y_chind,is.cc.chind)
Y.cc.metab <- subset(Y_metab,is.cc.metab)
Y.cc.crpca <- subset(Y_crpca,is.cc.crpca)

# Set up data frames for regression models
data.sys <- as.data.frame(cbind(Y.cc.sys, Z[is.cc.sys,], X[is.cc.sys,]))
data.dia <- as.data.frame(cbind(Y.cc.dia, Z[is.cc.dia,], X[is.cc.dia,]))
data.pul <- as.data.frame(cbind(Y.cc.pul, Z[is.cc.pul,], X[is.cc.pul,]))
data.map <- as.data.frame(cbind(Y.cc.map, Z[is.cc.map,], X[is.cc.map,]))
data.bmi <- as.data.frame(cbind(Y.cc.bmi, Z[is.cc.bmi,], X[is.cc.bmi,]))
data.wai <- as.data.frame(cbind(Y.cc.wai, Z[is.cc.wai,], X[is.cc.wai,]))
data.glu <- as.data.frame(cbind(Y.cc.glu, Z[is.cc.glu,], X[is.cc.glu,]))
data.hba <- as.data.frame(cbind(Y.cc.hba, Z[is.cc.hba,], X[is.cc.hba,]))
data.tri <- as.data.frame(cbind(Y.cc.tri, Z[is.cc.tri,], X[is.cc.tri,]))
data.hdl <- as.data.frame(cbind(Y.cc.hdl, Z[is.cc.hdl,], X[is.cc.hdl,]))
data.crp <- as.data.frame(cbind(Y.cc.crp, Z[is.cc.crp,], X[is.cc.crp,]))
data.il6 <- as.data.frame(cbind(Y.cc.il6, Z[is.cc.il6,], X[is.cc.il6,]))

data.hyper <- as.data.frame(cbind(Y.cc.hyper, Z[is.cc.hyper,], X[is.cc.hyper,]))
data.diabe <- as.data.frame(cbind(Y.cc.diabe, Z[is.cc.diabe,], X[is.cc.diabe,]))
data.obese <- as.data.frame(cbind(Y.cc.obese, Z[is.cc.obese,], X[is.cc.obese,]))
data.waind <- as.data.frame(cbind(Y.cc.waind, Z[is.cc.waind,], X[is.cc.waind,]))
data.bpind <- as.data.frame(cbind(Y.cc.bpind, Z[is.cc.bpind,], X[is.cc.bpind,]))
data.glind <- as.data.frame(cbind(Y.cc.glind, Z[is.cc.glind,], X[is.cc.glind,]))
data.trind <- as.data.frame(cbind(Y.cc.trind, Z[is.cc.trind,], X[is.cc.trind,]))
data.chind <- as.data.frame(cbind(Y.cc.chind, Z[is.cc.chind,], X[is.cc.chind,]))
data.metab <- as.data.frame(cbind(Y.cc.metab, Z[is.cc.metab,], X[is.cc.metab,]))
data.crpca <- as.data.frame(cbind(Y.cc.crpca, Z[is.cc.crpca,], X[is.cc.crpca,]))

```

### BKMR - CONTINUOUS OUTCOMES
```{r, BKMR - systolic BP}

# Fit BKMR
set.seed(111)
fitkm.novarsel.sys <- kmbayes(y = Y.cc.sys, Z = Z[is.cc.sys,], X = X[is.cc.sys,], iter = 10000, verbose = FALSE, varsel = FALSE) 

# Investigate model convergence
TracePlot(fit = fitkm.novarsel.sys, par = "beta")
TracePlot(fit = fitkm.novarsel.sys, par = "sigsq.eps")
TracePlot(fit = fitkm.novarsel.sys, par = "r", comp = 1)

# Summary statistics of predictor-response function
risks.overall.sys <- OverallRiskSummaries(fit = fitkm.novarsel.sys, y = Y.cc.sys, Z = Z[is.cc.sys,], X = X[is.cc.sys,],
                                      qs = seq(0.25, 0.75, by = 0.05), 
                                      q.fixed = 0.5, method = "exact")
risks.overall.sys

ggplot(risks.overall.sys, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
    geom_pointrange() +
    labs(
      x = "Joint quantile", 
      y = "Mean difference"
    )

# Summarize contribution of individual predictors to the response
risks.singvar.sys <- SingVarRiskSummaries(fit = fitkm.novarsel.sys, y = Y.cc.sys, Z = Z[is.cc.sys,], X = X[is.cc.sys,],
                                      qs.diff = c(0.25, 0.75), 
                                      q.fixed = c(0.50),
                                      method = "exact")
risks.singvar.sys

ggplot(risks.singvar.sys, aes(variable, est, ymin = est - 1.96*sd, 
                          ymax = est + 1.96*sd)) + 
    geom_pointrange(position = position_dodge(width = 0.75), color = "black") + 
    coord_flip() +
    labs(
      x = "Exposure",
      y = "Mean difference") +
    theme(legend.position = "none")
```

```{r, BKMR - diastolic BP}

# Fit BKMR
set.seed(111)
fitkm.novarsel.dia <- kmbayes(y = Y.cc.dia, Z = Z[is.cc.dia,], X = X[is.cc.dia,], iter = 10000, verbose = FALSE, varsel = FALSE) 

# Investigate model convergence
TracePlot(fit = fitkm.novarsel.dia, par = "beta")
TracePlot(fit = fitkm.novarsel.dia, par = "sigsq.eps")
TracePlot(fit = fitkm.novarsel.dia, par = "r", comp = 1)

# Summary statistics of predictor-response function
risks.overall.dia <- OverallRiskSummaries(fit = fitkm.novarsel.dia, y = Y.cc.dia, Z = Z[is.cc.dia,], X = X[is.cc.dia,],
                                      qs = seq(0.25, 0.75, by = 0.05), 
                                      q.fixed = 0.5, method = "exact")
risks.overall.dia

ggplot(risks.overall.dia, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
    geom_pointrange() +
    labs(
      x = "Joint quantile", 
      y = "Mean difference"
    )

# Summarize contribution of individual predictors to the response
risks.singvar.dia <- SingVarRiskSummaries(fit = fitkm.novarsel.dia, y = Y.cc.dia, Z = Z[is.cc.dia,], X = X[is.cc.dia,],
                                      qs.diff = c(0.25, 0.75), 
                                      q.fixed = c(0.50),
                                      method = "exact")
risks.singvar.dia

ggplot(risks.singvar.dia, aes(variable, est, ymin = est - 1.96*sd, 
                          ymax = est + 1.96*sd)) + 
    geom_pointrange(position = position_dodge(width = 0.75), color = "black") + 
    coord_flip() +
    labs(
      x = "Exposure",
      y = "Mean difference") +
    theme(legend.position = "none")
```

```{r, BKMR - pulse pressure}

# Fit BKMR
set.seed(111)
fitkm.novarsel.pul <- kmbayes(y = Y.cc.pul, Z = Z[is.cc.pul,], X = X[is.cc.pul,], iter = 10000, verbose = FALSE, varsel = FALSE) 

# Investigate model convergence
TracePlot(fit = fitkm.novarsel.pul, par = "beta")
TracePlot(fit = fitkm.novarsel.pul, par = "sigsq.eps")
TracePlot(fit = fitkm.novarsel.pul, par = "r", comp = 1)

# Summary statistics of predictor-response function
risks.overall.pul <- OverallRiskSummaries(fit = fitkm.novarsel.pul, y = Y.cc.pul, Z = Z[is.cc.pul,], X = X[is.cc.pul,],
                                      qs = seq(0.25, 0.75, by = 0.05), 
                                      q.fixed = 0.5, method = "exact")
risks.overall.pul

ggplot(risks.overall.pul, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
    geom_pointrange() +
    labs(
      x = "Joint quantile", 
      y = "Mean difference"
    )

# Summarize contribution of individual predictors to the response
risks.singvar.pul <- SingVarRiskSummaries(fit = fitkm.novarsel.pul, y = Y.cc.pul, Z = Z[is.cc.pul,], X = X[is.cc.pul,],
                                      qs.diff = c(0.25, 0.75), 
                                      q.fixed = c(0.50),
                                      method = "exact")
risks.singvar.pul

ggplot(risks.singvar.pul, aes(variable, est, ymin = est - 1.96*sd, 
                          ymax = est + 1.96*sd)) + 
    geom_pointrange(position = position_dodge(width = 0.75), color = "black") + 
    coord_flip() +
    labs(
      x = "Exposure",
      y = "Mean difference") +
    theme(legend.position = "none")
```

```{r, BKMR - MAP}

# Fit BKMR
set.seed(111)
fitkm.novarsel.map <- kmbayes(y = Y.cc.map, Z = Z[is.cc.map,], X = X[is.cc.map,], iter = 10000, verbose = FALSE, varsel = FALSE) 

# Investigate model convergence
TracePlot(fit = fitkm.novarsel.map, par = "beta")
TracePlot(fit = fitkm.novarsel.map, par = "sigsq.eps")
TracePlot(fit = fitkm.novarsel.map, par = "r", comp = 1)

# Summary statistics of predictor-response function
risks.overall.map <- OverallRiskSummaries(fit = fitkm.novarsel.map, y = Y.cc.map, Z = Z[is.cc.map,], X = X[is.cc.map,],
                                      qs = seq(0.25, 0.75, by = 0.05), 
                                      q.fixed = 0.5, method = "exact")
risks.overall.map

ggplot(risks.overall.map, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
    geom_pointrange() +
    labs(
      x = "Joint quantile", 
      y = "Mean difference"
    )

# Summarize contribution of individual predictors to the response
risks.singvar.map <- SingVarRiskSummaries(fit = fitkm.novarsel.map, y = Y.cc.map, Z = Z[is.cc.map,], X = X[is.cc.map,],
                                      qs.diff = c(0.25, 0.75), 
                                      q.fixed = c(0.50),
                                      method = "exact")
risks.singvar.map

ggplot(risks.singvar.map, aes(variable, est, ymin = est - 1.96*sd, 
                          ymax = est + 1.96*sd)) + 
    geom_pointrange(position = position_dodge(width = 0.75), color = "black") + 
    coord_flip() +
    labs(
      x = "Exposure",
      y = "Mean difference") +
    theme(legend.position = "none")
```

```{r, BKMR - triglycerides}

# Fit BKMR
set.seed(111)
fitkm.novarsel.tri <- kmbayes(y = Y.cc.tri, Z = Z[is.cc.tri,], X = X[is.cc.tri,], iter = 10000, verbose = FALSE, varsel = FALSE) 

# Investigate model convergence
TracePlot(fit = fitkm.novarsel.tri, par = "beta")
TracePlot(fit = fitkm.novarsel.tri, par = "sigsq.eps")
TracePlot(fit = fitkm.novarsel.tri, par = "r", comp = 1)

# Summary statistics of predictor-response function
risks.overall.tri <- OverallRiskSummaries(fit = fitkm.novarsel.tri, y = Y.cc.tri, Z = Z[is.cc.tri,], X = X[is.cc.tri,],
                                      qs = seq(0.25, 0.75, by = 0.05), 
                                      q.fixed = 0.5, method = "exact")
risks.overall.tri

ggplot(risks.overall.tri, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
    geom_pointrange() +
    labs(
      x = "Joint quantile", 
      y = "Mean difference"
    )

# Summarize contribution of individual predictors to the response
risks.singvar.tri <- SingVarRiskSummaries(fit = fitkm.novarsel.tri, y = Y.cc.tri, Z = Z[is.cc.tri,], X = X[is.cc.tri,],
                                      qs.diff = c(0.25, 0.75), 
                                      q.fixed = c(0.50),
                                      method = "exact")
risks.singvar.tri

ggplot(risks.singvar.tri, aes(variable, est, ymin = est - 1.96*sd, 
                          ymax = est + 1.96*sd)) + 
    geom_pointrange(position = position_dodge(width = 0.75), color = "black") + 
    coord_flip() +
    labs(
      x = "Exposure",
      y = "Mean difference") +
    theme(legend.position = "none")
```

```{r, BKMR - HDL cholesterol}

# Fit BKMR
set.seed(111)
fitkm.novarsel.hdl <- kmbayes(y = Y.cc.hdl, Z = Z[is.cc.hdl,], X = X[is.cc.hdl,], iter = 10000, verbose = FALSE, varsel = FALSE) 

# Investigate model convergence
TracePlot(fit = fitkm.novarsel.hdl, par = "beta")
TracePlot(fit = fitkm.novarsel.hdl, par = "sigsq.eps")
TracePlot(fit = fitkm.novarsel.hdl, par = "r", comp = 1)

# Summary statistics of predictor-response function
risks.overall.hdl <- OverallRiskSummaries(fit = fitkm.novarsel.hdl, y = Y.cc.hdl, Z = Z[is.cc.hdl,], X = X[is.cc.hdl,],
                                      qs = seq(0.25, 0.75, by = 0.05), 
                                      q.fixed = 0.5, method = "exact")
risks.overall.hdl

ggplot(risks.overall.hdl, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
    geom_pointrange() +
    labs(
      x = "Joint quantile", 
      y = "Mean difference"
    )

# Summarize contribution of individual predictors to the response
risks.singvar.hdl <- SingVarRiskSummaries(fit = fitkm.novarsel.hdl, y = Y.cc.hdl, Z = Z[is.cc.hdl,], X = X[is.cc.hdl,],
                                      qs.diff = c(0.25, 0.75), 
                                      q.fixed = c(0.50),
                                      method = "exact")
risks.singvar.hdl

ggplot(risks.singvar.hdl, aes(variable, est, ymin = est - 1.96*sd, 
                          ymax = est + 1.96*sd)) + 
    geom_pointrange(position = position_dodge(width = 0.75), color = "black") + 
    coord_flip() +
    labs(
      x = "Exposure",
      y = "Mean difference") +
    theme(legend.position = "none")
```

```{r, BKMR - glucose}

# Fit BKMR
set.seed(111)
fitkm.novarsel.glu <- kmbayes(y = Y.cc.glu, Z = Z[is.cc.glu,], X = X[is.cc.glu,], iter = 10000, verbose = FALSE, varsel = FALSE) 

# Investigate model convergence
TracePlot(fit = fitkm.novarsel.glu, par = "beta")
TracePlot(fit = fitkm.novarsel.glu, par = "sigsq.eps")
TracePlot(fit = fitkm.novarsel.glu, par = "r", comp = 1)

# Summary statistics of predictor-response function
risks.overall.glu <- OverallRiskSummaries(fit = fitkm.novarsel.glu, y = Y.cc.glu, Z = Z[is.cc.glu,], X = X[is.cc.glu,],
                                      qs = seq(0.25, 0.75, by = 0.05), 
                                      q.fixed = 0.5, method = "exact")
risks.overall.glu

ggplot(risks.overall.glu, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
    geom_pointrange() +
    labs(
      x = "Joint quantile", 
      y = "Mean difference"
    )

# Summarize contribution of individual predictors to the response
risks.singvar.glu <- SingVarRiskSummaries(fit = fitkm.novarsel.glu, y = Y.cc.glu, Z = Z[is.cc.glu,], X = X[is.cc.glu,],
                                      qs.diff = c(0.25, 0.75), 
                                      q.fixed = c(0.50),
                                      method = "exact")
risks.singvar.glu

ggplot(risks.singvar.glu, aes(variable, est, ymin = est - 1.96*sd, 
                          ymax = est + 1.96*sd)) + 
    geom_pointrange(position = position_dodge(width = 0.75), color = "black") + 
    coord_flip() +
    labs(
      x = "Exposure",
      y = "Mean difference") +
    theme(legend.position = "none")
```

```{r, BKMR - HbA1c}

# Fit BKMR
set.seed(111)
fitkm.novarsel.hba <- kmbayes(y = Y.cc.hba, Z = Z[is.cc.hba,], X = X[is.cc.hba,], iter = 10000, verbose = FALSE, varsel = FALSE) 

# Investigate model convergence
TracePlot(fit = fitkm.novarsel.hba, par = "beta")
TracePlot(fit = fitkm.novarsel.hba, par = "sigsq.eps")
TracePlot(fit = fitkm.novarsel.hba, par = "r", comp = 1)

# Summary statistics of predictor-response function
risks.overall.hba <- OverallRiskSummaries(fit = fitkm.novarsel.hba, y = Y.cc.hba, Z = Z[is.cc.hba,], X = X[is.cc.hba,],
                                      qs = seq(0.25, 0.75, by = 0.05), 
                                      q.fixed = 0.5, method = "exact")
risks.overall.hba

ggplot(risks.overall.hba, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
    geom_pointrange() +
    labs(
      x = "Joint quantile", 
      y = "Mean difference"
    )

# Summarize contribution of individual predictors to the response
risks.singvar.hba <- SingVarRiskSummaries(fit = fitkm.novarsel.hba, y = Y.cc.hba, Z = Z[is.cc.hba,], X = X[is.cc.hba,],
                                      qs.diff = c(0.25, 0.75), 
                                      q.fixed = c(0.50),
                                      method = "exact")
risks.singvar.hba

ggplot(risks.singvar.hba, aes(variable, est, ymin = est - 1.96*sd, 
                          ymax = est + 1.96*sd)) + 
    geom_pointrange(position = position_dodge(width = 0.75), color = "black") + 
    coord_flip() +
    labs(
      x = "Exposure",
      y = "Mean difference") +
    theme(legend.position = "none")
```

```{r, BKMR - BMI}

# Fit BKMR
set.seed(111)
fitkm.novarsel.bmi <- kmbayes(y = Y.cc.bmi, Z = Z[is.cc.bmi,], X = X[is.cc.bmi,], iter = 10000, verbose = FALSE, varsel = FALSE) 

# Investigate model convergence
TracePlot(fit = fitkm.novarsel.bmi, par = "beta")
TracePlot(fit = fitkm.novarsel.bmi, par = "sigsq.eps")
TracePlot(fit = fitkm.novarsel.bmi, par = "r", comp = 1)

# Summary statistics of predictor-response function
risks.overall.bmi <- OverallRiskSummaries(fit = fitkm.novarsel.bmi, y = Y.cc.bmi, Z = Z[is.cc.bmi,], X = X[is.cc.bmi,],
                                      qs = seq(0.25, 0.75, by = 0.05), 
                                      q.fixed = 0.5, method = "exact")
risks.overall.bmi

ggplot(risks.overall.bmi, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
    geom_pointrange() +
    labs(
      x = "Joint quantile", 
      y = "Mean difference"
    )

# Summarize contribution of individual predictors to the response
risks.singvar.bmi <- SingVarRiskSummaries(fit = fitkm.novarsel.bmi, y = Y.cc.bmi, Z = Z[is.cc.bmi,], X = X[is.cc.bmi,],
                                      qs.diff = c(0.25, 0.75), 
                                      q.fixed = c(0.50),
                                      method = "exact")
risks.singvar.bmi

ggplot(risks.singvar.bmi, aes(variable, est, ymin = est - 1.96*sd, 
                          ymax = est + 1.96*sd)) + 
    geom_pointrange(position = position_dodge(width = 0.75), color = "black") + 
    coord_flip() +
    labs(
      x = "Exposure",
      y = "Mean difference") +
    theme(legend.position = "none")
```

```{r, BKMR - waist circumference}

# Fit BKMR
set.seed(111)
fitkm.novarsel.wai <- kmbayes(y = Y.cc.wai, Z = Z[is.cc.wai,], X = X[is.cc.wai,], iter = 10000, verbose = FALSE, varsel = FALSE) 

# Investigate model convergence
TracePlot(fit = fitkm.novarsel.wai, par = "beta")
TracePlot(fit = fitkm.novarsel.wai, par = "sigsq.eps")
TracePlot(fit = fitkm.novarsel.wai, par = "r", comp = 1)

# Summary statistics of predictor-response function
risks.overall.wai <- OverallRiskSummaries(fit = fitkm.novarsel.wai, y = Y.cc.wai, Z = Z[is.cc.wai,], X = X[is.cc.wai,],
                                      qs = seq(0.25, 0.75, by = 0.05), 
                                      q.fixed = 0.5, method = "exact")
risks.overall.wai

ggplot(risks.overall.wai, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
    geom_pointrange() +
    labs(
      x = "Joint quantile", 
      y = "Mean difference"
    )

# Summarize contribution of individual predictors to the response
risks.singvar.wai <- SingVarRiskSummaries(fit = fitkm.novarsel.wai, y = Y.cc.wai, Z = Z[is.cc.wai,], X = X[is.cc.wai,],
                                      qs.diff = c(0.25, 0.75), 
                                      q.fixed = c(0.50),
                                      method = "exact")
risks.singvar.wai

ggplot(risks.singvar.wai, aes(variable, est, ymin = est - 1.96*sd, 
                          ymax = est + 1.96*sd)) + 
    geom_pointrange(position = position_dodge(width = 0.75), color = "black") + 
    coord_flip() +
    labs(
      x = "Exposure",
      y = "Mean difference") +
    theme(legend.position = "none")
```

```{r, BKMR - hs-CRP}

# Fit BKMR
set.seed(111)
fitkm.novarsel.crp <- kmbayes(y = Y.cc.crp, Z = Z[is.cc.crp,], X = X[is.cc.crp,], iter = 10000, verbose = FALSE, varsel = FALSE) 

# Investigate model convergence
TracePlot(fit = fitkm.novarsel.crp, par = "beta")
TracePlot(fit = fitkm.novarsel.crp, par = "sigsq.eps")
TracePlot(fit = fitkm.novarsel.crp, par = "r", comp = 1)

# Summary statistics of predictor-response function
risks.overall.crp <- OverallRiskSummaries(fit = fitkm.novarsel.crp, y = Y.cc.crp, Z = Z[is.cc.crp,], X = X[is.cc.crp,],
                                      qs = seq(0.25, 0.75, by = 0.05), 
                                      q.fixed = 0.5, method = "exact")
risks.overall.crp

ggplot(risks.overall.crp, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
    geom_pointrange() +
    labs(
      x = "Joint quantile", 
      y = "Mean difference"
    )

# Summarize contribution of individual predictors to the response
risks.singvar.crp <- SingVarRiskSummaries(fit = fitkm.novarsel.crp, y = Y.cc.crp, Z = Z[is.cc.crp,], X = X[is.cc.crp,],
                                      qs.diff = c(0.25, 0.75), 
                                      q.fixed = c(0.50),
                                      method = "exact")
risks.singvar.crp

ggplot(risks.singvar.crp, aes(variable, est, ymin = est - 1.96*sd, 
                          ymax = est + 1.96*sd)) + 
    geom_pointrange(position = position_dodge(width = 0.75), color = "black") + 
    coord_flip() +
    labs(
      x = "Exposure",
      y = "Mean difference") +
    theme(legend.position = "none")
```

```{r, BKMR - IL-6}

# Fit BKMR
set.seed(111)
fitkm.novarsel.il6 <- kmbayes(y = Y.cc.il6, Z = Z[is.cc.il6,], X = X[is.cc.il6,], iter = 10000, verbose = FALSE, varsel = FALSE) 

# Investigate model convergence
TracePlot(fit = fitkm.novarsel.il6, par = "beta")
TracePlot(fit = fitkm.novarsel.il6, par = "sigsq.eps")
TracePlot(fit = fitkm.novarsel.il6, par = "r", comp = 1)

# Summary statistics of predictor-response function
risks.overall.il6 <- OverallRiskSummaries(fit = fitkm.novarsel.il6, y = Y.cc.il6, Z = Z[is.cc.il6,], X = X[is.cc.il6,],
                                      qs = seq(0.25, 0.75, by = 0.05), 
                                      q.fixed = 0.5, method = "exact")
risks.overall.il6

ggplot(risks.overall.il6, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
    geom_pointrange() +
    labs(
      x = "Joint quantile", 
      y = "Mean difference"
    )

# Summarize contribution of individual predictors to the response
risks.singvar.il6 <- SingVarRiskSummaries(fit = fitkm.novarsel.il6, y = Y.cc.il6, Z = Z[is.cc.il6,], X = X[is.cc.il6,],
                                      qs.diff = c(0.25, 0.75), 
                                      q.fixed = c(0.50),
                                      method = "exact")
risks.singvar.il6

ggplot(risks.singvar.il6, aes(variable, est, ymin = est - 1.96*sd, 
                          ymax = est + 1.96*sd)) + 
    geom_pointrange(position = position_dodge(width = 0.75), color = "black") + 
    coord_flip() +
    labs(
      x = "Exposure",
      y = "Mean difference") +
    theme(legend.position = "none")
```
