---
title: "pest_cmd_bkmr_novarsel_binary_v3.Rmd"
author: "LCalderon"
output: html_document
date: "2025-12-09"
---

### SET UP DATA
```{r, load and setup data}
# Clear workspace
rm(list=ls())

# Set working directory
setwd("/Users/lcalderon1/Library/CloudStorage/Box-Box/CHAM Maternal Cognition Study/Analyses and Manuscripts/Lucia's analyses/CHAM PUR Cardiometabolic/Analysis 2")
#setwd("C:/Users/lucia/Box/CHAM Maternal Cognition Study/Analyses and Manuscripts/Lucia's analyses/CHAM PUR Cardiometabolic/Analysis 2/")

library(tableone)
library(fastDummies)
library(coda)
library(dplyr)
library(haven)
library(multcomp)
library(ggplot2)
library(qgcomp)
library(qgcompint)
library(gfoRmula)
library(broom)
library(boot)
library(bkmr)
library(tidyr)
library(tibble)

# Read in Data from Stata (this dataset only includes the analytic sample)
data<-read_dta("pest_cmd_analysis_v6.dta") 

# Drop outliers for continuous outcomes
#data$mbmi_mc1[data$mbmi_mc1_out==1]<-NA
#data$mwaist_mc1[data$mwaist_mc1_out==1]<-NA
#data$mbpsys_mc1[data$mbpsys_mc1_out==1]<-NA
#data$mbpdia_mc1[data$mbpdia_mc1_out==1]<-NA
#data$mbppul_mc1[data$mbppul_mc1_out==1]<-NA
#data$mbpmap_mc1[data$mbpmap_mc1_out==1]<-NA
#data$gluc_mc1[data$gluc_mc1_out==1]<-NA
#data$hba1c_mc1[data$hba1c_mc1_out==1]<-NA
#data$log_trig_mc1[data$log_trig_mc1_out==1]<-NA
#data$hdl_mc1[data$hdl_mc1_out==1]<-NA
#data$log_crp_mc1[data$log_crp_mc1_out==1]<-NA
#data$log_il6_mc1[data$log_il6_mc1_out==1]<-NA

# Exclude those taking meds from relevant continuous outcomes
data$mbpsys_mc1[data$mbpsys_mc1_med==1]<-NA
data$mbpdia_mc1[data$mbpdia_mc1_med==1]<-NA
data$mbppul_mc1[data$mbppul_mc1_med==1]<-NA
data$mbpmap_mc1[data$mbpmap_mc1_med==1]<-NA
data$gluc_mc1[data$gluc_mc1_med==1]<-NA
data$hba1c_mc1[data$hba1c_mc1_med==1]<-NA
data$log_trig_mc1[data$log_trig_mc1_med==1]<-NA
data$hdl_mc1[data$hdl_mc1_med==1]<-NA

# Exclude non-fasting glucose
#data$gluc_mc1[data$gluc_mc1_nf==1]<-NA

# Table 1 to check consistency with Stata analysis 
myvars<- c("age_dl","ageusa_cat_bl","meducat_bl","imarcat_10_5y","iagwork_10_5y","i2_povcat2_10_5y",
           "mhtn_mc1","diabetes_mc1","mobese_mc1","waist_ind_mc1","bp_ind_mc1","gluc_ind_mc1","trig_ind_mc1","chdl_ind_mc1","metsyn_mc1","crp_cat_mc1",
           "mbpsys_mc1","mbpdia_mc1","mbppul_mc1","mbpmap_mc1","mbmi_mc1","mwaist_mc1","gluc_mc1","hba1c_mc1","log_trig_mc1","hdl_mc1","log_crp_mc1","log_il6_mc1")
mycatvars<-c("ageusa_cat_bl","meducat_bl","imarcat_10_5y","iagwork_10_5y","i2_povcat2_10_5y",
             "mhtn_mc1","diabetes_mc1","mobese_mc1","waist_ind_mc1","bp_ind_mc1","gluc_ind_mc1","trig_ind_mc1","chdl_ind_mc1","metsyn_mc1","crp_cat_mc1")
table1<-CreateTableOne(vars=myvars, data=data, factorVars=mycatvars)
tab1print<-print(table1, showAlllevels=T, catDigits=1, contDigits=1, pDigits=1, test=F, printToggle = FALSE)

#Subset out relevant covariates
data<-dummy_cols(data, select_columns = c("ageusa_cat_bl","meducat_bl","iagwork_10_5y"), 
                 remove_first_dummy = TRUE, remove_selected_columns = FALSE, 
                 remove_most_frequent_dummy = FALSE, ignore_na = FALSE)
X <- subset(data, select = c("age_dl","ageusa_cat_bl_2","ageusa_cat_bl_3","meducat_bl_2","meducat_bl_3",
                             "imarcat_10_5y","iagwork_10_5y_2","iagwork_10_5y_3","i2_povcat2_10_5y"))
X<-as.matrix(X)

#Exposures
Z<- subset(data, select = c("op",
                            "pyr",
                            "carb",
                            "neo",
                            "mn",
                            "gly",
                            "paraq"))

Z <- as.matrix(Z)
Z <- scale(Z) ## This is essential for BKMR

##Vectorize individual outcomes of interest from Y
Y_sys<-as.vector(data$mbpsys_mc1)
Y_dia<-as.vector(data$mbpdia_mc1)
Y_pul<-as.vector(data$mbppul_mc1)
Y_map<-as.vector(data$mbpmap_mc1)
Y_bmi<-as.vector(data$mbmi_mc1)
Y_wai<-as.vector(data$mwaist_mc1)
Y_glu<-as.vector(data$gluc_mc1)
Y_hba<-as.vector(data$hba1c_mc1)
Y_tri<-as.vector(data$log_trig_mc1)
Y_hdl<-as.vector(data$hdl_mc1)
Y_crp<-as.vector(data$log_crp_mc1)
Y_il6<-as.vector(data$log_il6_mc1)

Y_hyper<-as.vector(data$mhtn_mc1)
Y_diabe<-as.vector(data$diabetes_mc1)
Y_obese<-as.vector(data$mobese_mc1)
Y_waind<-as.vector(data$waist_ind_mc1)
Y_bpind<-as.vector(data$bp_ind_mc1)
Y_glind<-as.vector(data$gluc_ind_mc1)
Y_trind<-as.vector(data$trig_ind_mc1)
Y_chind<-as.vector(data$chdl_ind_mc1)
Y_metab<-as.vector(data$metsyn_mc1)
Y_crpca<-as.vector(data$crp_cat_mc1)

##Complete Case Flag for each Outcome
is.cc.sys <- complete.cases(cbind(X,Z,Y_sys))
is.cc.dia <- complete.cases(cbind(X,Z,Y_dia))
is.cc.pul <- complete.cases(cbind(X,Z,Y_pul))
is.cc.map <- complete.cases(cbind(X,Z,Y_map))
is.cc.bmi <- complete.cases(cbind(X,Z,Y_bmi))
is.cc.wai <- complete.cases(cbind(X,Z,Y_wai))
is.cc.glu <- complete.cases(cbind(X,Z,Y_glu))
is.cc.hba <- complete.cases(cbind(X,Z,Y_hba))
is.cc.tri <- complete.cases(cbind(X,Z,Y_tri))
is.cc.hdl <- complete.cases(cbind(X,Z,Y_hdl))
is.cc.crp <- complete.cases(cbind(X,Z,Y_crp))
is.cc.il6 <- complete.cases(cbind(X,Z,Y_il6))

is.cc.hyper <- complete.cases(cbind(X,Z,Y_hyper))
is.cc.diabe <- complete.cases(cbind(X,Z,Y_diabe))
is.cc.obese <- complete.cases(cbind(X,Z,Y_obese))
is.cc.waind <- complete.cases(cbind(X,Z,Y_waind))
is.cc.bpind <- complete.cases(cbind(X,Z,Y_bpind))
is.cc.glind <- complete.cases(cbind(X,Z,Y_glind))
is.cc.trind <- complete.cases(cbind(X,Z,Y_trind))
is.cc.chind <- complete.cases(cbind(X,Z,Y_chind))
is.cc.metab <- complete.cases(cbind(X,Z,Y_metab))
is.cc.crpca <- complete.cases(cbind(X,Z,Y_crpca))

##Subset outcomes as complete cases
Y.cc.sys <- subset(Y_sys,is.cc.sys) 
Y.cc.dia <- subset(Y_dia,is.cc.dia) 
Y.cc.pul <- subset(Y_pul,is.cc.pul) 
Y.cc.map <- subset(Y_map,is.cc.map) 
Y.cc.bmi <- subset(Y_bmi,is.cc.bmi)
Y.cc.wai <- subset(Y_wai,is.cc.wai)
Y.cc.glu <- subset(Y_glu,is.cc.glu)
Y.cc.hba <- subset(Y_hba,is.cc.hba)
Y.cc.tri <- subset(Y_tri,is.cc.tri)
Y.cc.hdl <- subset(Y_hdl,is.cc.hdl)
Y.cc.crp <- subset(Y_crp,is.cc.crp)
Y.cc.il6 <- subset(Y_il6,is.cc.il6)

Y.cc.hyper <- subset(Y_hyper,is.cc.hyper)
Y.cc.diabe <- subset(Y_diabe,is.cc.diabe)
Y.cc.obese <- subset(Y_obese,is.cc.obese)
Y.cc.waind <- subset(Y_waind,is.cc.waind)
Y.cc.bpind <- subset(Y_bpind,is.cc.bpind)
Y.cc.glind <- subset(Y_glind,is.cc.glind)
Y.cc.trind <- subset(Y_trind,is.cc.trind)
Y.cc.chind <- subset(Y_chind,is.cc.chind)
Y.cc.metab <- subset(Y_metab,is.cc.metab)
Y.cc.crpca <- subset(Y_crpca,is.cc.crpca)

# Set up data frames for regression models
data.sys <- as.data.frame(cbind(Y.cc.sys, Z[is.cc.sys,], X[is.cc.sys,]))
data.dia <- as.data.frame(cbind(Y.cc.dia, Z[is.cc.dia,], X[is.cc.dia,]))
data.pul <- as.data.frame(cbind(Y.cc.pul, Z[is.cc.pul,], X[is.cc.pul,]))
data.map <- as.data.frame(cbind(Y.cc.map, Z[is.cc.map,], X[is.cc.map,]))
data.bmi <- as.data.frame(cbind(Y.cc.bmi, Z[is.cc.bmi,], X[is.cc.bmi,]))
data.wai <- as.data.frame(cbind(Y.cc.wai, Z[is.cc.wai,], X[is.cc.wai,]))
data.glu <- as.data.frame(cbind(Y.cc.glu, Z[is.cc.glu,], X[is.cc.glu,]))
data.hba <- as.data.frame(cbind(Y.cc.hba, Z[is.cc.hba,], X[is.cc.hba,]))
data.tri <- as.data.frame(cbind(Y.cc.tri, Z[is.cc.tri,], X[is.cc.tri,]))
data.hdl <- as.data.frame(cbind(Y.cc.hdl, Z[is.cc.hdl,], X[is.cc.hdl,]))
data.crp <- as.data.frame(cbind(Y.cc.crp, Z[is.cc.crp,], X[is.cc.crp,]))
data.il6 <- as.data.frame(cbind(Y.cc.il6, Z[is.cc.il6,], X[is.cc.il6,]))

data.hyper <- as.data.frame(cbind(Y.cc.hyper, Z[is.cc.hyper,], X[is.cc.hyper,]))
data.diabe <- as.data.frame(cbind(Y.cc.diabe, Z[is.cc.diabe,], X[is.cc.diabe,]))
data.obese <- as.data.frame(cbind(Y.cc.obese, Z[is.cc.obese,], X[is.cc.obese,]))
data.waind <- as.data.frame(cbind(Y.cc.waind, Z[is.cc.waind,], X[is.cc.waind,]))
data.bpind <- as.data.frame(cbind(Y.cc.bpind, Z[is.cc.bpind,], X[is.cc.bpind,]))
data.glind <- as.data.frame(cbind(Y.cc.glind, Z[is.cc.glind,], X[is.cc.glind,]))
data.trind <- as.data.frame(cbind(Y.cc.trind, Z[is.cc.trind,], X[is.cc.trind,]))
data.chind <- as.data.frame(cbind(Y.cc.chind, Z[is.cc.chind,], X[is.cc.chind,]))
data.metab <- as.data.frame(cbind(Y.cc.metab, Z[is.cc.metab,], X[is.cc.metab,]))
data.crpca <- as.data.frame(cbind(Y.cc.crpca, Z[is.cc.crpca,], X[is.cc.crpca,]))

```

### BKMR - BINARY OUTCOMES
```{r, set up functions for marginal estimates and CrIs}

# Generate posterior probabilities and marginalize
get_marginal_probs <- function(Znew, Xvals, fit, thin = 10, n_iter = 10000) {
    # Create the sequence of posterior draws to use
    draws_to_use <- seq(1, n_iter, by = thin)
    n_subj <- nrow(Xvals)
    probs_mat <- matrix(NA, nrow = length(draws_to_use), ncol = n_subj)
    # Loop over subjects
    for (i in 1:n_subj) {
      probs_mat[, i] <- SamplePred(
        fit = fit,
        Znew = Znew,
        Xnew = matrix(Xvals[i, ], nrow = 1),
        type = "response",
        iter = draws_to_use
      )
    }
    # Average over subjects for marginal probability per posterior draw
    rowMeans(probs_mat)
}

# 95% CrIs
  summarize <- function(x) {
    qs <- unname(quantile(x, c(0.025, 0.975)))
    c(mean = mean(x), l95 = qs[1], u95 = qs[2])
  }
```

```{r, BKMR - binary outcomes - hypertension - no variable selection}

# Fit BKMR
set.seed(111)
fitkm.novarsel.hyper <- kmbayes(y = Y.cc.hyper, Z = Z[is.cc.hyper,], X = X[is.cc.hyper,], iter = 10000, verbose = FALSE, varsel = FALSE, family = "binomial") 

# Investigate model convergence
TracePlot(fit = fitkm.novarsel.hyper, par = "beta")
TracePlot(fit = fitkm.novarsel.hyper, par = "r", comp = 1)

# Probability scale for RR and RD (adapting Bobb vignette https://jenfb.github.io/bkmr/ProbitEx.html)

  # Exposure quantiles
  Z25.hyper <- matrix(apply(Z[is.cc.hyper, ], 2, quantile, 0.25), nrow = 1)
  Z50.hyper <- matrix(apply(Z[is.cc.hyper, ], 2, quantile, 0.50), nrow = 1)
  Z75.hyper <- matrix(apply(Z[is.cc.hyper, ], 2, quantile, 0.75), nrow = 1)
  
  # Sample covars from their empirical distribution for marginal estimates
  Xvals.hyper <- X[is.cc.hyper, , drop = FALSE] 

  # Generate posterior probabilities and marginalize
  set.seed(111) 
  p25draws.hyper <- get_marginal_probs(Z25.hyper, Xvals.hyper, fitkm.novarsel.hyper, thin=10)
  p50draws.hyper <- get_marginal_probs(Z50.hyper, Xvals.hyper, fitkm.novarsel.hyper, thin=10)
  p75draws.hyper <- get_marginal_probs(Z75.hyper, Xvals.hyper, fitkm.novarsel.hyper, thin=10)

  # Compute RDs and RRs
  RD25to50.hyper <- p50draws.hyper - p25draws.hyper
  RD50to75.hyper <- p75draws.hyper - p50draws.hyper
  
  RR25to50.hyper <- p50draws.hyper / p25draws.hyper
  RR50to75.hyper <- p75draws.hyper / p50draws.hyper
  
  # Get 95% CIs
  results.hyper <- data.frame(
    Contrast = c("25->50", "50->75"),
    RDmean.hyper = c(summarize(RD25to50.hyper)["mean"], summarize(RD50to75.hyper)["mean"]),
    RDl95.hyper  = c(summarize(RD25to50.hyper)["l95"],  summarize(RD50to75.hyper)["l95"]),
    RDu95.hyper  = c(summarize(RD25to50.hyper)["u95"],  summarize(RD50to75.hyper)["u95"]),
    RRmean.hyper = c(summarize(RR25to50.hyper)["mean"], summarize(RR50to75.hyper)["mean"]),
    RRl95.hyper  = c(summarize(RR25to50.hyper)["l95"],  summarize(RR50to75.hyper)["l95"]),
    RRu95.hyper  = c(summarize(RR25to50.hyper)["u95"],  summarize(RR50to75.hyper)["u95"])
  )
  
  results.hyper
  
# Summarize predictor-response function (probit scale)
risks.overall.hyper <- OverallRiskSummaries(fit = fitkm.novarsel.hyper, y = Y.cc.hyper, Z = Z[is.cc.hyper,], X = X[is.cc.hyper,],
                                      qs = seq(0.25, 0.75, by = 0.05), 
                                      q.fixed = 0.5, method = "exact")
risks.overall.hyper

ggplot(risks.overall.hyper, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
    geom_pointrange() +
    labs(
      x = "Joint quantile", 
      y = "Mean difference"
    )

# Summarize contribution of individual predictors to the response (exploratory - probit)
risks.singvar.hyper <- SingVarRiskSummaries(fit = fitkm.novarsel.hyper, y = Y.cc.hyper, Z = Z[is.cc.hyper,], X = X[is.cc.hyper,],
                                      qs.diff = c(0.25, 0.75), 
                                      q.fixed = c(0.50),
                                      method = "exact")
risks.singvar.hyper

ggplot(risks.singvar.hyper, aes(variable, est, ymin = est - 1.96*sd, 
                          ymax = est + 1.96*sd)) + 
    geom_pointrange(position = position_dodge(width = 0.75), color = "black") + 
    coord_flip() +
    labs(
      x = "Exposure",
      y = "Mean difference") +
    theme(legend.position = "none")

```

```{r, BKMR - binary outcomes - diabetes - no variable selection}

# Fit BKMR
set.seed(111)
fitkm.novarsel.diabe <- kmbayes(y = Y.cc.diabe, Z = Z[is.cc.diabe,], X = X[is.cc.diabe,], iter = 10000, verbose = FALSE, varsel = FALSE, family = "binomial") 

# Investigate model convergence
TracePlot(fit = fitkm.novarsel.diabe, par = "beta")
TracePlot(fit = fitkm.novarsel.diabe, par = "r", comp = 1)

# Probability scale for RR and RD (adapting Bobb vignette https://jenfb.github.io/bkmr/ProbitEx.html)

  # Exposure quantiles
  Z25.diabe <- matrix(apply(Z[is.cc.diabe, ], 2, quantile, 0.25), nrow = 1)
  Z50.diabe <- matrix(apply(Z[is.cc.diabe, ], 2, quantile, 0.50), nrow = 1)
  Z75.diabe <- matrix(apply(Z[is.cc.diabe, ], 2, quantile, 0.75), nrow = 1)
  
  # Sample covars from their empirical distribution for marginal estimates
  Xvals.diabe <- X[is.cc.diabe, , drop = FALSE] 

  # Generate posterior probabilities and marginalize
  set.seed(111) 
  p25draws.diabe <- get_marginal_probs(Z25.diabe, Xvals.diabe, fitkm.novarsel.diabe, thin=10)
  p50draws.diabe <- get_marginal_probs(Z50.diabe, Xvals.diabe, fitkm.novarsel.diabe, thin=10)
  p75draws.diabe <- get_marginal_probs(Z75.diabe, Xvals.diabe, fitkm.novarsel.diabe, thin=10)

  # Compute RDs and RRs
  RD25to50.diabe <- p50draws.diabe - p25draws.diabe
  RD50to75.diabe <- p75draws.diabe - p50draws.diabe
  
  RR25to50.diabe <- p50draws.diabe / p25draws.diabe
  RR50to75.diabe <- p75draws.diabe / p50draws.diabe
  
  # Get 95% CIs
  results.diabe <- data.frame(
    Contrast = c("25->50", "50->75"),
    RDmean.diabe = c(summarize(RD25to50.diabe)["mean"], summarize(RD50to75.diabe)["mean"]),
    RDl95.diabe  = c(summarize(RD25to50.diabe)["l95"],  summarize(RD50to75.diabe)["l95"]),
    RDu95.diabe  = c(summarize(RD25to50.diabe)["u95"],  summarize(RD50to75.diabe)["u95"]),
    RRmean.diabe = c(summarize(RR25to50.diabe)["mean"], summarize(RR50to75.diabe)["mean"]),
    RRl95.diabe  = c(summarize(RR25to50.diabe)["l95"],  summarize(RR50to75.diabe)["l95"]),
    RRu95.diabe  = c(summarize(RR25to50.diabe)["u95"],  summarize(RR50to75.diabe)["u95"])
  )
  
  results.diabe

# Summarize predictor-response function (probit scale)
risks.overall.diabe <- OverallRiskSummaries(fit = fitkm.novarsel.diabe, y = Y.cc.diabe, Z = Z[is.cc.diabe,], X = X[is.cc.diabe,],
                                      qs = seq(0.25, 0.75, by = 0.05), 
                                      q.fixed = 0.5, method = "exact")
risks.overall.diabe

ggplot(risks.overall.diabe, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
    geom_pointrange() +
    labs(
      x = "Joint quantile", 
      y = "Mean difference"
    )

# Summarize contribution of individual predictors to the response (exploratory - probit)
risks.singvar.diabe <- SingVarRiskSummaries(fit = fitkm.novarsel.diabe, y = Y.cc.diabe, Z = Z[is.cc.diabe,], X = X[is.cc.diabe,],
                                      qs.diff = c(0.25, 0.75), 
                                      q.fixed = c(0.50),
                                      method = "exact")
risks.singvar.diabe

ggplot(risks.singvar.diabe, aes(variable, est, ymin = est - 1.96*sd, 
                          ymax = est + 1.96*sd)) + 
    geom_pointrange(position = position_dodge(width = 0.75), color = "black") + 
    coord_flip() +
    labs(
      x = "Exposure",
      y = "Mean difference") +
    theme(legend.position = "none")

```

```{r, BKMR - binary outcomes - obesity - no variable selection}

# Fit BKMR
set.seed(111)
fitkm.novarsel.obese <- kmbayes(y = Y.cc.obese, Z = Z[is.cc.obese,], X = X[is.cc.obese,], iter = 10000, verbose = FALSE, varsel = FALSE, family = "binomial") 

# Investigate model convergence
TracePlot(fit = fitkm.novarsel.obese, par = "beta")
TracePlot(fit = fitkm.novarsel.obese, par = "r", comp = 1)

# Probability scale for RR and RD (adapting Bobb vignette https://jenfb.github.io/bkmr/ProbitEx.html)

  # Exposure quantiles
  Z25.obese <- matrix(apply(Z[is.cc.obese, ], 2, quantile, 0.25), nrow = 1)
  Z50.obese <- matrix(apply(Z[is.cc.obese, ], 2, quantile, 0.50), nrow = 1)
  Z75.obese <- matrix(apply(Z[is.cc.obese, ], 2, quantile, 0.75), nrow = 1)
  
  # Sample covars from their empirical distribution for marginal estimates
  Xvals.obese <- X[is.cc.obese, , drop = FALSE] 

  # Generate posterior probabilities and marginalize
  set.seed(111) 
  p25draws.obese <- get_marginal_probs(Z25.obese, Xvals.obese, fitkm.novarsel.obese, thin=10)
  p50draws.obese <- get_marginal_probs(Z50.obese, Xvals.obese, fitkm.novarsel.obese, thin=10)
  p75draws.obese <- get_marginal_probs(Z75.obese, Xvals.obese, fitkm.novarsel.obese, thin=10)

  # Compute RDs and RRs
  RD25to50.obese <- p50draws.obese - p25draws.obese
  RD50to75.obese <- p75draws.obese - p50draws.obese
  
  RR25to50.obese <- p50draws.obese / p25draws.obese
  RR50to75.obese <- p75draws.obese / p50draws.obese
  
  # Get 95% CIs
  results.obese <- data.frame(
    Contrast = c("25->50", "50->75"),
    RDmean.obese = c(summarize(RD25to50.obese)["mean"], summarize(RD50to75.obese)["mean"]),
    RDl95.obese  = c(summarize(RD25to50.obese)["l95"],  summarize(RD50to75.obese)["l95"]),
    RDu95.obese  = c(summarize(RD25to50.obese)["u95"],  summarize(RD50to75.obese)["u95"]),
    RRmean.obese = c(summarize(RR25to50.obese)["mean"], summarize(RR50to75.obese)["mean"]),
    RRl95.obese  = c(summarize(RR25to50.obese)["l95"],  summarize(RR50to75.obese)["l95"]),
    RRu95.obese  = c(summarize(RR25to50.obese)["u95"],  summarize(RR50to75.obese)["u95"])
  )
  
  results.obese

# Summarize predictor-response function (probit scale)
risks.overall.obese <- OverallRiskSummaries(fit = fitkm.novarsel.obese, y = Y.cc.obese, Z = Z[is.cc.obese,], X = X[is.cc.obese,],
                                      qs = seq(0.25, 0.75, by = 0.05), 
                                      q.fixed = 0.5, method = "exact")
risks.overall.obese

ggplot(risks.overall.obese, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
    geom_pointrange() +
    labs(
      x = "Joint quantile", 
      y = "Mean difference"
    )

# Summarize contribution of individual predictors to the response (exploratory - probit)
risks.singvar.obese <- SingVarRiskSummaries(fit = fitkm.novarsel.obese, y = Y.cc.obese, Z = Z[is.cc.obese,], X = X[is.cc.obese,],
                                      qs.diff = c(0.25, 0.75), 
                                      q.fixed = c(0.50),
                                      method = "exact")
risks.singvar.obese

ggplot(risks.singvar.obese, aes(variable, est, ymin = est - 1.96*sd, 
                          ymax = est + 1.96*sd)) + 
    geom_pointrange(position = position_dodge(width = 0.75), color = "black") + 
    coord_flip() +
    labs(
      x = "Exposure",
      y = "Mean difference") +
    theme(legend.position = "none")

```

```{r, BKMR - binary outcomes - MetS BP indicator - no variable selection}

# Fit BKMR
set.seed(111)
fitkm.novarsel.bpind <- kmbayes(y = Y.cc.bpind, Z = Z[is.cc.bpind,], X = X[is.cc.bpind,], iter = 10000, verbose = FALSE, varsel = FALSE, family = "binomial") 

# Investigate model convergence
TracePlot(fit = fitkm.novarsel.bpind, par = "beta")
TracePlot(fit = fitkm.novarsel.bpind, par = "r", comp = 1)

# Probability scale for RR and RD (adapting Bobb vignette https://jenfb.github.io/bkmr/ProbitEx.html)

  # Exposure quantiles
  Z25.bpind <- matrix(apply(Z[is.cc.bpind, ], 2, quantile, 0.25), nrow = 1)
  Z50.bpind <- matrix(apply(Z[is.cc.bpind, ], 2, quantile, 0.50), nrow = 1)
  Z75.bpind <- matrix(apply(Z[is.cc.bpind, ], 2, quantile, 0.75), nrow = 1)
  
  # Sample covars from their empirical distribution for marginal estimates
  Xvals.bpind <- X[is.cc.bpind, , drop = FALSE] 

  # Generate posterior probabilities and marginalize
  set.seed(111) 
  p25draws.bpind <- get_marginal_probs(Z25.bpind, Xvals.bpind, fitkm.novarsel.bpind, thin=10)
  p50draws.bpind <- get_marginal_probs(Z50.bpind, Xvals.bpind, fitkm.novarsel.bpind, thin=10)
  p75draws.bpind <- get_marginal_probs(Z75.bpind, Xvals.bpind, fitkm.novarsel.bpind, thin=10)

  # Compute RDs and RRs
  RD25to50.bpind <- p50draws.bpind - p25draws.bpind
  RD50to75.bpind <- p75draws.bpind - p50draws.bpind
  
  RR25to50.bpind <- p50draws.bpind / p25draws.bpind
  RR50to75.bpind <- p75draws.bpind / p50draws.bpind
  
  # Get 95% CIs
  results.bpind <- data.frame(
    Contrast = c("25->50", "50->75"),
    RDmean.bpind = c(summarize(RD25to50.bpind)["mean"], summarize(RD50to75.bpind)["mean"]),
    RDl95.bpind  = c(summarize(RD25to50.bpind)["l95"],  summarize(RD50to75.bpind)["l95"]),
    RDu95.bpind  = c(summarize(RD25to50.bpind)["u95"],  summarize(RD50to75.bpind)["u95"]),
    RRmean.bpind = c(summarize(RR25to50.bpind)["mean"], summarize(RR50to75.bpind)["mean"]),
    RRl95.bpind  = c(summarize(RR25to50.bpind)["l95"],  summarize(RR50to75.bpind)["l95"]),
    RRu95.bpind  = c(summarize(RR25to50.bpind)["u95"],  summarize(RR50to75.bpind)["u95"])
  )
  
  results.bpind

# Summarize predictor-response function (probit scale)
risks.overall.bpind <- OverallRiskSummaries(fit = fitkm.novarsel.bpind, y = Y.cc.bpind, Z = Z[is.cc.bpind,], X = X[is.cc.bpind,],
                                      qs = seq(0.25, 0.75, by = 0.05), 
                                      q.fixed = 0.5, method = "exact")
risks.overall.bpind

ggplot(risks.overall.bpind, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
    geom_pointrange() +
    labs(
      x = "Joint quantile", 
      y = "Mean difference"
    )

# Summarize contribution of individual predictors to the response (exploratory - probit)
risks.singvar.bpind <- SingVarRiskSummaries(fit = fitkm.novarsel.bpind, y = Y.cc.bpind, Z = Z[is.cc.bpind,], X = X[is.cc.bpind,],
                                      qs.diff = c(0.25, 0.75), 
                                      q.fixed = c(0.50),
                                      method = "exact")
risks.singvar.bpind

ggplot(risks.singvar.bpind, aes(variable, est, ymin = est - 1.96*sd, 
                          ymax = est + 1.96*sd)) + 
    geom_pointrange(position = position_dodge(width = 0.75), color = "black") + 
    coord_flip() +
    labs(
      x = "Exposure",
      y = "Mean difference") +
    theme(legend.position = "none")

```

```{r, BKMR - binary outcomes - MetS triglycerides indicator - no variable selection}

# Fit BKMR
set.seed(111)
fitkm.novarsel.trind <- kmbayes(y = Y.cc.trind, Z = Z[is.cc.trind,], X = X[is.cc.trind,], iter = 10000, verbose = FALSE, varsel = FALSE, family = "binomial") 

# Investigate model convergence
TracePlot(fit = fitkm.novarsel.trind, par = "beta")
TracePlot(fit = fitkm.novarsel.trind, par = "r", comp = 1)

# Probability scale for RR and RD (adapting Bobb vignette https://jenfb.github.io/bkmr/ProbitEx.html)

  # Exposure quantiles
  Z25.trind <- matrix(apply(Z[is.cc.trind, ], 2, quantile, 0.25), nrow = 1)
  Z50.trind <- matrix(apply(Z[is.cc.trind, ], 2, quantile, 0.50), nrow = 1)
  Z75.trind <- matrix(apply(Z[is.cc.trind, ], 2, quantile, 0.75), nrow = 1)
  
  # Sample covars from their empirical distribution for marginal estimates
  Xvals.trind <- X[is.cc.trind, , drop = FALSE] 

  # Generate posterior probabilities and marginalize
  set.seed(111) 
  p25draws.trind <- get_marginal_probs(Z25.trind, Xvals.trind, fitkm.novarsel.trind, thin=10)
  p50draws.trind <- get_marginal_probs(Z50.trind, Xvals.trind, fitkm.novarsel.trind, thin=10)
  p75draws.trind <- get_marginal_probs(Z75.trind, Xvals.trind, fitkm.novarsel.trind, thin=10)

  # Compute RDs and RRs
  RD25to50.trind <- p50draws.trind - p25draws.trind
  RD50to75.trind <- p75draws.trind - p50draws.trind
  
  RR25to50.trind <- p50draws.trind / p25draws.trind
  RR50to75.trind <- p75draws.trind / p50draws.trind
  
  # Get 95% CIs
  results.trind <- data.frame(
    Contrast = c("25->50", "50->75"),
    RDmean.trind = c(summarize(RD25to50.trind)["mean"], summarize(RD50to75.trind)["mean"]),
    RDl95.trind  = c(summarize(RD25to50.trind)["l95"],  summarize(RD50to75.trind)["l95"]),
    RDu95.trind  = c(summarize(RD25to50.trind)["u95"],  summarize(RD50to75.trind)["u95"]),
    RRmean.trind = c(summarize(RR25to50.trind)["mean"], summarize(RR50to75.trind)["mean"]),
    RRl95.trind  = c(summarize(RR25to50.trind)["l95"],  summarize(RR50to75.trind)["l95"]),
    RRu95.trind  = c(summarize(RR25to50.trind)["u95"],  summarize(RR50to75.trind)["u95"])
  )
  
  results.trind

# Summarize predictor-response function (probit scale)
risks.overall.trind <- OverallRiskSummaries(fit = fitkm.novarsel.trind, y = Y.cc.trind, Z = Z[is.cc.trind,], X = X[is.cc.trind,],
                                      qs = seq(0.25, 0.75, by = 0.05), 
                                      q.fixed = 0.5, method = "exact")
risks.overall.trind

ggplot(risks.overall.trind, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
    geom_pointrange() +
    labs(
      x = "Joint quantile", 
      y = "Mean difference"
    )

# Summarize contribution of individual predictors to the response (exploratory - probit)
risks.singvar.trind <- SingVarRiskSummaries(fit = fitkm.novarsel.trind, y = Y.cc.trind, Z = Z[is.cc.trind,], X = X[is.cc.trind,],
                                      qs.diff = c(0.25, 0.75), 
                                      q.fixed = c(0.50),
                                      method = "exact")
risks.singvar.trind

ggplot(risks.singvar.trind, aes(variable, est, ymin = est - 1.96*sd, 
                          ymax = est + 1.96*sd)) + 
    geom_pointrange(position = position_dodge(width = 0.75), color = "black") + 
    coord_flip() +
    labs(
      x = "Exposure",
      y = "Mean difference") +
    theme(legend.position = "none")

```

```{r, BKMR - binary outcomes - MetS HDL cholesterol indicator - no variable selection}

# Fit BKMR
set.seed(111)
fitkm.novarsel.chind <- kmbayes(y = Y.cc.chind, Z = Z[is.cc.chind,], X = X[is.cc.chind,], iter = 10000, verbose = FALSE, varsel = FALSE, family = "binomial") 

# Investigate model convergence
TracePlot(fit = fitkm.novarsel.chind, par = "beta")
TracePlot(fit = fitkm.novarsel.chind, par = "r", comp = 1)

# Probability scale for RR and RD (adapting Bobb vignette https://jenfb.github.io/bkmr/ProbitEx.html)

  # Exposure quantiles
  Z25.chind <- matrix(apply(Z[is.cc.chind, ], 2, quantile, 0.25), nrow = 1)
  Z50.chind <- matrix(apply(Z[is.cc.chind, ], 2, quantile, 0.50), nrow = 1)
  Z75.chind <- matrix(apply(Z[is.cc.chind, ], 2, quantile, 0.75), nrow = 1)
  
  # Sample covars from their empirical distribution for marginal estimates
  Xvals.chind <- X[is.cc.chind, , drop = FALSE] 

  # Generate posterior probabilities and marginalize
  set.seed(111) 
  p25draws.chind <- get_marginal_probs(Z25.chind, Xvals.chind, fitkm.novarsel.chind, thin=10)
  p50draws.chind <- get_marginal_probs(Z50.chind, Xvals.chind, fitkm.novarsel.chind, thin=10)
  p75draws.chind <- get_marginal_probs(Z75.chind, Xvals.chind, fitkm.novarsel.chind, thin=10)

  # Compute RDs and RRs
  RD25to50.chind <- p50draws.chind - p25draws.chind
  RD50to75.chind <- p75draws.chind - p50draws.chind
  
  RR25to50.chind <- p50draws.chind / p25draws.chind
  RR50to75.chind <- p75draws.chind / p50draws.chind
  
  # Get 95% CIs
  results.chind <- data.frame(
    Contrast = c("25->50", "50->75"),
    RDmean.chind = c(summarize(RD25to50.chind)["mean"], summarize(RD50to75.chind)["mean"]),
    RDl95.chind  = c(summarize(RD25to50.chind)["l95"],  summarize(RD50to75.chind)["l95"]),
    RDu95.chind  = c(summarize(RD25to50.chind)["u95"],  summarize(RD50to75.chind)["u95"]),
    RRmean.chind = c(summarize(RR25to50.chind)["mean"], summarize(RR50to75.chind)["mean"]),
    RRl95.chind  = c(summarize(RR25to50.chind)["l95"],  summarize(RR50to75.chind)["l95"]),
    RRu95.chind  = c(summarize(RR25to50.chind)["u95"],  summarize(RR50to75.chind)["u95"])
  )
  
  results.chind

# Summarize predictor-response function (probit scale)
risks.overall.chind <- OverallRiskSummaries(fit = fitkm.novarsel.chind, y = Y.cc.chind, Z = Z[is.cc.chind,], X = X[is.cc.chind,],
                                      qs = seq(0.25, 0.75, by = 0.05), 
                                      q.fixed = 0.5, method = "exact")
risks.overall.chind

ggplot(risks.overall.chind, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
    geom_pointrange() +
    labs(
      x = "Joint quantile", 
      y = "Mean difference"
    )

# Summarize contribution of individual predictors to the response (exploratory - probit)
risks.singvar.chind <- SingVarRiskSummaries(fit = fitkm.novarsel.chind, y = Y.cc.chind, Z = Z[is.cc.chind,], X = X[is.cc.chind,],
                                      qs.diff = c(0.25, 0.75), 
                                      q.fixed = c(0.50),
                                      method = "exact")
risks.singvar.chind

ggplot(risks.singvar.chind, aes(variable, est, ymin = est - 1.96*sd, 
                          ymax = est + 1.96*sd)) + 
    geom_pointrange(position = position_dodge(width = 0.75), color = "black") + 
    coord_flip() +
    labs(
      x = "Exposure",
      y = "Mean difference") +
    theme(legend.position = "none")

```

```{r, BKMR - binary outcomes - MetS glucose indicator - no variable selection}

# Fit BKMR
set.seed(111)
fitkm.novarsel.glind <- kmbayes(y = Y.cc.glind, Z = Z[is.cc.glind,], X = X[is.cc.glind,], iter = 10000, verbose = FALSE, varsel = FALSE, family = "binomial") 

# Investigate model convergence
TracePlot(fit = fitkm.novarsel.glind, par = "beta")
TracePlot(fit = fitkm.novarsel.glind, par = "r", comp = 1)

# Probability scale for RR and RD (adapting Bobb vignette https://jenfb.github.io/bkmr/ProbitEx.html)

  # Exposure quantiles
  Z25.glind <- matrix(apply(Z[is.cc.glind, ], 2, quantile, 0.25), nrow = 1)
  Z50.glind <- matrix(apply(Z[is.cc.glind, ], 2, quantile, 0.50), nrow = 1)
  Z75.glind <- matrix(apply(Z[is.cc.glind, ], 2, quantile, 0.75), nrow = 1)
  
  # Sample covars from their empirical distribution for marginal estimates
  Xvals.glind <- X[is.cc.glind, , drop = FALSE] 

  # Generate posterior probabilities and marginalize
  set.seed(111) 
  p25draws.glind <- get_marginal_probs(Z25.glind, Xvals.glind, fitkm.novarsel.glind, thin=10)
  p50draws.glind <- get_marginal_probs(Z50.glind, Xvals.glind, fitkm.novarsel.glind, thin=10)
  p75draws.glind <- get_marginal_probs(Z75.glind, Xvals.glind, fitkm.novarsel.glind, thin=10)

  # Compute RDs and RRs
  RD25to50.glind <- p50draws.glind - p25draws.glind
  RD50to75.glind <- p75draws.glind - p50draws.glind
  
  RR25to50.glind <- p50draws.glind / p25draws.glind
  RR50to75.glind <- p75draws.glind / p50draws.glind
  
  # Get 95% CIs
  results.glind <- data.frame(
    Contrast = c("25->50", "50->75"),
    RDmean.glind = c(summarize(RD25to50.glind)["mean"], summarize(RD50to75.glind)["mean"]),
    RDl95.glind  = c(summarize(RD25to50.glind)["l95"],  summarize(RD50to75.glind)["l95"]),
    RDu95.glind  = c(summarize(RD25to50.glind)["u95"],  summarize(RD50to75.glind)["u95"]),
    RRmean.glind = c(summarize(RR25to50.glind)["mean"], summarize(RR50to75.glind)["mean"]),
    RRl95.glind  = c(summarize(RR25to50.glind)["l95"],  summarize(RR50to75.glind)["l95"]),
    RRu95.glind  = c(summarize(RR25to50.glind)["u95"],  summarize(RR50to75.glind)["u95"])
  )
  
  results.glind

# Summarize predictor-response function (probit scale)
risks.overall.glind <- OverallRiskSummaries(fit = fitkm.novarsel.glind, y = Y.cc.glind, Z = Z[is.cc.glind,], X = X[is.cc.glind,],
                                      qs = seq(0.25, 0.75, by = 0.05), 
                                      q.fixed = 0.5, method = "exact")
risks.overall.glind

ggplot(risks.overall.glind, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
    geom_pointrange() +
    labs(
      x = "Joint quantile", 
      y = "Mean difference"
    )

# Summarize contribution of individual predictors to the response (exploratory - probit)
risks.singvar.glind <- SingVarRiskSummaries(fit = fitkm.novarsel.glind, y = Y.cc.glind, Z = Z[is.cc.glind,], X = X[is.cc.glind,],
                                      qs.diff = c(0.25, 0.75), 
                                      q.fixed = c(0.50),
                                      method = "exact")
risks.singvar.glind

ggplot(risks.singvar.glind, aes(variable, est, ymin = est - 1.96*sd, 
                          ymax = est + 1.96*sd)) + 
    geom_pointrange(position = position_dodge(width = 0.75), color = "black") + 
    coord_flip() +
    labs(
      x = "Exposure",
      y = "Mean difference") +
    theme(legend.position = "none")

```

```{r, BKMR - binary outcomes - MetS waist indicator - no variable selection}

# Fit BKMR
set.seed(111)
fitkm.novarsel.waind <- kmbayes(y = Y.cc.waind, Z = Z[is.cc.waind,], X = X[is.cc.waind,], iter = 10000, verbose = FALSE, varsel = FALSE, family = "binomial") 

# Investigate model convergence
TracePlot(fit = fitkm.novarsel.waind, par = "beta")
TracePlot(fit = fitkm.novarsel.waind, par = "r", comp = 1)

# Probability scale for RR and RD (adapting Bobb vignette https://jenfb.github.io/bkmr/ProbitEx.html)

  # Exposure quantiles
  Z25.waind <- matrix(apply(Z[is.cc.waind, ], 2, quantile, 0.25), nrow = 1)
  Z50.waind <- matrix(apply(Z[is.cc.waind, ], 2, quantile, 0.50), nrow = 1)
  Z75.waind <- matrix(apply(Z[is.cc.waind, ], 2, quantile, 0.75), nrow = 1)
  
  # Sample covars from their empirical distribution for marginal estimates
  Xvals.waind <- X[is.cc.waind, , drop = FALSE] 

  # Generate posterior probabilities and marginalize
  set.seed(111) 
  p25draws.waind <- get_marginal_probs(Z25.waind, Xvals.waind, fitkm.novarsel.waind, thin=10)
  p50draws.waind <- get_marginal_probs(Z50.waind, Xvals.waind, fitkm.novarsel.waind, thin=10)
  p75draws.waind <- get_marginal_probs(Z75.waind, Xvals.waind, fitkm.novarsel.waind, thin=10)

  # Compute RDs and RRs
  RD25to50.waind <- p50draws.waind - p25draws.waind
  RD50to75.waind <- p75draws.waind - p50draws.waind
  
  RR25to50.waind <- p50draws.waind / p25draws.waind
  RR50to75.waind <- p75draws.waind / p50draws.waind
  
  # Get 95% CIs
  results.waind <- data.frame(
    Contrast = c("25->50", "50->75"),
    RDmean.waind = c(summarize(RD25to50.waind)["mean"], summarize(RD50to75.waind)["mean"]),
    RDl95.waind  = c(summarize(RD25to50.waind)["l95"],  summarize(RD50to75.waind)["l95"]),
    RDu95.waind  = c(summarize(RD25to50.waind)["u95"],  summarize(RD50to75.waind)["u95"]),
    RRmean.waind = c(summarize(RR25to50.waind)["mean"], summarize(RR50to75.waind)["mean"]),
    RRl95.waind  = c(summarize(RR25to50.waind)["l95"],  summarize(RR50to75.waind)["l95"]),
    RRu95.waind  = c(summarize(RR25to50.waind)["u95"],  summarize(RR50to75.waind)["u95"])
  )
  
  results.waind

# Summarize predictor-response function (probit scale)
risks.overall.waind <- OverallRiskSummaries(fit = fitkm.novarsel.waind, y = Y.cc.waind, Z = Z[is.cc.waind,], X = X[is.cc.waind,],
                                      qs = seq(0.25, 0.75, by = 0.05), 
                                      q.fixed = 0.5, method = "exact")
risks.overall.waind

ggplot(risks.overall.waind, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
    geom_pointrange() +
    labs(
      x = "Joint quantile", 
      y = "Mean difference"
    )

# Summarize contribution of individual predictors to the response (exploratory - probit)
risks.singvar.waind <- SingVarRiskSummaries(fit = fitkm.novarsel.waind, y = Y.cc.waind, Z = Z[is.cc.waind,], X = X[is.cc.waind,],
                                      qs.diff = c(0.25, 0.75), 
                                      q.fixed = c(0.50),
                                      method = "exact")
risks.singvar.waind

ggplot(risks.singvar.waind, aes(variable, est, ymin = est - 1.96*sd, 
                          ymax = est + 1.96*sd)) + 
    geom_pointrange(position = position_dodge(width = 0.75), color = "black") + 
    coord_flip() +
    labs(
      x = "Exposure",
      y = "Mean difference") +
    theme(legend.position = "none")

```

```{r, BKMR - binary outcomes - metabolic syndrome - no variable selection}

# Fit BKMR
set.seed(111)
fitkm.novarsel.metab <- kmbayes(y = Y.cc.metab, Z = Z[is.cc.metab,], X = X[is.cc.metab,], iter = 10000, verbose = FALSE, varsel = FALSE, family = "binomial") 

# Investigate model convergence
TracePlot(fit = fitkm.novarsel.metab, par = "beta")
TracePlot(fit = fitkm.novarsel.metab, par = "r", comp = 1)

# Probability scale for RR and RD (adapting Bobb vignette https://jenfb.github.io/bkmr/ProbitEx.html)

  # Exposure quantiles
  Z25.metab <- matrix(apply(Z[is.cc.metab, ], 2, quantile, 0.25), nrow = 1)
  Z50.metab <- matrix(apply(Z[is.cc.metab, ], 2, quantile, 0.50), nrow = 1)
  Z75.metab <- matrix(apply(Z[is.cc.metab, ], 2, quantile, 0.75), nrow = 1)
  
  # Sample covars from their empirical distribution for marginal estimates
  Xvals.metab <- X[is.cc.metab, , drop = FALSE] 

  # Generate posterior probabilities and marginalize
  set.seed(111) 
  p25draws.metab <- get_marginal_probs(Z25.metab, Xvals.metab, fitkm.novarsel.metab, thin=10)
  p50draws.metab <- get_marginal_probs(Z50.metab, Xvals.metab, fitkm.novarsel.metab, thin=10)
  p75draws.metab <- get_marginal_probs(Z75.metab, Xvals.metab, fitkm.novarsel.metab, thin=10)

  # Compute RDs and RRs
  RD25to50.metab <- p50draws.metab - p25draws.metab
  RD50to75.metab <- p75draws.metab - p50draws.metab
  
  RR25to50.metab <- p50draws.metab / p25draws.metab
  RR50to75.metab <- p75draws.metab / p50draws.metab
  
  # Get 95% CIs
  results.metab <- data.frame(
    Contrast = c("25->50", "50->75"),
    RDmean.metab = c(summarize(RD25to50.metab)["mean"], summarize(RD50to75.metab)["mean"]),
    RDl95.metab  = c(summarize(RD25to50.metab)["l95"],  summarize(RD50to75.metab)["l95"]),
    RDu95.metab  = c(summarize(RD25to50.metab)["u95"],  summarize(RD50to75.metab)["u95"]),
    RRmean.metab = c(summarize(RR25to50.metab)["mean"], summarize(RR50to75.metab)["mean"]),
    RRl95.metab  = c(summarize(RR25to50.metab)["l95"],  summarize(RR50to75.metab)["l95"]),
    RRu95.metab  = c(summarize(RR25to50.metab)["u95"],  summarize(RR50to75.metab)["u95"])
  )
  
  results.metab

# Summarize predictor-response function (probit scale)
risks.overall.metab <- OverallRiskSummaries(fit = fitkm.novarsel.metab, y = Y.cc.metab, Z = Z[is.cc.metab,], X = X[is.cc.metab,],
                                      qs = seq(0.25, 0.75, by = 0.05), 
                                      q.fixed = 0.5, method = "exact")
risks.overall.metab

ggplot(risks.overall.metab, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
    geom_pointrange() +
    labs(
      x = "Joint quantile", 
      y = "Mean difference"
    )

# Summarize contribution of individual predictors to the response (exploratory - probit)
risks.singvar.metab <- SingVarRiskSummaries(fit = fitkm.novarsel.metab, y = Y.cc.metab, Z = Z[is.cc.metab,], X = X[is.cc.metab,],
                                      qs.diff = c(0.25, 0.75), 
                                      q.fixed = c(0.50),
                                      method = "exact")
risks.singvar.metab

ggplot(risks.singvar.metab, aes(variable, est, ymin = est - 1.96*sd, 
                          ymax = est + 1.96*sd)) + 
    geom_pointrange(position = position_dodge(width = 0.75), color = "black") + 
    coord_flip() +
    labs(
      x = "Exposure",
      y = "Mean difference") +
    theme(legend.position = "none")

```

```{r, BKMR - binary outcomes - elevated CRP - no variable selection}

# Fit BKMR
set.seed(111)
fitkm.novarsel.crpca <- kmbayes(y = Y.cc.crpca, Z = Z[is.cc.crpca,], X = X[is.cc.crpca,], iter = 10000, verbose = FALSE, varsel = FALSE, family = "binomial") 

# Investigate model convergence
TracePlot(fit = fitkm.novarsel.crpca, par = "beta")
TracePlot(fit = fitkm.novarsel.crpca, par = "r", comp = 1)

# Probability scale for RR and RD (adapting Bobb vignette https://jenfb.github.io/bkmr/ProbitEx.html)

  # Exposure quantiles
  Z25.crpca <- matrix(apply(Z[is.cc.crpca, ], 2, quantile, 0.25), nrow = 1)
  Z50.crpca <- matrix(apply(Z[is.cc.crpca, ], 2, quantile, 0.50), nrow = 1)
  Z75.crpca <- matrix(apply(Z[is.cc.crpca, ], 2, quantile, 0.75), nrow = 1)
  
  # Sample covars from their empirical distribution for marginal estimates
  Xvals.crpca <- X[is.cc.crpca, , drop = FALSE] 

  # Generate posterior probabilities and marginalize
  set.seed(111) 
  p25draws.crpca <- get_marginal_probs(Z25.crpca, Xvals.crpca, fitkm.novarsel.crpca, thin=10)
  p50draws.crpca <- get_marginal_probs(Z50.crpca, Xvals.crpca, fitkm.novarsel.crpca, thin=10)
  p75draws.crpca <- get_marginal_probs(Z75.crpca, Xvals.crpca, fitkm.novarsel.crpca, thin=10)

  # Compute RDs and RRs
  RD25to50.crpca <- p50draws.crpca - p25draws.crpca
  RD50to75.crpca <- p75draws.crpca - p50draws.crpca
  
  RR25to50.crpca <- p50draws.crpca / p25draws.crpca
  RR50to75.crpca <- p75draws.crpca / p50draws.crpca
  
  # Get 95% CIs
  results.crpca <- data.frame(
    Contrast = c("25->50", "50->75"),
    RDmean.crpca = c(summarize(RD25to50.crpca)["mean"], summarize(RD50to75.crpca)["mean"]),
    RDl95.crpca  = c(summarize(RD25to50.crpca)["l95"],  summarize(RD50to75.crpca)["l95"]),
    RDu95.crpca  = c(summarize(RD25to50.crpca)["u95"],  summarize(RD50to75.crpca)["u95"]),
    RRmean.crpca = c(summarize(RR25to50.crpca)["mean"], summarize(RR50to75.crpca)["mean"]),
    RRl95.crpca  = c(summarize(RR25to50.crpca)["l95"],  summarize(RR50to75.crpca)["l95"]),
    RRu95.crpca  = c(summarize(RR25to50.crpca)["u95"],  summarize(RR50to75.crpca)["u95"])
  )
  
  results.crpca

# Summarize predictor-response function (probit scale)
risks.overall.crpca <- OverallRiskSummaries(fit = fitkm.novarsel.crpca, y = Y.cc.crpca, Z = Z[is.cc.crpca,], X = X[is.cc.crpca,],
                                      qs = seq(0.25, 0.75, by = 0.05), 
                                      q.fixed = 0.5, method = "exact")
risks.overall.crpca

ggplot(risks.overall.crpca, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
    geom_pointrange() +
    labs(
      x = "Joint quantile", 
      y = "Mean difference"
    )

# Summarize contribution of individual predictors to the response (exploratory - probit)
risks.singvar.crpca <- SingVarRiskSummaries(fit = fitkm.novarsel.crpca, y = Y.cc.crpca, Z = Z[is.cc.crpca,], X = X[is.cc.crpca,],
                                      qs.diff = c(0.25, 0.75), 
                                      q.fixed = c(0.50),
                                      method = "exact")
risks.singvar.crpca

ggplot(risks.singvar.crpca, aes(variable, est, ymin = est - 1.96*sd, 
                          ymax = est + 1.96*sd)) + 
    geom_pointrange(position = position_dodge(width = 0.75), color = "black") + 
    coord_flip() +
    labs(
      x = "Exposure",
      y = "Mean difference") +
    theme(legend.position = "none")

```
